@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Feb 13 13:30:50 CET 2025

title Jira Tickets for Person Levi van Hoorn | Tadaah
hide empty members

legend
Jira Ticket Status
----
Backlog : 7
Actief : 2
----
Jira Ticket Types
----
Taak : 7
Bug : 2
end legend


' Tickets =======
class "Taak" << (T,lightblue) >> {
 Summary : please change the 'standaard bemiddelingsovereenkomst' for all organisations & freelancers
 Assigned to : Levi van Hoorn | Tadaah
 Status : Backlog
 Type : Taak
Total  Points : 0
}

class "Taak" << (T,lightblue) >> {
 Summary : [2984] is rejected at KYC, but doesn't see Rejection reason and sees Paid On date on her invoice in the App (Ruveyda Kilic)
 Assigned to : Levi van Hoorn | Tadaah
 Status : Backlog
 Type : Taak
Total  Points : 0
}

class "Taak" << (T,lightblue) >> {
 Summary : password reset
 Assigned to : Levi van Hoorn | Tadaah
 Status : Backlog
 Type : Taak
Total  Points : 0
}

class "Taak" << (T,lightblue) >> {
 Summary : Can we add certificate title? FL_issue[5506]
 Assigned to : Levi van Hoorn | Tadaah
 Status : Backlog
 Type : Taak
Total  Points : 0
}

class "Taak" << (T,lightblue) >> {
 Summary : FL doesn't recieve mail when ask for password reset
 Assigned to : Levi van Hoorn | Tadaah
 Status : Backlog
 Type : Taak
Total  Points : 0
}

class "Taak" << (T,lightblue) >> {
 Summary : add info to org. [153] Oase
 Assigned to : Levi van Hoorn | Tadaah
 Status : Backlog
 Type : Taak
Total  Points : 0
}

class "Bug" << (B,red) >> {
 Summary : [3574] button 'certificaten toevoegen' isn't visable
 Assigned to : Levi van Hoorn | Tadaah
 Status : Backlog
 Type : Bug
Total  Points : 0
}

class "Bug" << (B,red) >> {
 Summary : Certificate Type is not available to Add again if Migrated Certificate was deleted
 Assigned to : Levi van Hoorn | Tadaah
 Status : Actief
 Type : Bug
Total  Points : 0
}

class "Taak" << (T,lightblue) >> {
 Summary : FL been waiting months, so please TODAY [5016] Karin Hackfoort VVE title is gone
 Assigned to : Levi van Hoorn | Tadaah
 Status : Actief
 Type : Taak
Total  Points : 0
}



' Links =======


@enduml
