@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Wed May 29 11:49:43 CEST 2024

title Jira Tickets for Status TECH REVIEW (pls tag reviewer)
hide empty members

legend
Jira Ticket Status
----
To Do : 1
TECH REVIEW (pls tag reviewer) : 2
----
Jira Ticket Types
----
Epic : 1
Bug : 1
Story : 1
end legend


' Tickets =======
class "ARS-115" << (B,red) >> {
 Summary : Correct the URL of /Admin/post_admin
 Assigned to : PAOLO BRUNASTI
 Status : TECH REVIEW (pls tag reviewer)
 Type : Bug
 Points : 1.0
Total  Points : 1
}

class "ARS-91" << (S,lightgreen) >> {
 Summary : Content Modelling for Questions Page
 Assigned to : Nneka Tielman
 Status : TECH REVIEW (pls tag reviewer)
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-2" << (E,green) >> {
 Summary : Survey Questions Pages
 Status : To Do
 Type : Epic
Total  Points : 28
}



' Links =======
"ARS-91" <.. "ARS-2" : Issue split


@enduml
