@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Wed May 29 11:49:43 CEST 2024

title Jira Tickets for Person Pablo Uhalte
hide empty members

legend
Jira Ticket Status
----
To Do : 6
Done : 1
In Progress : 1
----
Jira Ticket Types
----
Spike : 1
Subtask : 3
Story : 4
end legend


' Tickets =======
class "ARS-60" << (S,lightblue) >> {
 Summary : Cleanse and standardize data coming from the responses
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-6" << (S,lightgreen) >> {
 Summary : CP Dashboard for results analysis
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-61" << (S,lightblue) >> {
 Summary : Creation of the visuals
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-62" << (X,lightblue) >> {
 Summary : Spike - AI personalised roadmap
 Assigned to : Pablo Uhalte
 Status : Done
 Type : Spike
Total  Points : 0
}

class "ARS-7" << (S,lightgreen) >> {
 Summary : CP AI-Powered Personalised Roadmap Component
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-59" << (S,lightblue) >> {
 Summary : Connect tool to the database 
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-74" << (S,lightgreen) >> {
 Summary : Implement FE API - submit survey endpoint
 Status : To Do
 Type : Story
 Points : 8.0
Total  Points : 8
}

class "ARS-75" << (S,lightgreen) >> {
 Summary : Generate pdf with spider graph
 Assigned to : Pablo Uhalte
 Status : In Progress
 Type : Story
 Points : 8.0
Total  Points : 8
}



' Links =======
"ARS-75" <.. "ARS-74" : Issue split



@enduml
