@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue May 21 11:41:23 CEST 2024

title Jira Tickets for Person Juan Solano
hide empty members

legend
Jira Ticket Status
----
Done : 13
To Do : 3
In Progress : 2
----
Jira Ticket Types
----
Story : 18
end legend


' Tickets =======
class "ARS-16" << (S,lightgreen) >> {
 Summary : Contentful Content Modeling for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-38" << (S,lightgreen) >> {
 Summary : Generate Gitlab Pipeline
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-17" << (S,lightgreen) >> {
 Summary : Generate Content Types GraphQL Queries for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-19" << (S,lightgreen) >> {
 Summary : Create NUXT -Vue2 project FE
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-56" << (S,lightgreen) >> {
 Summary : Input Fields Validation
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-78" << (S,lightgreen) >> {
 Summary : Create Image Component for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-34" << (S,lightgreen) >> {
 Summary : All Survey Pages - Create Theme
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-57" << (S,lightgreen) >> {
 Summary : Banner component
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-58" << (S,lightgreen) >> {
 Summary : Button components
 Assigned to : Juan Solano
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-14" << (S,lightgreen) >> {
 Summary : Set up Contentful Account
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 2.0
Total  Points : 2
}

class "ARS-36" << (S,lightgreen) >> {
 Summary : Landing Page - Input fields Component
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-15" << (S,lightgreen) >> {
 Summary : Contentful Integration FE
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-37" << (S,lightgreen) >> {
 Summary : Create Eslint modules
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-1" << (S,lightgreen) >> {
 Summary : Survey Landing Page
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-53" << (S,lightgreen) >> {
 Summary : Navbar component for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-54" << (S,lightgreen) >> {
 Summary : Footer component
 Assigned to : Juan Solano
 Status : In Progress
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-55" << (S,lightgreen) >> {
 Summary : Typography component
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-77" << (S,lightgreen) >> {
 Summary : Add Font to the Tailwind Config
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 2.0
Total  Points : 2
}



' Links =======
"ARS-56" <.. "ARS-1" : Issue split

"ARS-36" <.. "ARS-1" : Issue split

"ARS-1" <.. "ARS-14" : Polaris issue link

"ARS-1" <.. "ARS-15" : Polaris issue link

"ARS-1" <.. "ARS-16" : Polaris issue link

"ARS-1" <.. "ARS-17" : Polaris issue link



@enduml
