@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon May 27 11:35:03 CEST 2024

title Jira Tickets for Epic Survey Landing Page
hide empty members

legend
Jira Ticket Status
----
To Do : 2
In Progress : 2
----
Jira Ticket Types
----
Epic : 1
Story : 3
end legend


' Tickets =======
class "ARS-92" << (S,lightgreen) >> {
 Summary : Integration between BE and FE from the Landing Page
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-56" << (S,lightgreen) >> {
 Summary : Input Fields Validation
 Assigned to : Juan Solano
 Status : In Progress
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-36" << (S,lightgreen) >> {
 Summary : Landing Page - Input fields Component and Form
 Assigned to : Juan Solano
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-1" << (E,green) >> {
 Summary : Survey Landing Page
 Assigned to : Juan Solano
 Status : To Do
 Type : Epic
Total  Points : 11
}



' Links =======

' Parents =======
"ARS-1" <|-- "ARS-92"
"ARS-1" <|-- "ARS-56"
"ARS-1" <|-- "ARS-36"

"ARS-56" <.. "ARS-1" : Issue split

"ARS-36" <.. "ARS-1" : Issue split

"ARS-1" <.. "ARS-14" : Polaris issue link

"ARS-1" <.. "ARS-15" : Polaris issue link

"ARS-1" <.. "ARS-16" : Polaris issue link

"ARS-1" <.. "ARS-17" : Polaris issue link



@enduml
