@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue May 14 15:35:46 CEST 2024

title Jira Tickets for Person Nneka Tielman
hide empty members

legend
Jira Ticket Status
----
(Done) : 2
(To Do) : 1
----
Jira Ticket Types
----
(Story) : 3
end legend


' Tickets =======
class "ARS-49" << (S,lightgreen) >> {
  Summary : research connect Contentful to postgreSQL
  Assigned to : Nneka Tielman
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-25" << (S,lightgreen) >> {
  Summary : Design APIs
  Assigned to : Nneka Tielman
  Status : Done
  Type : Story
  Points : 5.0
}

class "ARS-26" << (S,lightgreen) >> {
  Summary : Implement APIs
  Assigned to : Nneka Tielman
  Status : To Do
  Type : Story
  Points : 8.0
}



' Links =======


@enduml
