@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:03:14 CEST 2024

title Jira Tickets for Status Done
hide empty members

legend
Jira Ticket Status
----
(Done) : 9
----
Jira Ticket Types
----
(Task) : 4
(Epic) : 1
(Story) : 4
end legend


' Tickets =======
class "ENKPS-19" << (T,lightblue) >> {
  Assigned to : Juan Solano
  Status : Done
  Type : Task
}

class "ENKPS-4" << (S,lightgreen) >> {
  Status : Done
  Type : Story
}

class "ENKPS-41" << (X,lightblue) >> {
  Status : Done
  Type : Epic
}

class "ENKPS-32" << (S,lightgreen) >> {
  Status : Done
  Type : Story
}

class "ENKPS-21" << (T,lightblue) >> {
  Assigned to : Eniko Kosztolanyi
  Status : Done
  Type : Task
}

class "ENKPS-34" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "ENKPS-35" << (S,lightgreen) >> {
  Status : Done
  Type : Story
}

class "ENKPS-36" << (S,lightgreen) >> {
  Status : Done
  Type : Story
}

class "ENKPS-18" << (T,lightblue) >> {
  Assigned to : Eniko Kosztolanyi
  Status : Done
  Type : Task
}



' Links =======


@enduml
