@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Wed May 29 11:49:43 CEST 2024

title Jira Tickets for Status To Do
hide empty members

legend
Jira Ticket Status
----
To Do : 49
Done : 6
In Progress : 1
----
Jira Ticket Types
----
Subtask : 14
Epic : 5
Bug : 2
Story : 35
end legend


' Tickets =======
class "ARS-114" << (S,lightblue) >> {
 Summary : Connect Internet Gateway to VPN and EC2 instances
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-113" << (S,lightblue) >> {
 Summary : Create Internet Gateway
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-118" << (B,red) >> {
 Summary : Avoid duplication of users in POST /users execution
 Status : To Do
 Type : Bug
 Points : 3.0
Total  Points : 3
}

class "ARS-16" << (S,lightgreen) >> {
 Summary : Contentful Content Modeling for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-117" << (S,lightgreen) >> {
 Summary : Add execution time computing to all endpoints
 Status : To Do
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-17" << (S,lightgreen) >> {
 Summary : Generate Content Types GraphQL Queries for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-18" << (S,lightgreen) >> {
 Summary : Create Repository
 Assigned to : PAOLO BRUNASTI
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-119" << (B,red) >> {
 Summary : Add endpoints to get the "tables" values
 Status : To Do
 Type : Bug
 Points : 3.0
Total  Points : 3
}

class "ARS-110" << (S,lightgreen) >> {
 Summary : Content Modelling for Results Page
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-93" << (S,lightgreen) >> {
 Summary : Questions Page - Dimension component
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-94" << (S,lightgreen) >> {
 Summary : Questions Page - Radio buttons with text
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-95" << (S,lightgreen) >> {
 Summary : Questions Page - Previous and Next button
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-12" << (S,lightblue) >> {
 Summary : Send email to customer with the PDF as attachment
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-13" << (S,lightblue) >> {
 Summary : Activation of the process of generating and sending the email
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-14" << (S,lightgreen) >> {
 Summary : Set up Contentful Account
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 2.0
Total  Points : 2
}

class "ARS-59" << (S,lightblue) >> {
 Summary : Connect tool to the database 
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-15" << (S,lightgreen) >> {
 Summary : Contentful Integration FE
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-11" << (S,lightblue) >> {
 Summary : Generate the PDF with the report for a single survey response
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-27" << (S,lightgreen) >> {
 Summary : Design the CICD Pipeline
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-29" << (S,lightblue) >> {
 Summary : CICD Pipeline for BE
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-60" << (S,lightblue) >> {
 Summary : Cleanse and standardize data coming from the responses
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-61" << (S,lightblue) >> {
 Summary : Creation of the visuals
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-68" << (S,lightblue) >> {
 Summary : Security
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-26" << (S,lightgreen) >> {
 Summary : Implement APIs
 Assigned to : Nneka Tielman
 Status : Done
 Type : Story
Total  Points : 0
}

class "ARS-63" << (S,lightgreen) >> {
 Summary : Implement Analytics API - user endpoints
 Status : To Do
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-64" << (S,lightgreen) >> {
 Summary : Auth for Analytics API
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-39" << (S,lightblue) >> {
 Summary : Investigate HubSpot integration
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-70" << (S,lightblue) >> {
 Summary : Connection with Contentful
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-5" << (S,lightgreen) >> {
 Summary : Email with Results as a pdf
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-6" << (S,lightgreen) >> {
 Summary : CP Dashboard for results analysis
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-72" << (S,lightgreen) >> {
 Summary : Implement Analytics API - results endpoints
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-3" << (S,lightgreen) >> {
 Summary : Questions Page - Dimensions Progress Bar Component
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
 Points : 8.0
Total  Points : 8
}

class "ARS-4" << (S,lightgreen) >> {
 Summary : Survey Results Page
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-9" << (S,lightgreen) >> {
 Summary : Results Page - Personalised High-Level Roadmap Component with AI
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-7" << (S,lightgreen) >> {
 Summary : CP AI-Powered Personalised Roadmap Component
 Assigned to : Pablo Uhalte
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-8" << (S,lightgreen) >> {
 Summary : Results Page - Scoring Graphic Component
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-79" << (E,green) >> {
 Summary : Final Report
 Status : To Do
 Type : Epic
Total  Points : 0
}

class "ARS-74" << (S,lightgreen) >> {
 Summary : Implement FE API - submit survey endpoint
 Status : To Do
 Type : Story
 Points : 8.0
Total  Points : 8
}

class "ARS-1" << (E,green) >> {
 Summary : Survey Landing Page
 Assigned to : Juan Solano
 Status : To Do
 Type : Epic
Total  Points : 11
}

class "ARS-31" << (E,green) >> {
 Summary : Front End for Survey
 Status : To Do
 Type : Epic
Total  Points : 0
}

class "ARS-2" << (E,green) >> {
 Summary : Survey Questions Pages
 Status : To Do
 Type : Epic
Total  Points : 28
}

class "ARS-33" << (S,lightgreen) >> {
 Summary : Questions Page - Save Survey Progress
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-103" << (S,lightblue) >> {
 Summary : Connect EC2 to S3
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-105" << (E,green) >> {
 Summary : Survey Results Page
 Status : To Do
 Type : Epic
Total  Points : 0
}

class "ARS-107" << (S,lightgreen) >> {
 Summary : Error Page
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-101" << (S,lightblue) >> {
 Summary : Automate deployment of BE app on EC2
 Status : To Do
 Type : Subtask
Total  Points : 0
}

class "ARS-82" << (S,lightgreen) >> {
 Summary : Implement the result algorithm
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-83" << (S,lightgreen) >> {
 Summary : Mechanism to replace the tags in the texts
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-40" << (S,lightgreen) >> {
 Summary : AWS Environment
 Assigned to : PAOLO BRUNASTI
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-80" << (S,lightgreen) >> {
 Summary : Store the different Dimension Responses for the result in the DB
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-48" << (S,lightgreen) >> {
 Summary : Questions Page - Scroll progress bar
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-41" << (S,lightgreen) >> {
 Summary : Questions Page - Personalised with company name
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-85" << (S,lightgreen) >> {
 Summary : Security and Configuration : place connection values in a .env file for more security
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-42" << (S,lightgreen) >> {
 Summary : Results Page - Personalised Thank you message
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-43" << (S,lightgreen) >> {
 Summary : Survey Hubspot integration
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Story
 Points : 8.0
Total  Points : 8
}

class "ARS-87" << (S,lightgreen) >> {
 Summary : Cleanup VW Tailwind classes
 Status : To Do
 Type : Story
Total  Points : 0
}



' Links =======
"ARS-27" <.. "ARS-18" : Blocks
"ARS-27" <.. "ARS-40" : Blocks
"ARS-33" <.. "ARS-2" : Issue split
"ARS-42" <.. "ARS-4" : Polaris datapoint issue link
"ARS-63" <.. "ARS-26" : Issue split
"ARS-64" <.. "ARS-72" : Blocks
"ARS-64" <.. "ARS-63" : Blocks
"ARS-64" <.. "ARS-26" : Issue split
"ARS-5" <.. "ARS-74" : Issue split
"ARS-72" <.. "ARS-26" : Issue split
"ARS-3" <.. "ARS-2" : Issue split
"ARS-9" <.. "ARS-4" : Issue split
"ARS-8" <.. "ARS-4" : Issue split
"ARS-74" <.. "ARS-26" : Issue split
"ARS-74" <.. "ARS-43" : Relates
"ARS-1" <.. "ARS-14" : Polaris issue link
"ARS-1" <.. "ARS-15" : Polaris issue link
"ARS-1" <.. "ARS-16" : Polaris issue link
"ARS-1" <.. "ARS-17" : Polaris issue link
"ARS-2" <.. "ARS-48" : Polaris datapoint issue link
"ARS-2" <.. "ARS-41" : Polaris datapoint issue link


@enduml
