@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue May 14 12:25:21 CEST 2024

title Jira Tickets for Status Done
hide empty members

legend
Jira Ticket Status
----
(Done) : 11
(To Do) : 1
----
Jira Ticket Types
----
(Subtask) : 1
(Story) : 11
end legend


' Tickets =======
class "ARS-16" << (S,lightgreen) >> {
  Summary : Contentful Content Modeling for Landing Page
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 5.0
}

class "ARS-38" << (S,lightgreen) >> {
  Summary : Generate Gitlab Pipeline
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-49" << (S,lightgreen) >> {
  Summary : research connect Contentful to postgreSQL
  Assigned to : Nneka Tielman
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-18" << (S,lightgreen) >> {
  Summary : Create Repository
  Assigned to : PAOLO BRUNASTI
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-19" << (S,lightgreen) >> {
  Summary : Create NUXT -Vue2 project FE
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-45" << (S,lightgreen) >> {
  Summary : Review Gitlab Pipeline
  Assigned to : PAOLO BRUNASTI
  Status : Done
  Type : Story
}

class "ARS-14" << (S,lightgreen) >> {
  Summary : Set up Contentful Account
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 2.0
}

class "ARS-37" << (S,lightgreen) >> {
  Summary : Create Eslint modules
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-15" << (S,lightgreen) >> {
  Summary : Contentful Integration FE
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-52" << (S,lightgreen) >> {
  Summary : Prototype BE architecture
  Assigned to : PAOLO BRUNASTI
  Status : To Do
  Type : Story
  Points : 5.0
}

class "ARS-21" << (S,lightblue) >> {
  Summary : Create GitHub repository for BE
  Assigned to : PAOLO BRUNASTI
  Status : Done
  Type : Subtask
}

class "ARS-22" << (S,lightgreen) >> {
  Summary : Define BE architecture
  Assigned to : PAOLO BRUNASTI
  Status : Done
  Type : Story
  Points : 5.0
}



' Links =======
"ARS-18" <.. "ARS-37" : Polaris issue link
"ARS-18" <.. "ARS-38" : Polaris issue link
"ARS-22" <.. "ARS-52" : Cloners


@enduml
