@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Wed May 29 11:49:43 CEST 2024

title Jira Tickets for Link Type Polaris datapoint issue link
hide empty members

legend
Jira Ticket Status
----
To Do : 5
----
Jira Ticket Types
----
Epic : 1
Story : 4
end legend


' Tickets =======
class "ARS-4" << (S,lightgreen) >> {
 Summary : Survey Results Page
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-48" << (S,lightgreen) >> {
 Summary : Questions Page - Scroll progress bar
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-41" << (S,lightgreen) >> {
 Summary : Questions Page - Personalised with company name
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-42" << (S,lightgreen) >> {
 Summary : Results Page - Personalised Thank you message
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-2" << (E,green) >> {
 Summary : Survey Questions Pages
 Status : To Do
 Type : Epic
Total  Points : 28
}



' Links =======
"ARS-42" <.. "ARS-4" : Polaris datapoint issue link

"ARS-2" <.. "ARS-48" : Polaris datapoint issue link

"ARS-2" <.. "ARS-41" : Polaris datapoint issue link



@enduml
