@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu May 23 13:36:26 CEST 2024

title Jira Tickets for Link Type Issue split
hide empty members

legend
Jira Ticket Status
----
To Do : 15
In Progress : 4
----
Jira Ticket Types
----
Epic : 2
Story : 17
end legend


' Tickets =======
class "ARS-5" << (S,lightgreen) >> {
 Summary : Email with Results as a pdf
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-72" << (S,lightgreen) >> {
 Summary : Implement Analytics API - results endpoints
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-3" << (S,lightgreen) >> {
 Summary : Questions Page - Dimensions Progress Bar Component
 Status : To Do
 Type : Story
 Points : 8.0
Total  Points : 8
}

class "ARS-73" << (S,lightgreen) >> {
 Summary : Implement FE API - response endpoints
 Assigned to : Nneka Tielman
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-4" << (S,lightgreen) >> {
 Summary : Survey Results Page
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-9" << (S,lightgreen) >> {
 Summary : Results Page - Personalised High-Level Roadmap Component with AI
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-91" << (S,lightgreen) >> {
 Summary : Content Modelling for Questions Page
 Status : To Do
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-8" << (S,lightgreen) >> {
 Summary : Results Page - Scoring Graphic Component
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-56" << (S,lightgreen) >> {
 Summary : Input Fields Validation
 Assigned to : Juan Solano
 Status : To Do
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-67" << (S,lightgreen) >> {
 Summary : Implement FE API - user endpoints
 Assigned to : Nneka Tielman
 Status : In Progress
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-36" << (S,lightgreen) >> {
 Summary : Landing Page - Input fields Component and Form
 Assigned to : Juan Solano
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-26" << (S,lightgreen) >> {
 Summary : Implement APIs
 Assigned to : Nneka Tielman
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-1" << (E,green) >> {
 Summary : Survey Landing Page
 Assigned to : Juan Solano
 Status : To Do
 Type : Epic
Total  Points : 11
}

class "ARS-63" << (S,lightgreen) >> {
 Summary : Implement Analytics API - user endpoints
 Assigned to : Nneka Tielman
 Status : In Progress
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-74" << (S,lightgreen) >> {
 Summary : Implement FE API - submit survey endpoint
 Status : To Do
 Type : Story
 Points : 8.0
Total  Points : 8
}

class "ARS-2" << (E,green) >> {
 Summary : Survey Questions Pages
 Status : To Do
 Type : Epic
Total  Points : 26
}

class "ARS-64" << (S,lightgreen) >> {
 Summary : Auth for Analytics API
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-75" << (S,lightgreen) >> {
 Summary : Generate pdf with spider graph
 Assigned to : PAOLO BRUNASTI
 Status : To Do
 Type : Story
 Points : 8.0
Total  Points : 8
}

class "ARS-33" << (S,lightgreen) >> {
 Summary : Questions Page - Save Survey Progress
 Status : To Do
 Type : Story
Total  Points : 0
}



' Links =======
"ARS-91" <.. "ARS-2" : Issue split

"ARS-36" <.. "ARS-1" : Issue split

"ARS-33" <.. "ARS-2" : Issue split

"ARS-56" <.. "ARS-1" : Issue split

"ARS-67" <.. "ARS-26" : Issue split

"ARS-63" <.. "ARS-26" : Issue split

"ARS-64" <.. "ARS-26" : Issue split

"ARS-5" <.. "ARS-74" : Issue split

"ARS-72" <.. "ARS-26" : Issue split

"ARS-3" <.. "ARS-2" : Issue split

"ARS-73" <.. "ARS-26" : Issue split

"ARS-9" <.. "ARS-4" : Issue split

"ARS-8" <.. "ARS-4" : Issue split

"ARS-74" <.. "ARS-26" : Issue split

"ARS-75" <.. "ARS-74" : Issue split



@enduml
