@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:03:14 CEST 2024

title Jira Tickets for Person Juan Solano
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 1
(Story) : 1
end legend


' Tickets =======
class "ENKPS-19" << (T,lightblue) >> {
  Assigned to : Juan Solano
  Status : Done
  Type : Task
}

class "ENKPS-23" << (S,lightgreen) >> {
  Assigned to : Juan Solano
  Status : In Progress
  Type : Story
}



' Links =======


@enduml
