@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:03:14 CEST 2024

title Jira Tickets for Person Nneka Tielman
hide empty members

legend
Jira Ticket Status
----
(In Review) : 1
----
Jira Ticket Types
----
(Task) : 1
end legend


' Tickets =======
class "ENKPS-22" << (T,lightblue) >> {
  Assigned to : Nneka Tielman
  Status : In Review
  Type : Task
}



' Links =======


@enduml
