@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Wed May 29 11:49:43 CEST 2024

title Jira Tickets for Link Type Polaris issue link
hide empty members

legend
Jira Ticket Status
----
Done : 7
To Do : 1
----
Jira Ticket Types
----
Epic : 1
Story : 7
end legend


' Tickets =======
class "ARS-38" << (S,lightgreen) >> {
 Summary : Generate Gitlab Pipeline
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-16" << (S,lightgreen) >> {
 Summary : Contentful Content Modeling for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-17" << (S,lightgreen) >> {
 Summary : Generate Content Types GraphQL Queries for Landing Page
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-18" << (S,lightgreen) >> {
 Summary : Create Repository
 Assigned to : PAOLO BRUNASTI
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-14" << (S,lightgreen) >> {
 Summary : Set up Contentful Account
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 2.0
Total  Points : 2
}

class "ARS-37" << (S,lightgreen) >> {
 Summary : Create Eslint modules
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-15" << (S,lightgreen) >> {
 Summary : Contentful Integration FE
 Assigned to : Juan Solano
 Status : Done
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-1" << (E,green) >> {
 Summary : Survey Landing Page
 Assigned to : Juan Solano
 Status : To Do
 Type : Epic
Total  Points : 11
}



' Links =======
"ARS-18" <.. "ARS-37" : Polaris issue link

"ARS-18" <.. "ARS-38" : Polaris issue link

"ARS-1" <.. "ARS-14" : Polaris issue link

"ARS-1" <.. "ARS-15" : Polaris issue link

"ARS-1" <.. "ARS-16" : Polaris issue link

"ARS-1" <.. "ARS-17" : Polaris issue link



@enduml
