@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:03:14 CEST 2024

title Jira Tickets for Link Type Cloners
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
(To Do) : 1
----
Jira Ticket Types
----
(Story) : 2
end legend


' Tickets =======
class "ENKPS-36" << (S,lightgreen) >> {
  Status : Done
  Type : Story
}

class "ENKPS-27" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}



' Links =======
"ENKPS-27" <.. "ENKPS-36" : Cloners


@enduml
