@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue May 14 12:25:21 CEST 2024

title Jira Tickets for Person Juan Solano
hide empty members

legend
Jira Ticket Status
----
(Done) : 6
(To Do) : 2
----
Jira Ticket Types
----
(Story) : 8
end legend


' Tickets =======
class "ARS-16" << (S,lightgreen) >> {
  Summary : Contentful Content Modeling for Landing Page
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 5.0
}

class "ARS-38" << (S,lightgreen) >> {
  Summary : Generate Gitlab Pipeline
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-17" << (S,lightgreen) >> {
  Summary : Generate Content Types GraphQL Queries
  Assigned to : Juan Solano
  Status : To Do
  Type : Story
  Points : 5.0
}

class "ARS-19" << (S,lightgreen) >> {
  Summary : Create NUXT -Vue2 project FE
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-34" << (S,lightgreen) >> {
  Summary : All Survey Pages - Create Theme
  Assigned to : Juan Solano
  Status : To Do
  Type : Story
  Points : 3.0
}

class "ARS-14" << (S,lightgreen) >> {
  Summary : Set up Contentful Account
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 2.0
}

class "ARS-15" << (S,lightgreen) >> {
  Summary : Contentful Integration FE
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}

class "ARS-37" << (S,lightgreen) >> {
  Summary : Create Eslint modules
  Assigned to : Juan Solano
  Status : Done
  Type : Story
  Points : 3.0
}



' Links =======


@enduml
