@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu May 23 13:36:26 CEST 2024

title Jira Tickets for Status In Progress
hide empty members

legend
Jira Ticket Status
----
To Do : 2
In Progress : 10
----
Jira Ticket Types
----
Subtask : 3
Epic : 3
Story : 6
end legend


' Tickets =======
class "ARS-40" << (S,lightgreen) >> {
 Summary : AWS Environment
 Assigned to : PAOLO BRUNASTI
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-73" << (S,lightgreen) >> {
 Summary : Implement FE API - response endpoints
 Assigned to : Nneka Tielman
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-104" << (S,lightblue) >> {
 Summary : Connect to EC2 from Internet
 Status : In Progress
 Type : Subtask
Total  Points : 0
}

class "ARS-67" << (S,lightgreen) >> {
 Summary : Implement FE API - user endpoints
 Assigned to : Nneka Tielman
 Status : In Progress
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-89" << (S,lightblue) >> {
 Summary : Spider Net Graphic
 Assigned to : PAOLO BRUNASTI
 Status : In Progress
 Type : Subtask
Total  Points : 0
}

class "ARS-36" << (S,lightgreen) >> {
 Summary : Landing Page - Input fields Component and Form
 Assigned to : Juan Solano
 Status : In Progress
 Type : Story
 Points : 5.0
Total  Points : 5
}

class "ARS-26" << (S,lightgreen) >> {
 Summary : Implement APIs
 Assigned to : Nneka Tielman
 Status : To Do
 Type : Story
Total  Points : 0
}

class "ARS-1" << (E,green) >> {
 Summary : Survey Landing Page
 Assigned to : Juan Solano
 Status : To Do
 Type : Epic
Total  Points : 11
}

class "ARS-63" << (S,lightgreen) >> {
 Summary : Implement Analytics API - user endpoints
 Assigned to : Nneka Tielman
 Status : In Progress
 Type : Story
 Points : 3.0
Total  Points : 3
}

class "ARS-20" << (E,green) >> {
 Summary : Back End for Survey
 Assigned to : PAOLO BRUNASTI
 Status : In Progress
 Type : Epic
Total  Points : 71
}

class "ARS-32" << (E,green) >> {
 Summary : Infrastructure
 Assigned to : PAOLO BRUNASTI
 Status : In Progress
 Type : Epic
Total  Points : 24
}

class "ARS-99" << (S,lightblue) >> {
 Summary : Deploy BE app in EC2
 Status : In Progress
 Type : Subtask
Total  Points : 0
}



' Links =======
"ARS-36" <.. "ARS-1" : Issue split
"ARS-67" <.. "ARS-26" : Issue split
"ARS-63" <.. "ARS-26" : Issue split
"ARS-73" <.. "ARS-26" : Issue split


@enduml
