@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 11:44:38 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 2
----
Jira Ticket Types
----
(Task) : 2
end legend


' Tickets =======
class "CNG-989" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}

class "CNG-990" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}



' Links =======
"CNG-989" <.. "CNG-990" : Cloners


@enduml
