@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 15:11:08 CEST 2024

title Jira Tickets for Status Accepted
hide empty members

legend
Jira Ticket Status
----
(Accepted) : 1
----
Jira Ticket Types
----
(Project Request Package) : 1
end legend


' Tickets =======
class "CNG-895" << (P,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Accepted
  Type : Project Request Package
}



' Links =======


@enduml
