@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 19 14:50:29 CEST 2024

title Jira Tickets for Person Dileep
hide empty members

legend
Jira Ticket Status
----
(Done) : 8
(To Do) : 5
(In Progress) : 7
----
Jira Ticket Types
----
(Task) : 19
(Issue) : 1
end legend


' Tickets =======
class "CNG-1262" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1263" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1395" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-1271" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1360" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-1181" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1408" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-1229" << (I,orange) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Issue
}

class "CNG-1237" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1259" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1249" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1257" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1258" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1245" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-1300" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-1286" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-1264" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1253" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1385" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-1254" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}



' Links =======
"CNG-1286" <.. "CNG-1254" : Dependent
"CNG-1262" <.. "CNG-1254" : Dependent
"CNG-1263" <.. "CNG-1254" : Dependent
"CNG-1263" <.. "CNG-1264" : Dependent
"CNG-1249" <.. "CNG-1245" : Dependent
"CNG-1245" <.. "CNG-1237" : Dependent
"CNG-1259" <.. "CNG-1254" : Dependent
"CNG-1257" <.. "CNG-1254" : Dependent
"CNG-1258" <.. "CNG-1254" : Dependent
"CNG-1254" <.. "CNG-1253" : Dependent
"CNG-1254" <.. "CNG-1271" : Dependent
"CNG-1385" <.. "CNG-1395" : Cloners


@enduml
