@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 14:59:13 CEST 2024

title Jira Tickets for Person Dilip Kandamuthu
hide empty members

legend
Jira Ticket Status
----
(Work Complete) : 5
----
Jira Ticket Types
----
(Bug) : 5
end legend


' Tickets =======
class "CNG-1393" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Status : Work Complete
  Type : Bug
}

class "CNG-1358" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Status : Work Complete
  Type : Bug
}

class "CNG-1345" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Status : Work Complete
  Type : Bug
}

class "CNG-1365" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Status : Work Complete
  Type : Bug
}

class "CNG-1364" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Status : Work Complete
  Type : Bug
}



' Links =======


@enduml
