@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 11:50:48 CEST 2024

title Jira Tickets for Person Pooja Ravi
hide empty members

legend
Jira Ticket Status
----
(Withdrawn) : 2
(Raised) : 1
----
Jira Ticket Types
----
(Bug) : 3
end legend


' Tickets =======
class "CNG-515" << (B,red) >> {
  Assigned to : Pooja Ravi
  Status : Withdrawn
  Type : Bug
}

class "CNG-442" << (B,red) >> {
  Assigned to : Pooja Ravi
  Status : Withdrawn
  Type : Bug
}

class "CNG-854" << (B,red) >> {
  Assigned to : Pooja Ravi
  Status : Raised
  Type : Bug
}



' Links =======


@enduml
