@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 14:59:13 CEST 2024

title Jira Tickets for Person Sushant Khandelwal
hide empty members

legend
Jira Ticket Status
----
(QA) : 2
(Done) : 27
(To Do) : 8
(Dev Review) : 3
(In Work) : 1
(Withdrawn) : 2
(In Progress) : 6
(Work Complete) : 4
(Resolved (Closed)) : 2
(Raised) : 1
(Design Review) : 1
----
Jira Ticket Types
----
(Risks) : 1
(Task) : 22
(Bug) : 8
(Sub-task) : 21
(Impediment (Issue)) : 2
(New Feature) : 3
end legend


' Tickets =======
class "CNG-583" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : Done
  Type : Sub-task
}

class "CNG-537" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : Withdrawn
  Type : Bug
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-418" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Work Complete
  Type : Bug
}

class "CNG-938" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Work Complete
  Type : Bug
}

class "CNG-772" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Work Complete
  Type : Bug
}

class "CNG-695" << (I,orange) >> {
  Assigned to : Sushant Khandelwal
  Status : Resolved (Closed)
  Type : Impediment (Issue)
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-610" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-1044" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-657" << (I,orange) >> {
  Assigned to : Shafiqul Islam
  Status : Resolved (Closed)
  Type : Impediment (Issue)
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-628" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-627" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-949" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-948" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-629" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Task
}

class "CNG-585" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Sub-task
}

class "CNG-1336" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-661" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Sub-task
}

class "CNG-543" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-983" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Withdrawn
  Type : Bug
}

class "CNG-1015" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-620" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Task
}

class "CNG-544" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-984" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1011" << (R,red) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Risks
}

class "CNG-943" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-546" << (N,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : New Feature
}

class "CNG-1021" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-837" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-638" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-992" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Work Complete
  Type : Bug
}

class "CNG-673" << (S,lightblue) >> {
  Status : Done
  Type : Sub-task
}

class "CNG-794" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-595" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-598" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-674" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : Done
  Type : Sub-task
}

class "CNG-630" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-677" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-875" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-756" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-558" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1220" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1394" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Raised
  Type : Bug
}

class "CNG-527" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-528" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-640" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-562" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-523" << (N,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : New Feature
}

class "CNG-600" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-522" << (N,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : Done
  Type : New Feature
}



' Links =======
"CNG-772" <.. "CNG-686" : Relates
"CNG-992" <.. "CNG-585" : Relates
"CNG-756" <.. "CNG-548" : Dependent
"CNG-527" <.. "CNG-673" : Dependent
"CNG-527" <.. "CNG-533" : Dependent
"CNG-528" <.. "CNG-674" : Dependent
"CNG-528" <.. "CNG-533" : Dependent
"CNG-528" <.. "CNG-685" : Relates
"CNG-523" <.. "CNG-522" : Relates
"CNG-523" <.. "CNG-546" : Relates
"CNG-523" <.. "CNG-684" : Relates
"CNG-523" <.. "CNG-630" : Relates
"CNG-794" <.. "CNG-583" : Dependent
"CNG-938" <.. "CNG-585" : Relates
"CNG-938" <.. "CNG-558" : Relates
"CNG-948" <.. "CNG-949" : Dependent
"CNG-1044" <.. "CNG-557" : Dependent
"CNG-1021" <.. "CNG-610" : Relates
"CNG-1015" <.. "CNG-814" : Relates
"CNG-1011" <.. "CNG-984" : Relates
"CNG-638" <.. "CNG-583" : Dependent
"CNG-677" <.. "CNG-875" : Relates
"CNG-620" <.. "CNG-657" : Blocks
"CNG-620" <.. "CNG-537" : Blocks
"CNG-620" <.. "CNG-604" : Dependent
"CNG-837" <.. "CNG-583" : Dependent
"CNG-837" <.. "CNG-794" : Dependent
"CNG-837" <.. "CNG-638" : Dependent
"CNG-837" <.. "CNG-943" : Dependent


@enduml
