@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 13:08:16 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 16
(Dev Review) : 1
(Build) : 1
(UAT) : 1
(In Progress) : 9
(Design Review) : 1
----
Jira Ticket Types
----
(Task) : 15
(Sub-task) : 10
(Story) : 4
end legend


' Tickets =======
class "CNG-736" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-738" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-596" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-257" << (S,lightgreen) >> {
  Assigned to : Tony Cassidy
  Status : UAT
  Type : Story
}

class "CNG-531" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-732" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-798" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-734" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-592" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-594" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-593" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-84" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-626" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-707" << (S,lightgreen) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Story
}

class "CNG-709" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-564" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-688" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-644" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Build
  Type : Sub-task
}

class "CNG-401" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-525" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-800" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-624" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-723" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-700" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}



' Links =======
"CNG-533" <.. "CNG-732" : Dependent
"CNG-533" <.. "CNG-732" : Dependent
"CNG-533" <.. "CNG-688" : Relates
"CNG-533" <.. "CNG-732" : Dependent
"CNG-533" <.. "CNG-688" : Relates
"CNG-644" <.. "CNG-393" : Dependent
"CNG-644" <.. "CNG-393" : Dependent
"CNG-644" <.. "CNG-393" : Dependent
"CNG-592" <.. "CNG-257" : Relates
"CNG-592" <.. "CNG-84" : Relates
"CNG-707" <.. "CNG-393" : Dependent
"CNG-707" <.. "CNG-700" : Relates
"CNG-707" <.. "CNG-393" : Dependent
"CNG-707" <.. "CNG-1203" : Feature
"CNG-707" <.. "CNG-393" : Dependent
"CNG-707" <.. "CNG-1203" : Feature
"CNG-800" <.. "CNG-548" : Relates
"CNG-800" <.. "CNG-548" : Relates
"CNG-738" <.. "CNG-604" : Relates
"CNG-624" <.. "CNG-626" : Automates
"CNG-624" <.. "CNG-531" : Dependent
"CNG-624" <.. "CNG-531" : Dependent
"CNG-624" <.. "CNG-531" : Dependent
"CNG-604" <.. "CNG-738" : Relates
"CNG-604" <.. "CNG-723" : Relates
"CNG-604" <.. "CNG-738" : Relates
"CNG-604" <.. "CNG-723" : Relates


@enduml
