@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:59 CEST 2024

title Jira Tickets for Person Naveen Kumar S
hide empty members

legend
Jira Ticket Status
----
(Work Complete) : 3
----
Jira Ticket Types
----
(Bug) : 3
end legend


' Tickets =======
class "CNG-1350" << (B,red) >> {
  Assigned to : Naveen Kumar S
  Summary : CNG-SOLR API-System test -overallCabin: 'M' only is not returned by default in solr response,when overallCabin is not specified in solr request.
  Status : Work Complete
  Type : Bug
}

class "CNG-1335" << (B,red) >> {
  Assigned to : Naveen Kumar S
  Summary : CNG-SOLR API-System test - Invariant related issues in bahpricefeed handler for FC,HO and CO propositions
  Status : Work Complete
  Type : Bug
}

class "CNG-1355" << (B,red) >> {
  Assigned to : Naveen Kumar S
  Summary : CNG - SOLR API - System Test - Date/YEAR is not working for all propositions
  Status : Work Complete
  Type : Bug
}



' Links =======


@enduml
