@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 19 14:50:28 CEST 2024

title Jira Tickets for Link Type Relates
hide empty members

legend
Jira Ticket Status
----
(IN UAT) : 6
(In Review (migrated)) : 3
(To Do) : 74
(Done) : 159
(Dev Review) : 1
(Under Investigation) : 2
(UAT) : 3
(In Progress) : 41
(In System Test) : 4
(Work Complete) : 40
(Raised) : 5
(QA) : 5
(Withdrawn) : 2
(Design Review) : 3
----
Jira Ticket Types
----
(Risks) : 7
(Task) : 214
(Improvement) : 1
(Issue) : 2
(Bug) : 59
(Sub-task) : 58
(Story) : 3
(New Feature) : 4
end legend


' Tickets =======
class "CNG-1208" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1329" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1204" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Done
  Type : Task
}

class "CNG-772" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Work Complete
  Type : Bug
}

class "CNG-651" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-893" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : Done
  Type : Task
}

class "CNG-892" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1326" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-650" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-774" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-894" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-776" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1200" << (T,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : Done
  Type : Task
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-896" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-654" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : In System Test
  Type : Bug
}

class "CNG-536" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-899" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-415" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-777" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-428" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Story
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-1219" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Done
  Type : Task
}

class "CNG-785" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-542" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-421" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Status : Work Complete
  Type : Bug
}

class "CNG-1332" << (B,red) >> {
  Assigned to : Aswathi Ullattil
  Status : Work Complete
  Type : Bug
}

class "CNG-665" << (S,lightblue) >> {
  Status : Done
  Type : Sub-task
}

class "CNG-1330" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-546" << (N,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : New Feature
}

class "CNG-1331" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-667" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-758" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-879" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-636" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : Done
  Type : Task
}

class "CNG-999" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-878" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Status : Work Complete
  Type : Bug
}

class "CNG-518" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : UAT
  Type : Task
}

class "CNG-639" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-1305" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-992" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Work Complete
  Type : Bug
}

class "CNG-870" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1301" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-994" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-993" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Risks
}

class "CNG-751" << (S,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Sub-task
}

class "CNG-630" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-512" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-996" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-875" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1300" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-995" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-635" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-997" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-876" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-770" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-891" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-890" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Work Complete
  Type : Bug
}

class "CNG-769" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-768" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-529" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-528" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-1318" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1316" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1317" << (T,lightblue) >> {
  Assigned to : Mahima Verma
  Status : Done
  Type : Task
}

class "CNG-882" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-1315" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-881" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-521" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-883" << (T,lightblue) >> {
  Assigned to : Ketaki Baisani
  Status : Done
  Type : Task
}

class "CNG-641" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-523" << (N,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : New Feature
}

class "CNG-765" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : In Progress
  Type : Sub-task
}

class "CNG-522" << (N,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : Done
  Type : New Feature
}

class "CNG-767" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-646" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-524" << (N,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : Done
  Type : New Feature
}

class "CNG-887" << (B,red) >> {
  Assigned to : Riti Agarwal
  Status : Under Investigation
  Type : Bug
}

class "CNG-460" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-581" << (S,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : Done
  Type : Sub-task
}

class "CNG-1407" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-694" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-697" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-696" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-699" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-457" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Withdrawn
  Type : Bug
}

class "CNG-698" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-459" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-458" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-1097" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1095" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1096" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1094" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-591" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-908" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-901" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-903" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-902" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-907" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-906" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-585" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Sub-task
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-467" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Work Complete
  Type : Bug
}

class "CNG-1099" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1185" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1183" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1060" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1181" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-680" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1061" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Improvement
}

class "CNG-1182" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-440" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-682" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-561" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-560" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-681" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : In Progress
  Type : Sub-task
}

class "CNG-795" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-677" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-1068" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1189" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1069" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-558" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-679" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-437" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-1187" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-678" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Sub-task
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1067" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-436" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-1075" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1197" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : Done
  Type : Task
}

class "CNG-1073" << (S,lightblue) >> {
  Assigned to : Surya Prakash Bhallamudi
  Status : Done
  Type : Sub-task
}

class "CNG-1074" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Sub-task
}

class "CNG-1071" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-691" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-1072" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1193" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Task
}

class "CNG-1190" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-693" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-1070" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-692" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-562" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-441" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : Done
  Type : Task
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-444" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-688" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-1042" << (S,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1282" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1281" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-813" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-934" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-933" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-936" << (B,red) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Work Complete
  Type : Bug
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-938" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Work Complete
  Type : Bug
}

class "CNG-1167" << (T,lightblue) >> {
  Assigned to : Hamida Rehman
  Status : Done
  Type : Task
}

class "CNG-1289" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1168" << (T,lightblue) >> {
  Assigned to : Hamida Rehman
  Status : Done
  Type : Task
}

class "CNG-1165" << (T,lightblue) >> {
  Assigned to : Hamida Rehman
  Status : Done
  Type : Task
}

class "CNG-1166" << (T,lightblue) >> {
  Assigned to : Hamida Rehman
  Status : Done
  Type : Task
}

class "CNG-931" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1174" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1296" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1175" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1172" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1051" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Sub-task
}

class "CNG-945" << (B,red) >> {
  Assigned to : Rajeswari Vijayal Neelakantan
  Status : Work Complete
  Type : Bug
}

class "CNG-703" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-702" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-705" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-704" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-948" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-708" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-1299" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1179" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-822" << (T,lightblue) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : Done
  Type : Task
}

class "CNG-1176" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-701" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-821" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-700" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1141" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-1021" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Sub-task
}

class "CNG-1142" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : To Do
  Type : Task
}

class "CNG-1382" << (T,lightblue) >> {
  Assigned to : Philip Adams
  Status : To Do
  Type : Task
}

class "CNG-1140" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-483" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-919" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-911" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-915" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-918" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1028" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Sub-task
}

class "CNG-1149" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1029" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1147" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1148" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1145" << (T,lightblue) >> {
  Assigned to : Surya Prakash Bhallamudi
  Status : Done
  Type : Task
}

class "CNG-479" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-1024" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-599" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-1143" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-1023" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Task
}

class "CNG-1386" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Under Investigation
  Type : Bug
}

class "CNG-1144" << (T,lightblue) >> {
  Assigned to : Hamida Rehman
  Status : Done
  Type : Task
}

class "CNG-1273" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Design Review
  Type : Task
}

class "CNG-1152" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1153" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1274" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1150" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-491" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : Done
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1030" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-494" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-804" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Sub-task
}

class "CNG-806" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-927" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1039" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-485" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1279" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1159" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1035" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-1156" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-921" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-1154" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1275" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-800" << (S,lightblue) >> {
  Status : Done
  Type : Sub-task
}

class "CNG-1033" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-920" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1361" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1120" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-738" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-617" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Task
}

class "CNG-619" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : Done
  Type : Task
}

class "CNG-739" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1008" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1129" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1009" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-970" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Status : Work Complete
  Type : Bug
}

class "CNG-1248" << (B,red) >> {
  Assigned to : Narayana Golla
  Status : Work Complete
  Type : Bug
}

class "CNG-1006" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1127" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1007" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1128" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1004" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : In Progress
  Type : Risks
}

class "CNG-1125" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-971" << (T,lightblue) >> {
  Assigned to : Rosy Mary
  Status : Done
  Type : Task
}

class "CNG-1005" << (T,lightblue) >> {
  Assigned to : Poornima Sajeendran
  Status : Design Review
  Type : Task
}

class "CNG-850" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1126" << (T,lightblue) >> {
  Assigned to : Sam Miles
  Status : Done
  Type : Task
}

class "CNG-611" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Sub-task
}

class "CNG-610" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-852" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Raised
  Type : Bug
}

class "CNG-1124" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-855" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-1363" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1121" << (T,lightblue) >> {
  Assigned to : Surya Prakash Bhallamudi
  Status : Done
  Type : Task
}

class "CNG-1000" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-613" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : Done
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-975" << (T,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Task
}

class "CNG-612" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : Done
  Type : Sub-task
}

class "CNG-1122" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1131" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1010" << (I,orange) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Issue
}

class "CNG-505" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : Done
  Type : Task
}

class "CNG-868" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-506" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-508" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1019" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-860" << (B,red) >> {
  Assigned to : Dhanish Kumar
  Status : Work Complete
  Type : Bug
}

class "CNG-981" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1017" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1139" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : In Progress
  Type : Task
}

class "CNG-983" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Withdrawn
  Type : Bug
}

class "CNG-1015" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-862" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-1378" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1016" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1379" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-740" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-861" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Status : Work Complete
  Type : Bug
}

class "CNG-1013" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-985" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-622" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Task
}

class "CNG-984" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-863" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : Work Complete
  Type : Bug
}

class "CNG-1011" << (R,red) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Risks
}

class "CNG-865" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : Done
  Type : Task
}

class "CNG-1012" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-623" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Sub-task
}

class "CNG-834" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-958" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1109" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-838" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-959" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1107" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Design Review
  Type : Task
}

class "CNG-1228" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : Done
  Type : Sub-task
}

class "CNG-1229" << (I,orange) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Issue
}

class "CNG-1108" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1105" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1227" << (S,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Done
  Type : Sub-task
}

class "CNG-1106" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1103" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1225" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-1104" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-710" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1222" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1223" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-1102" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-833" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-953" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-711" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-1221" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1100" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1230" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-966" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : Work Complete
  Type : Bug
}

class "CNG-603" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : Done
  Type : Task
}

class "CNG-969" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Status : Work Complete
  Type : Bug
}

class "CNG-606" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-605" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Task
}

class "CNG-608" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1118" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1119" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-609" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-1116" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1117" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Done
  Type : Task
}

class "CNG-1114" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1235" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-961" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-1115" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1236" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-960" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-963" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : Work Complete
  Type : Bug
}

class "CNG-1112" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1113" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-962" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-723" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-844" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1110" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-964" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-601" << (T,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Done
  Type : Task
}

class "CNG-1111" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}



' Links =======
"CNG-1208" <.. "CNG-710" : Relates
"CNG-1204" <.. "CNG-733" : Relates
"CNG-772" <.. "CNG-686" : Relates
"CNG-1205" <.. "CNG-685" : Relates
"CNG-774" <.. "CNG-678" : Relates
"CNG-774" <.. "CNG-677" : Relates
"CNG-533" <.. "CNG-688" : Relates
"CNG-536" <.. "CNG-684" : Relates
"CNG-536" <.. "CNG-777" : Relates
"CNG-542" <.. "CNG-855" : Relates
"CNG-542" <.. "CNG-860" : Relates
"CNG-546" <.. "CNG-685" : Relates
"CNG-518" <.. "CNG-684" : Relates
"CNG-518" <.. "CNG-739" : Relates
"CNG-992" <.. "CNG-585" : Relates
"CNG-993" <.. "CNG-1008" : Relates
"CNG-751" <.. "CNG-758" : Relates
"CNG-512" <.. "CNG-686" : Relates
"CNG-770" <.. "CNG-635" : Relates
"CNG-769" <.. "CNG-635" : Relates
"CNG-768" <.. "CNG-636" : Relates
"CNG-529" <.. "CNG-733" : Relates
"CNG-528" <.. "CNG-685" : Relates
"CNG-521" <.. "CNG-687" : Relates
"CNG-523" <.. "CNG-522" : Relates
"CNG-523" <.. "CNG-546" : Relates
"CNG-523" <.. "CNG-684" : Relates
"CNG-523" <.. "CNG-630" : Relates
"CNG-522" <.. "CNG-684" : Relates
"CNG-522" <.. "CNG-1153" : Relates
"CNG-524" <.. "CNG-684" : Relates
"CNG-1407" <.. "CNG-873" : Relates
"CNG-1407" <.. "CNG-1282" : Relates
"CNG-1407" <.. "CNG-1296" : Relates
"CNG-589" <.. "CNG-1363" : Relates
"CNG-560" <.. "CNG-908" : Relates
"CNG-795" <.. "CNG-892" : Relates
"CNG-558" <.. "CNG-1332" : Relates
"CNG-936" <.. "CNG-585" : Relates
"CNG-938" <.. "CNG-585" : Relates
"CNG-938" <.. "CNG-558" : Relates
"CNG-945" <.. "CNG-585" : Relates
"CNG-919" <.. "CNG-708" : Relates
"CNG-915" <.. "CNG-585" : Relates
"CNG-918" <.. "CNG-708" : Relates
"CNG-921" <.. "CNG-708" : Relates
"CNG-920" <.. "CNG-708" : Relates
"CNG-970" <.. "CNG-585" : Relates
"CNG-733" <.. "CNG-776" : Relates
"CNG-733" <.. "CNG-1060" : Relates
"CNG-733" <.. "CNG-1154" : Relates
"CNG-733" <.. "CNG-651" : Relates
"CNG-733" <.. "CNG-506" : Relates
"CNG-733" <.. "CNG-1281" : Relates
"CNG-733" <.. "CNG-1299" : Relates
"CNG-733" <.. "CNG-1300" : Relates
"CNG-733" <.. "CNG-1301" : Relates
"CNG-733" <.. "CNG-1330" : Relates
"CNG-733" <.. "CNG-1331" : Relates
"CNG-733" <.. "CNG-1329" : Relates
"CNG-508" <.. "CNG-733" : Relates
"CNG-981" <.. "CNG-795" : Relates
"CNG-984" <.. "CNG-983" : Relates
"CNG-984" <.. "CNG-993" : Relates
"CNG-984" <.. "CNG-994" : Relates
"CNG-984" <.. "CNG-995" : Relates
"CNG-984" <.. "CNG-996" : Relates
"CNG-984" <.. "CNG-997" : Relates
"CNG-984" <.. "CNG-1004" : Relates
"CNG-710" <.. "CNG-975" : Relates
"CNG-710" <.. "CNG-865" : Relates
"CNG-710" <.. "CNG-971" : Relates
"CNG-953" <.. "CNG-795" : Relates
"CNG-711" <.. "CNG-651" : Relates
"CNG-969" <.. "CNG-585" : Relates
"CNG-963" <.. "CNG-585" : Relates
"CNG-964" <.. "CNG-795" : Relates
"CNG-1097" <.. "CNG-1028" : Relates
"CNG-1095" <.. "CNG-1028" : Relates
"CNG-1096" <.. "CNG-1028" : Relates
"CNG-1094" <.. "CNG-1028" : Relates
"CNG-1099" <.. "CNG-1028" : Relates
"CNG-1075" <.. "CNG-733" : Relates
"CNG-1289" <.. "CNG-557" : Relates
"CNG-1289" <.. "CNG-806" : Relates
"CNG-1289" <.. "CNG-813" : Relates
"CNG-1289" <.. "CNG-821" : Relates
"CNG-1289" <.. "CNG-822" : Relates
"CNG-1289" <.. "CNG-919" : Relates
"CNG-1289" <.. "CNG-927" : Relates
"CNG-1289" <.. "CNG-883" : Relates
"CNG-1289" <.. "CNG-896" : Relates
"CNG-1289" <.. "CNG-891" : Relates
"CNG-1289" <.. "CNG-882" : Relates
"CNG-1289" <.. "CNG-948" : Relates
"CNG-1289" <.. "CNG-1016" : Relates
"CNG-1289" <.. "CNG-983" : Relates
"CNG-1289" <.. "CNG-1113" : Relates
"CNG-1289" <.. "CNG-1114" : Relates
"CNG-1289" <.. "CNG-1115" : Relates
"CNG-1289" <.. "CNG-1116" : Relates
"CNG-1289" <.. "CNG-1118" : Relates
"CNG-1289" <.. "CNG-1119" : Relates
"CNG-1289" <.. "CNG-1120" : Relates
"CNG-1289" <.. "CNG-1131" : Relates
"CNG-1289" <.. "CNG-1073" : Relates
"CNG-1289" <.. "CNG-1121" : Relates
"CNG-1289" <.. "CNG-1129" : Relates
"CNG-1289" <.. "CNG-1145" : Relates
"CNG-1289" <.. "CNG-1148" : Relates
"CNG-1289" <.. "CNG-1149" : Relates
"CNG-1289" <.. "CNG-1167" : Relates
"CNG-1289" <.. "CNG-1168" : Relates
"CNG-1021" <.. "CNG-610" : Relates
"CNG-1023" <.. "CNG-1094" : Relates
"CNG-1279" <.. "CNG-733" : Relates
"CNG-1009" <.. "CNG-907" : Relates
"CNG-1009" <.. "CNG-899" : Relates
"CNG-1248" <.. "CNG-1205" : Relates
"CNG-1010" <.. "CNG-984" : Relates
"CNG-1017" <.. "CNG-700" : Relates
"CNG-1015" <.. "CNG-814" : Relates
"CNG-1013" <.. "CNG-558" : Relates
"CNG-1011" <.. "CNG-984" : Relates
"CNG-1012" <.. "CNG-558" : Relates
"CNG-1222" <.. "CNG-873" : Relates
"CNG-1223" <.. "CNG-999" : Relates
"CNG-1221" <.. "CNG-873" : Relates
"CNG-1235" <.. "CNG-873" : Relates
"CNG-1235" <.. "CNG-1185" : Relates
"CNG-1236" <.. "CNG-733" : Relates
"CNG-1236" <.. "CNG-1181" : Relates
"CNG-1236" <.. "CNG-1176" : Relates
"CNG-1236" <.. "CNG-833" : Relates
"CNG-1236" <.. "CNG-699" : Relates
"CNG-1236" <.. "CNG-985" : Relates
"CNG-1236" <.. "CNG-774" : Relates
"CNG-1236" <.. "CNG-894" : Relates
"CNG-1236" <.. "CNG-903" : Relates
"CNG-1236" <.. "CNG-635" : Relates
"CNG-1236" <.. "CNG-901" : Relates
"CNG-1236" <.. "CNG-1006" : Relates
"CNG-1236" <.. "CNG-1072" : Relates
"CNG-1236" <.. "CNG-1071" : Relates
"CNG-1236" <.. "CNG-1070" : Relates
"CNG-1236" <.. "CNG-1069" : Relates
"CNG-1236" <.. "CNG-1068" : Relates
"CNG-1236" <.. "CNG-1067" : Relates
"CNG-1236" <.. "CNG-767" : Relates
"CNG-1236" <.. "CNG-1061" : Relates
"CNG-1236" <.. "CNG-1200" : Relates
"CNG-1236" <.. "CNG-1227" : Relates
"CNG-1236" <.. "CNG-1219" : Relates
"CNG-1236" <.. "CNG-562" : Relates
"CNG-893" <.. "CNG-1000" : Relates
"CNG-896" <.. "CNG-879" : Relates
"CNG-654" <.. "CNG-536" : Relates
"CNG-415" <.. "CNG-441" : Relates
"CNG-415" <.. "CNG-440" : Relates
"CNG-667" <.. "CNG-1007" : Relates
"CNG-878" <.. "CNG-708" : Relates
"CNG-870" <.. "CNG-733" : Relates
"CNG-873" <.. "CNG-1107" : Relates
"CNG-873" <.. "CNG-1204" : Relates
"CNG-873" <.. "CNG-961" : Relates
"CNG-873" <.. "CNG-710" : Relates
"CNG-873" <.. "CNG-1230" : Relates
"CNG-873" <.. "CNG-557" : Relates
"CNG-873" <.. "CNG-1273" : Relates
"CNG-873" <.. "CNG-1274" : Relates
"CNG-873" <.. "CNG-1275" : Relates
"CNG-873" <.. "CNG-1305" : Relates
"CNG-873" <.. "CNG-1315" : Relates
"CNG-873" <.. "CNG-1229" : Relates
"CNG-873" <.. "CNG-1379" : Relates
"CNG-891" <.. "CNG-881" : Relates
"CNG-891" <.. "CNG-558" : Relates
"CNG-890" <.. "CNG-881" : Relates
"CNG-890" <.. "CNG-558" : Relates
"CNG-1318" <.. "CNG-684" : Relates
"CNG-1316" <.. "CNG-733" : Relates
"CNG-1317" <.. "CNG-684" : Relates
"CNG-882" <.. "CNG-879" : Relates
"CNG-882" <.. "CNG-876" : Relates
"CNG-881" <.. "CNG-708" : Relates
"CNG-646" <.. "CNG-687" : Relates
"CNG-887" <.. "CNG-687" : Relates
"CNG-694" <.. "CNG-558" : Relates
"CNG-696" <.. "CNG-697" : Relates
"CNG-696" <.. "CNG-630" : Relates
"CNG-696" <.. "CNG-740" : Relates
"CNG-457" <.. "CNG-485" : Relates
"CNG-698" <.. "CNG-696" : Relates
"CNG-459" <.. "CNG-483" : Relates
"CNG-458" <.. "CNG-485" : Relates
"CNG-467" <.. "CNG-483" : Relates
"CNG-680" <.. "CNG-1197" : Relates
"CNG-682" <.. "CNG-1005" : Relates
"CNG-681" <.. "CNG-494" : Relates
"CNG-677" <.. "CNG-875" : Relates
"CNG-679" <.. "CNG-893" : Relates
"CNG-679" <.. "CNG-852" : Relates
"CNG-679" <.. "CNG-834" : Relates
"CNG-679" <.. "CNG-1190" : Relates
"CNG-679" <.. "CNG-1035" : Relates
"CNG-679" <.. "CNG-1326" : Relates
"CNG-437" <.. "CNG-436" : Relates
"CNG-691" <.. "CNG-558" : Relates
"CNG-693" <.. "CNG-558" : Relates
"CNG-692" <.. "CNG-558" : Relates
"CNG-684" <.. "CNG-966" : Relates
"CNG-684" <.. "CNG-999" : Relates
"CNG-686" <.. "CNG-665" : Relates
"CNG-686" <.. "CNG-1193" : Relates
"CNG-686" <.. "CNG-999" : Relates
"CNG-685" <.. "CNG-505" : Relates
"CNG-685" <.. "CNG-665" : Relates
"CNG-685" <.. "CNG-1225" : Relates
"CNG-685" <.. "CNG-1151" : Relates
"CNG-685" <.. "CNG-1228" : Relates
"CNG-687" <.. "CNG-536" : Relates
"CNG-813" <.. "CNG-561" : Relates
"CNG-800" <.. "CNG-548" : Relates
"CNG-850" <.. "CNG-696" : Relates
"CNG-611" <.. "CNG-686" : Relates
"CNG-610" <.. "CNG-686" : Relates
"CNG-855" <.. "CNG-558" : Relates
"CNG-855" <.. "CNG-860" : Relates
"CNG-613" <.. "CNG-524" : Relates
"CNG-612" <.. "CNG-686" : Relates
"CNG-868" <.. "CNG-700" : Relates
"CNG-862" <.. "CNG-558" : Relates
"CNG-861" <.. "CNG-558" : Relates
"CNG-863" <.. "CNG-558" : Relates
"CNG-623" <.. "CNG-687" : Relates
"CNG-838" <.. "CNG-558" : Relates
"CNG-604" <.. "CNG-678" : Relates
"CNG-604" <.. "CNG-738" : Relates
"CNG-604" <.. "CNG-723" : Relates
"CNG-606" <.. "CNG-687" : Relates
"CNG-609" <.. "CNG-686" : Relates
"CNG-844" <.. "CNG-696" : Relates
"CNG-908" <.. "CNG-428" : Relates
"CNG-908" <.. "CNG-785" : Relates
"CNG-901" <.. "CNG-524" : Relates
"CNG-901" <.. "CNG-613" : Relates
"CNG-902" <.. "CNG-733" : Relates
"CNG-906" <.. "CNG-733" : Relates
"CNG-1183" <.. "CNG-733" : Relates
"CNG-1182" <.. "CNG-733" : Relates
"CNG-1189" <.. "CNG-733" : Relates
"CNG-1187" <.. "CNG-560" : Relates
"CNG-1167" <.. "CNG-1030" : Relates
"CNG-1168" <.. "CNG-1030" : Relates
"CNG-1165" <.. "CNG-1028" : Relates
"CNG-1166" <.. "CNG-1028" : Relates
"CNG-1174" <.. "CNG-765" : Relates
"CNG-1174" <.. "CNG-804" : Relates
"CNG-1175" <.. "CNG-733" : Relates
"CNG-1172" <.. "CNG-765" : Relates
"CNG-1172" <.. "CNG-804" : Relates
"CNG-1179" <.. "CNG-733" : Relates
"CNG-1141" <.. "CNG-1039" : Relates
"CNG-1142" <.. "CNG-1039" : Relates
"CNG-1382" <.. "CNG-1221" : Relates
"CNG-1140" <.. "CNG-1039" : Relates
"CNG-1149" <.. "CNG-1030" : Relates
"CNG-1147" <.. "CNG-1028" : Relates
"CNG-1148" <.. "CNG-1030" : Relates
"CNG-1145" <.. "CNG-1030" : Relates
"CNG-479" <.. "CNG-460" : Relates
"CNG-1143" <.. "CNG-1127" : Relates
"CNG-1386" <.. "CNG-873" : Relates
"CNG-1144" <.. "CNG-1028" : Relates
"CNG-1152" <.. "CNG-1030" : Relates
"CNG-1153" <.. "CNG-686" : Relates
"CNG-1150" <.. "CNG-1030" : Relates
"CNG-491" <.. "CNG-723" : Relates
"CNG-1151" <.. "CNG-1030" : Relates
"CNG-485" <.. "CNG-421" : Relates
"CNG-485" <.. "CNG-444" : Relates
"CNG-1159" <.. "CNG-630" : Relates
"CNG-1156" <.. "CNG-733" : Relates
"CNG-1361" <.. "CNG-590" : Relates
"CNG-1361" <.. "CNG-1019" : Relates
"CNG-1361" <.. "CNG-959" : Relates
"CNG-1361" <.. "CNG-622" : Relates
"CNG-1361" <.. "CNG-619" : Relates
"CNG-1361" <.. "CNG-603" : Relates
"CNG-1361" <.. "CNG-581" : Relates
"CNG-1361" <.. "CNG-599" : Relates
"CNG-1120" <.. "CNG-1033" : Relates
"CNG-1127" <.. "CNG-1024" : Relates
"CNG-1128" <.. "CNG-1028" : Relates
"CNG-1125" <.. "CNG-1074" : Relates
"CNG-1126" <.. "CNG-1024" : Relates
"CNG-1124" <.. "CNG-1074" : Relates
"CNG-1363" <.. "CNG-601" : Relates
"CNG-1363" <.. "CNG-599" : Relates
"CNG-1363" <.. "CNG-581" : Relates
"CNG-1363" <.. "CNG-617" : Relates
"CNG-1363" <.. "CNG-639" : Relates
"CNG-1363" <.. "CNG-911" : Relates
"CNG-1363" <.. "CNG-958" : Relates
"CNG-1363" <.. "CNG-931" : Relates
"CNG-1363" <.. "CNG-641" : Relates
"CNG-1363" <.. "CNG-933" : Relates
"CNG-1363" <.. "CNG-934" : Relates
"CNG-1363" <.. "CNG-962" : Relates
"CNG-1121" <.. "CNG-1073" : Relates
"CNG-1122" <.. "CNG-1030" : Relates
"CNG-1139" <.. "CNG-1039" : Relates
"CNG-1378" <.. "CNG-591" : Relates
"CNG-1378" <.. "CNG-608" : Relates
"CNG-1378" <.. "CNG-701" : Relates
"CNG-1378" <.. "CNG-702" : Relates
"CNG-1378" <.. "CNG-703" : Relates
"CNG-1378" <.. "CNG-704" : Relates
"CNG-1378" <.. "CNG-705" : Relates
"CNG-1378" <.. "CNG-960" : Relates
"CNG-1378" <.. "CNG-1019" : Relates
"CNG-1378" <.. "CNG-605" : Relates
"CNG-1378" <.. "CNG-650" : Relates
"CNG-1109" <.. "CNG-1042" : Relates
"CNG-1107" <.. "CNG-1028" : Relates
"CNG-1108" <.. "CNG-1042" : Relates
"CNG-1105" <.. "CNG-1028" : Relates
"CNG-1106" <.. "CNG-1028" : Relates
"CNG-1103" <.. "CNG-1051" : Relates
"CNG-1104" <.. "CNG-1028" : Relates
"CNG-1102" <.. "CNG-1051" : Relates
"CNG-1100" <.. "CNG-1051" : Relates
"CNG-1118" <.. "CNG-1033" : Relates
"CNG-1119" <.. "CNG-1033" : Relates
"CNG-1116" <.. "CNG-1029" : Relates
"CNG-1117" <.. "CNG-1029" : Relates
"CNG-1114" <.. "CNG-1042" : Relates
"CNG-1115" <.. "CNG-1042" : Relates
"CNG-1112" <.. "CNG-1042" : Relates
"CNG-1113" <.. "CNG-1042" : Relates
"CNG-1110" <.. "CNG-1042" : Relates
"CNG-1111" <.. "CNG-1042" : Relates


@enduml
