@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:46:42 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 2
(To Do) : 3
(UAT) : 2
(In Progress) : 5
(Design Review) : 3
----
Jira Ticket Types
----
(Task) : 8
(Sub-task) : 2
(Story) : 5
end legend


' Tickets =======
class "CNG-1252" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1274" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-391" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Design Review
  Type : Story
}

class "CNG-394" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-990" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}

class "CNG-395" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-989" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}

class "CNG-87" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-977" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Design Review
  Type : Sub-task
}

class "CNG-69" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-387" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : In Progress
  Type : Task
}

class "CNG-1216" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-388" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}



' Links =======
"CNG-1205" <.. "CNG-1151" : Cloners
"CNG-977" <.. "CNG-1216" : Cloners
"CNG-977" <.. "CNG-1216" : Cloners
"CNG-977" <.. "CNG-1216" : Cloners
"CNG-989" <.. "CNG-990" : Cloners
"CNG-989" <.. "CNG-990" : Cloners
"CNG-989" <.. "CNG-990" : Cloners
"CNG-69" <.. "CNG-388" : Cloners
"CNG-69" <.. "CNG-388" : Cloners
"CNG-69" <.. "CNG-387" : Cloners
"CNG-69" <.. "CNG-388" : Cloners
"CNG-69" <.. "CNG-387" : Cloners
"CNG-394" <.. "CNG-395" : Cloners
"CNG-394" <.. "CNG-395" : Cloners
"CNG-394" <.. "CNG-395" : Cloners
"CNG-1252" <.. "CNG-1274" : Cloners
"CNG-1252" <.. "CNG-1274" : Cloners
"CNG-1252" <.. "CNG-1274" : Cloners
"CNG-87" <.. "CNG-391" : Cloners
"CNG-87" <.. "CNG-391" : Cloners
"CNG-87" <.. "CNG-391" : Cloners


@enduml
