@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 19 14:50:29 CEST 2024

title Jira Tickets for Person Saranya Subramani
hide empty members

legend
Jira Ticket Status
----
(Work Complete) : 1
----
Jira Ticket Types
----
(Bug) : 1
end legend


' Tickets =======
class "CNG-1338" << (B,red) >> {
  Assigned to : Saranya Subramani
  Status : Work Complete
  Type : Bug
}



' Links =======


@enduml
