@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 16:49:39 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(IN UAT) : 8
(In Review (migrated)) : 1
(To Do) : 193
(Dev Review) : 11
(In Work) : 3
(Under Investigation) : 2
(UAT) : 19
(In Progress) : 89
(In System Test) : 7
(QA) : 11
(Build) : 3
(On Hold / Monitoring) : 2
(Design Review) : 9
----
Jira Ticket Types
----
(Risks) : 8
(Task) : 207
(Issue) : 2
(Work Request) : 2
(Bug) : 22
(Sub-task) : 59
(Story) : 57
(New Feature) : 1
end legend


' Jira Tickets =======
class "CNG-1329" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1208" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1209" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-1327" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Dev Review
  Type : Task
}

class "CNG-1206" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1328" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : In Progress
  Type : Sub-task
}

class "CNG-1207" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-893" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-651" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-530" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : In Progress
  Type : Task
}

class "CNG-1323" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1202" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : To Do
  Type : Task
}

class "CNG-895" << (P,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Accepted
  Type : Project Request Package
}

class "CNG-653" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1324" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-773" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-531" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-1321" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-897" << (P,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Denied
  Type : Project Request Package
}

class "CNG-776" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-655" << (N,lightgreen) >> {
  Status : To Do
  Type : New Feature
}

class "CNG-1322" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1201" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-654" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : In System Test
  Type : Bug
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-536" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-415" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1320" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-777" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-671" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-670" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-2" << (S,lightgreen) >> {
  Assigned to : Merin Joseph
  Status : Build
  Type : Story
}

class "CNG-1217" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1218" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1336" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-1215" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-662" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1216" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-782" << (T,lightblue) >> {
  Status : QA
  Type : Task
}

class "CNG-661" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Sub-task
}

class "CNG-1213" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-785" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-664" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : QA
  Type : Sub-task
}

class "CNG-543" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-1214" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-663" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Task
}

class "CNG-300" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1211" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-666" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1333" << (B,red) >> {
  Assigned to : Anand Jajoo
  Status : In System Test
  Type : Bug
}

class "CNG-1212" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-786" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-544" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-1330" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-668" << (S,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : In Progress
  Type : Sub-task
}

class "CNG-1331" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1210" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-667" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-516" << (B,red) >> {
  Assigned to : Dale Tubb
  Status : Rejected
  Type : Bug
}

class "CNG-999" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-1309" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-518" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : UAT
  Type : Task
}

class "CNG-1308" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1305" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1306" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1303" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-871" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1304" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-991" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-870" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1301" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-994" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-993" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Risks
}

class "CNG-996" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-1300" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-995" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-874" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Progress
  Type : Task
}

class "CNG-997" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-768" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-647" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-529" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-407" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : On Hold / Monitoring
  Type : Bug
}

class "CNG-1318" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1319" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1316" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1314" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : To Do
  Type : Sub-task
}

class "CNG-1315" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-760" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1312" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Sub-task
}

class "CNG-521" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-1313" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Sub-task
}

class "CNG-762" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1310" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-765" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : In Progress
  Type : Sub-task
}

class "CNG-644" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Build
  Type : Sub-task
}

class "CNG-1311" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-401" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-888" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-646" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-525" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-887" << (B,red) >> {
  Assigned to : Riti Agarwal
  Status : Under Investigation
  Type : Bug
}

class "CNG-645" << (T,lightblue) >> {
  Assigned to : Jayanth Vignesh
  Status : In Progress
  Type : Task
}

class "CNG-339" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Task
}

class "CNG-210" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-697" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-696" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-333" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-336" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-214" << (S,lightgreen) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Story
}

class "CNG-217" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-592" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-591" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-594" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-352" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : On Hold / Monitoring
  Type : Bug
}

class "CNG-593" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-588" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-346" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-680" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-682" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-440" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-681" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : In Progress
  Type : Sub-task
}

class "CNG-560" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-559" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-317" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-310" << (P,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : Denied
  Type : Project Request Package
}

class "CNG-672" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-675" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-312" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-795" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-798" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-556" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Dev Review
  Type : Sub-task
}

class "CNG-314" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-555" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-679" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-558" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-316" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-570" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-571" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-563" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-564" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-688" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-689" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-812" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-815" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-935" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-932" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-811" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-810" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-824" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-944" << (W,lightblue) >> {
  Assigned to : Scott Nimmo
  Status : To Do
  Type : Work Request
}

class "CNG-826" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Task
}

class "CNG-946" << (N,lightgreen) >> {
  Status : To Do
  Type : New Feature
}

class "CNG-825" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-949" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-707" << (S,lightgreen) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Story
}

class "CNG-709" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-708" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-941" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-940" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-942" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-700" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-916" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-917" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-809" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-804" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Sub-task
}

class "CNG-924" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-805" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-928" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-807" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : In Progress
  Type : Task
}

class "CNG-800" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-857" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-736" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-615" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-977" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Design Review
  Type : Sub-task
}

class "CNG-614" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-738" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-858" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-737" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-616" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-739" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-730" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-850" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-974" << (T,lightblue) >> {
  Assigned to : Pragya Singhal
  Status : To Do
  Type : Task
}

class "CNG-732" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-611" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Sub-task
}

class "CNG-731" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-610" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-734" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-975" << (T,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-990" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}

class "CNG-989" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}

class "CNG-626" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-988" << (R,red) >> {
  Status : To Do
  Type : Risks
}

class "CNG-746" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-625" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-506" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-629" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Task
}

class "CNG-508" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-981" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-741" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-620" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Task
}

class "CNG-740" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-984" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-742" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-621" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-500" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Under Investigation
  Type : Bug
}

class "CNG-987" << (R,red) >> {
  Status : To Do
  Type : Risks
}

class "CNG-624" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-986" << (W,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Work Request
}

class "CNG-865" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-623" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Sub-task
}

class "CNG-835" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-714" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-713" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-716" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-715" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-718" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-717" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-719" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-952" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-710" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-712" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-953" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-711" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-846" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-725" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-845" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-724" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-848" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-727" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-606" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-847" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-726" << (S,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : To Do
  Type : Sub-task
}

class "CNG-729" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-849" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-728" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-609" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-961" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-721" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-720" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-723" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-964" << (T,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Task
}

class "CNG-722" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-50" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-51" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-55" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-57" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-65" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-66" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-67" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-68" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-69" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-30" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-32" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-37" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-41" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-42" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-46" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-48" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Story
}

class "CNG-49" << (S,lightgreen) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Story
}

class "CNG-1086" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1087" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1084" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1085" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1082" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1083" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1080" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1081" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1088" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1089" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1098" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1093" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1091" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1092" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1090" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-908" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-902" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-904" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-906" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-28" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1185" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1064" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : In Progress
  Type : Improvement
}

class "CNG-1186" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1065" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : To Do
  Type : Improvement
}

class "CNG-1183" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1062" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : To Do
  Type : Improvement
}

class "CNG-1184" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1063" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : To Do
  Type : Improvement
}

class "CNG-1060" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1182" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1180" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1189" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1187" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1066" << (T,lightblue) >> {
  Assigned to : Sam Miles
  Status : To Do
  Type : Task
}

class "CNG-1196" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1075" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1076" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1195" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1192" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-1190" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1191" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1079" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1198" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1077" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1199" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1078" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1163" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1042" << (S,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1285" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1164" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1043" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1161" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1040" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-1283" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-1162" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1280" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-383" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-1281" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1160" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-385" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-376" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-255" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Dev Review
  Type : Task
}

class "CNG-1048" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-257" << (S,lightgreen) >> {
  Assigned to : Tony Cassidy
  Status : UAT
  Type : Story
}

class "CNG-1049" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-377" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Story
}

class "CNG-1288" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1046" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-1289" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1047" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-1286" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-1044" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-1287" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1045" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-1295" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-1174" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1053" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1175" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1054" << (S,lightblue) >> {
  Assigned to : Abdillahi Mirie
  Status : In Progress
  Type : Sub-task
}

class "CNG-1293" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1172" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1294" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : In Progress
  Type : Task
}

class "CNG-1173" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1052" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-391" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Design Review
  Type : Story
}

class "CNG-1291" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1170" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-394" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-1292" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1171" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1050" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-1290" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-395" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-387" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1059" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-388" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-1299" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1178" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1057" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Sub-task
}

class "CNG-1179" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1058" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : Dev Review
  Type : Task
}

class "CNG-269" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-1055" << (S,lightblue) >> {
  Assigned to : Abdillahi Mirie
  Status : To Do
  Type : Sub-task
}

class "CNG-1177" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1056" << (S,lightblue) >> {
  Assigned to : Abdillahi Mirie
  Status : To Do
  Type : Sub-task
}

class "CNG-1383" << (T,lightblue) >> {
  Assigned to : Philip Adams
  Status : To Do
  Type : Task
}

class "CNG-1141" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-1020" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1384" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1142" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : To Do
  Type : Task
}

class "CNG-1381" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1260" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1382" << (T,lightblue) >> {
  Assigned to : Philip Adams
  Status : To Do
  Type : Task
}

class "CNG-1140" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-1380" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-596" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-1029" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1268" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1026" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-356" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-1027" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1266" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1024" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1388" << (T,lightblue) >> {
  Assigned to : Surya Prakash Bhallamudi
  Status : To Do
  Type : Task
}

class "CNG-1267" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1146" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-1025" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-357" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-1385" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-1264" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1022" << (T,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Task
}

class "CNG-1265" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1023" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Task
}

class "CNG-1273" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Design Review
  Type : Task
}

class "CNG-1031" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Progress
  Type : Sub-task
}

class "CNG-1274" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1153" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1032" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1271" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-491" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : To Do
  Type : Task
}

class "CNG-1272" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1030" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-494" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-1039" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-485" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-364" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : Under Investigation
  Type : Bug
}

class "CNG-1279" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1158" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-367" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : In Work
  Type : Bug
}

class "CNG-1159" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1038" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-366" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : In Work
  Type : Bug
}

class "CNG-1277" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1156" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-369" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-1278" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1157" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1275" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1154" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1033" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-1155" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1034" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1361" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1240" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-1362" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1241" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-1360" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-90" << (S,lightgreen) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Story
}

class "CNG-93" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-1008" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1369" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-299" << (T,lightblue) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Task
}

class "CNG-1007" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1367" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1246" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1004" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : In Progress
  Type : Risks
}

class "CNG-1368" << (T,lightblue) >> {
  Assigned to : Surya Prakash Bhallamudi
  Status : To Do
  Type : Task
}

class "CNG-1005" << (T,lightblue) >> {
  Assigned to : Poornima Sajeendran
  Status : Design Review
  Type : Task
}

class "CNG-1244" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1123" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1366" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1003" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1363" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1242" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : To Do
  Type : Sub-task
}

class "CNG-1001" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1372" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : To Do
  Type : Task
}

class "CNG-1251" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1252" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1010" << (I,orange) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Issue
}

class "CNG-1370" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1371" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1250" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1138" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-1017" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1139" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : In Progress
  Type : Task
}

class "CNG-1378" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1136" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1015" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-1379" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-1137" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-1376" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1134" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : Build
  Type : Task
}

class "CNG-1013" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-1377" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1256" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1135" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1374" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1253" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1132" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1011" << (R,red) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Risks
}

class "CNG-1375" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-1254" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-1133" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1012" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-70" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-71" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-72" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-73" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Story
}

class "CNG-74" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-75" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : Design Review
  Type : Story
}

class "CNG-77" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-78" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Story
}

class "CNG-79" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Build
  Type : Story
}

class "CNG-1107" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1229" << (I,orange) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Issue
}

class "CNG-1347" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-1226" << (T,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Task
}

class "CNG-398" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-1348" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Rejected
  Type : Bug
}

class "CNG-1224" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1225" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-1222" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1101" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1344" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Under Investigation
  Type : Bug
}

class "CNG-1223" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-1342" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-1351" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1230" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-293" << (T,lightblue) >> {
  Assigned to : Poornima Sajeendran
  Status : In Progress
  Type : Task
}

class "CNG-294" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-81" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Story
}

class "CNG-82" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-84" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-85" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-87" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-1358" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-1237" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1359" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1238" << (S,lightblue) >> {
  Assigned to : Jayanth Vignesh
  Status : Dev Review
  Type : Sub-task
}

class "CNG-1356" << (B,red) >> {
  Assigned to : Anand Jajoo
  Status : In Work
  Type : Bug
}

class "CNG-1235" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1357" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-1236" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1233" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1234" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1231" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1353" << (B,red) >> {
  Assigned to : Anand Jajoo
  Status : In Work
  Type : Bug
}



' Parents =======


' Links =======
"CNG-1208" <.. "CNG-710" : Relates
"CNG-1327" <.. "CNG-961" : Dependent
"CNG-530" <.. "CNG-1237" : Dependent
"CNG-1205" <.. "CNG-685" : Relates
"CNG-1202" <.. "CNG-733" : Approval
"CNG-773" <.. "CNG-717" : Dependent
"CNG-773" <.. "CNG-716" : Dependent
"CNG-1201" <.. "CNG-733" : Approval
"CNG-654" <.. "CNG-536" : Relates
"CNG-654" <.. "CNG-394" : Relates
"CNG-533" <.. "CNG-732" : Dependent
"CNG-533" <.. "CNG-688" : Relates
"CNG-536" <.. "CNG-214" : Relates
"CNG-536" <.. "CNG-684" : Relates
"CNG-536" <.. "CNG-777" : Relates
"CNG-415" <.. "CNG-440" : Relates
"CNG-415" <.. "CNG-385" : Relates
"CNG-415" <.. "CNG-679" : Relates
"CNG-670" <.. "CNG-533" : Dependent
"CNG-2" <.. "CNG-609" : Approval
"CNG-1217" <.. "CNG-1179" : Dependent
"CNG-1217" <.. "CNG-733" : Dependent
"CNG-1218" <.. "CNG-733" : Dependent
"CNG-785" <.. "CNG-814" : Dependent
"CNG-786" <.. "CNG-815" : Dependent
"CNG-667" <.. "CNG-1007" : Relates
"CNG-999" <.. "CNG-81" : Dependent
"CNG-999" <.. "CNG-79" : Dependent
"CNG-999" <.. "CNG-393" : Dependent
"CNG-999" <.. "CNG-700" : Relates
"CNG-1309" <.. "CNG-1163" : Dependent
"CNG-518" <.. "CNG-684" : Relates
"CNG-518" <.. "CNG-739" : Relates
"CNG-1308" <.. "CNG-1163" : Dependent
"CNG-1306" <.. "CNG-557" : Dependent
"CNG-1303" <.. "CNG-733" : Dependent
"CNG-870" <.. "CNG-733" : Relates
"CNG-873" <.. "CNG-1107" : Relates
"CNG-873" <.. "CNG-1123" : Relates
"CNG-873" <.. "CNG-1205" : Relates
"CNG-873" <.. "CNG-961" : Relates
"CNG-873" <.. "CNG-710" : Relates
"CNG-873" <.. "CNG-711" : Relates
"CNG-873" <.. "CNG-1230" : Relates
"CNG-873" <.. "CNG-557" : Relates
"CNG-873" <.. "CNG-1273" : Relates
"CNG-873" <.. "CNG-1274" : Relates
"CNG-873" <.. "CNG-1275" : Relates
"CNG-873" <.. "CNG-1305" : Relates
"CNG-873" <.. "CNG-1315" : Relates
"CNG-873" <.. "CNG-1229" : Relates
"CNG-873" <.. "CNG-1379" : Relates
"CNG-993" <.. "CNG-1008" : Relates
"CNG-874" <.. "CNG-79" : Dependent
"CNG-874" <.. "CNG-81" : Dependent
"CNG-647" <.. "CNG-67" : Dependent
"CNG-647" <.. "CNG-1173" : Feature
"CNG-529" <.. "CNG-733" : Relates
"CNG-407" <.. "CNG-684" : Relates
"CNG-1318" <.. "CNG-684" : Relates
"CNG-1316" <.. "CNG-733" : Relates
"CNG-1316" <.. "CNG-367" : Relates
"CNG-760" <.. "CNG-1008" : Dependent
"CNG-521" <.. "CNG-686" : Relates
"CNG-1310" <.. "CNG-1163" : Dependent
"CNG-644" <.. "CNG-393" : Dependent
"CNG-1311" <.. "CNG-733" : Dependent
"CNG-646" <.. "CNG-687" : Relates
"CNG-887" <.. "CNG-687" : Relates
"CNG-645" <.. "CNG-79" : Dependent
"CNG-645" <.. "CNG-81" : Dependent
"CNG-339" <.. "CNG-393" : Dependent
"CNG-210" <.. "CNG-393" : Dependent
"CNG-210" <.. "CNG-1203" : Feature
"CNG-696" <.. "CNG-697" : Relates
"CNG-696" <.. "CNG-740" : Relates
"CNG-333" <.. "CNG-68" : Dependent
"CNG-214" <.. "CNG-393" : Dependent
"CNG-214" <.. "CNG-1066" : Enable
"CNG-214" <.. "CNG-1203" : Feature
"CNG-214" <.. "CNG-210" : Relates
"CNG-217" <.. "CNG-393" : Dependent
"CNG-217" <.. "CNG-1203" : Feature
"CNG-590" <.. "CNG-339" : Relates
"CNG-591" <.. "CNG-339" : Relates
"CNG-352" <.. "CNG-679" : Relates
"CNG-589" <.. "CNG-1363" : Relates
"CNG-346" <.. "CNG-69" : Approval
"CNG-680" <.. "CNG-366" : Relates
"CNG-682" <.. "CNG-1005" : Relates
"CNG-682" <.. "CNG-48" : Relates
"CNG-440" <.. "CNG-679" : Relates
"CNG-681" <.. "CNG-494" : Relates
"CNG-681" <.. "CNG-2" : Relates
"CNG-681" <.. "CNG-28" : Relates
"CNG-681" <.. "CNG-30" : Relates
"CNG-681" <.. "CNG-32" : Relates
"CNG-681" <.. "CNG-37" : Relates
"CNG-681" <.. "CNG-41" : Relates
"CNG-681" <.. "CNG-42" : Relates
"CNG-681" <.. "CNG-383" : Relates
"CNG-681" <.. "CNG-394" : Relates
"CNG-560" <.. "CNG-41" : Relates
"CNG-560" <.. "CNG-908" : Relates
"CNG-559" <.. "CNG-560" : Dependent
"CNG-559" <.. "CNG-558" : Gantt End to Start
"CNG-559" <.. "CNG-814" : Gantt End to Start
"CNG-559" <.. "CNG-79" : Relates
"CNG-559" <.. "CNG-81" : Relates
"CNG-559" <.. "CNG-84" : Relates
"CNG-559" <.. "CNG-369" : Relates
"CNG-559" <.. "CNG-78" : Relates
"CNG-559" <.. "CNG-376" : Relates
"CNG-312" <.. "CNG-559" : Relates
"CNG-795" <.. "CNG-887" : Relates
"CNG-556" <.. "CNG-557" : Dependent
"CNG-679" <.. "CNG-300" : Relates
"CNG-679" <.. "CNG-893" : Relates
"CNG-679" <.. "CNG-299" : Relates
"CNG-679" <.. "CNG-364" : Relates
"CNG-679" <.. "CNG-1190" : Relates
"CNG-679" <.. "CNG-357" : Relates
"CNG-558" <.. "CNG-269" : Relates
"CNG-557" <.. "CNG-558" : Dependent
"CNG-684" <.. "CNG-90" : Relates
"CNG-684" <.. "CNG-999" : Relates
"CNG-686" <.. "CNG-50" : Relates
"CNG-686" <.. "CNG-70" : Relates
"CNG-686" <.. "CNG-90" : Relates
"CNG-686" <.. "CNG-269" : Relates
"CNG-686" <.. "CNG-210" : Relates
"CNG-686" <.. "CNG-999" : Relates
"CNG-685" <.. "CNG-70" : Relates
"CNG-685" <.. "CNG-50" : Relates
"CNG-685" <.. "CNG-999" : Relates
"CNG-685" <.. "CNG-1225" : Relates
"CNG-685" <.. "CNG-1151" : Relates
"CNG-685" <.. "CNG-255" : Relates
"CNG-688" <.. "CNG-77" : Relates
"CNG-687" <.. "CNG-28" : Relates
"CNG-687" <.. "CNG-30" : Relates
"CNG-687" <.. "CNG-37" : Relates
"CNG-687" <.. "CNG-42" : Relates
"CNG-687" <.. "CNG-50" : Relates
"CNG-687" <.. "CNG-66" : Relates
"CNG-687" <.. "CNG-70" : Relates
"CNG-687" <.. "CNG-90" : Relates
"CNG-687" <.. "CNG-217" : Relates
"CNG-687" <.. "CNG-269" : Relates
"CNG-687" <.. "CNG-69" : Relates
"CNG-687" <.. "CNG-49" : Relates
"CNG-687" <.. "CNG-51" : Relates
"CNG-687" <.. "CNG-387" : Relates
"CNG-687" <.. "CNG-536" : Relates
"CNG-689" <.. "CNG-533" : Dependent
"CNG-935" <.. "CNG-393" : Dependent
"CNG-935" <.. "CNG-1203" : Feature
"CNG-932" <.. "CNG-809" : Dependent
"CNG-810" <.. "CNG-1022" : Approval
"CNG-824" <.. "CNG-558" : Dependent
"CNG-944" <.. "CNG-961" : Dependent
"CNG-826" <.. "CNG-395" : Dependent
"CNG-826" <.. "CNG-667" : Dependent
"CNG-825" <.. "CNG-558" : Dependent
"CNG-949" <.. "CNG-558" : Dependent
"CNG-707" <.. "CNG-393" : Dependent
"CNG-707" <.. "CNG-1203" : Feature
"CNG-708" <.. "CNG-79" : Dependent
"CNG-708" <.. "CNG-81" : Dependent
"CNG-940" <.. "CNG-592" : Dependent
"CNG-700" <.. "CNG-707" : Relates
"CNG-700" <.. "CNG-655" : Relates
"CNG-916" <.. "CNG-557" : Dependent
"CNG-804" <.. "CNG-67" : Dependent
"CNG-924" <.. "CNG-558" : Dependent
"CNG-928" <.. "CNG-558" : Dependent
"CNG-807" <.. "CNG-558" : Dependent
"CNG-800" <.. "CNG-548" : Relates
"CNG-977" <.. "CNG-1216" : Cloners
"CNG-737" <.. "CNG-723" : Dependent
"CNG-730" <.. "CNG-760" : Dependent
"CNG-850" <.. "CNG-696" : Relates
"CNG-850" <.. "CNG-333" : Relates
"CNG-974" <.. "CNG-961" : Dependent
"CNG-611" <.. "CNG-686" : Relates
"CNG-731" <.. "CNG-760" : Dependent
"CNG-610" <.. "CNG-686" : Relates
"CNG-733" <.. "CNG-1360" : Automates
"CNG-733" <.. "CNG-1385" : Automates
"CNG-733" <.. "CNG-776" : Relates
"CNG-733" <.. "CNG-1060" : Relates
"CNG-733" <.. "CNG-1154" : Relates
"CNG-733" <.. "CNG-651" : Relates
"CNG-733" <.. "CNG-506" : Relates
"CNG-733" <.. "CNG-1281" : Relates
"CNG-733" <.. "CNG-1299" : Relates
"CNG-733" <.. "CNG-1300" : Relates
"CNG-733" <.. "CNG-1301" : Relates
"CNG-733" <.. "CNG-1330" : Relates
"CNG-733" <.. "CNG-1331" : Relates
"CNG-733" <.. "CNG-1329" : Relates
"CNG-989" <.. "CNG-990" : Cloners
"CNG-626" <.. "CNG-85" : Approval
"CNG-626" <.. "CNG-74" : Approval
"CNG-626" <.. "CNG-48" : Approval
"CNG-626" <.. "CNG-82" : Approval
"CNG-626" <.. "CNG-615" : Approval
"CNG-626" <.. "CNG-624" : Approval
"CNG-626" <.. "CNG-647" : Approval
"CNG-626" <.. "CNG-871" : Approval
"CNG-626" <.. "CNG-917" : Approval
"CNG-629" <.. "CNG-67" : Dependent
"CNG-629" <.. "CNG-395" : Relates
"CNG-508" <.. "CNG-726" : Dependent
"CNG-508" <.. "CNG-733" : Relates
"CNG-981" <.. "CNG-795" : Relates
"CNG-620" <.. "CNG-604" : Dependent
"CNG-984" <.. "CNG-988" : Automates
"CNG-984" <.. "CNG-993" : Relates
"CNG-984" <.. "CNG-994" : Relates
"CNG-984" <.. "CNG-995" : Relates
"CNG-984" <.. "CNG-996" : Relates
"CNG-984" <.. "CNG-997" : Relates
"CNG-984" <.. "CNG-1004" : Relates
"CNG-624" <.. "CNG-531" : Dependent
"CNG-986" <.. "CNG-795" : Relates
"CNG-865" <.. "CNG-961" : Dependent
"CNG-865" <.. "CNG-68" : Relates
"CNG-623" <.. "CNG-687" : Relates
"CNG-952" <.. "CNG-724" : Dependent
"CNG-710" <.. "CNG-975" : Relates
"CNG-710" <.. "CNG-865" : Relates
"CNG-953" <.. "CNG-795" : Relates
"CNG-711" <.. "CNG-651" : Relates
"CNG-725" <.. "CNG-727" : Dependent
"CNG-604" <.. "CNG-738" : Relates
"CNG-604" <.. "CNG-723" : Relates
"CNG-724" <.. "CNG-993" : Automates
"CNG-727" <.. "CNG-760" : Dependent
"CNG-606" <.. "CNG-686" : Relates
"CNG-726" <.. "CNG-728" : Dependent
"CNG-729" <.. "CNG-760" : Dependent
"CNG-728" <.. "CNG-760" : Dependent
"CNG-609" <.. "CNG-686" : Relates
"CNG-961" <.. "CNG-1060" : Approval
"CNG-723" <.. "CNG-73" : Dependent
"CNG-964" <.. "CNG-795" : Relates
"CNG-50" <.. "CNG-383" : Relates
"CNG-50" <.. "CNG-629" : Relates
"CNG-50" <.. "CNG-395" : Relates
"CNG-51" <.. "CNG-741" : Feature
"CNG-55" <.. "CNG-393" : Dependent
"CNG-55" <.. "CNG-1203" : Feature
"CNG-55" <.. "CNG-684" : Relates
"CNG-55" <.. "CNG-773" : Relates
"CNG-57" <.. "CNG-79" : Dependent
"CNG-57" <.. "CNG-81" : Dependent
"CNG-57" <.. "CNG-393" : Dependent
"CNG-57" <.. "CNG-1203" : Feature
"CNG-57" <.. "CNG-687" : Relates
"CNG-65" <.. "CNG-393" : Dependent
"CNG-65" <.. "CNG-1203" : Feature
"CNG-66" <.. "CNG-393" : Dependent
"CNG-66" <.. "CNG-684" : Feature
"CNG-66" <.. "CNG-1203" : Feature
"CNG-67" <.. "CNG-1173" : Feature
"CNG-68" <.. "CNG-709" : Enable
"CNG-68" <.. "CNG-1207" : Feature
"CNG-69" <.. "CNG-388" : Cloners
"CNG-69" <.. "CNG-387" : Cloners
"CNG-69" <.. "CNG-67" : Dependent
"CNG-69" <.. "CNG-684" : Feature
"CNG-69" <.. "CNG-346" : Relates
"CNG-69" <.. "CNG-686" : Relates
"CNG-32" <.. "CNG-28" : Relates
"CNG-32" <.. "CNG-30" : Relates
"CNG-41" <.. "CNG-741" : Feature
"CNG-46" <.. "CNG-67" : Dependent
"CNG-46" <.. "CNG-684" : Feature
"CNG-46" <.. "CNG-69" : Relates
"CNG-46" <.. "CNG-521" : Relates
"CNG-46" <.. "CNG-629" : Relates
"CNG-46" <.. "CNG-687" : Relates
"CNG-48" <.. "CNG-626" : Relates
"CNG-49" <.. "CNG-684" : Feature
"CNG-49" <.. "CNG-609" : Relates
"CNG-49" <.. "CNG-689" : Relates
"CNG-908" <.. "CNG-902" : Dependent
"CNG-908" <.. "CNG-556" : Dependent
"CNG-908" <.. "CNG-785" : Relates
"CNG-902" <.. "CNG-733" : Relates
"CNG-904" <.. "CNG-557" : Dependent
"CNG-904" <.. "CNG-559" : Dependent
"CNG-906" <.. "CNG-733" : Relates
"CNG-1185" <.. "CNG-733" : Dependent
"CNG-1185" <.. "CNG-1173" : Dependent
"CNG-1186" <.. "CNG-1173" : Dependent
"CNG-1183" <.. "CNG-733" : Relates
"CNG-1184" <.. "CNG-1290" : Dependent
"CNG-1182" <.. "CNG-733" : Relates
"CNG-1180" <.. "CNG-1290" : Dependent
"CNG-1189" <.. "CNG-733" : Relates
"CNG-1187" <.. "CNG-560" : Relates
"CNG-1196" <.. "CNG-733" : Approval
"CNG-1075" <.. "CNG-733" : Relates
"CNG-1195" <.. "CNG-733" : Approval
"CNG-1192" <.. "CNG-70" : Issue split
"CNG-1190" <.. "CNG-385" : Issue split
"CNG-1198" <.. "CNG-733" : Approval
"CNG-1199" <.. "CNG-733" : Approval
"CNG-1163" <.. "CNG-733" : Dependent
"CNG-1285" <.. "CNG-1290" : Dependent
"CNG-1283" <.. "CNG-1205" : End To Start
"CNG-1280" <.. "CNG-733" : Dependent
"CNG-383" <.. "CNG-395" : Relates
"CNG-385" <.. "CNG-679" : Relates
"CNG-385" <.. "CNG-395" : Relates
"CNG-376" <.. "CNG-79" : Dependent
"CNG-376" <.. "CNG-81" : Dependent
"CNG-376" <.. "CNG-377" : Relates
"CNG-255" <.. "CNG-79" : Dependent
"CNG-255" <.. "CNG-81" : Dependent
"CNG-255" <.. "CNG-393" : Dependent
"CNG-255" <.. "CNG-684" : Feature
"CNG-1048" <.. "CNG-68" : Dependent
"CNG-1048" <.. "CNG-1207" : Feature
"CNG-257" <.. "CNG-393" : Dependent
"CNG-257" <.. "CNG-1203" : Feature
"CNG-257" <.. "CNG-592" : Relates
"CNG-1049" <.. "CNG-68" : Dependent
"CNG-1049" <.. "CNG-1207" : Feature
"CNG-377" <.. "CNG-393" : Dependent
"CNG-377" <.. "CNG-1203" : Feature
"CNG-1288" <.. "CNG-733" : Dependent
"CNG-1046" <.. "CNG-68" : Dependent
"CNG-1046" <.. "CNG-1207" : Feature
"CNG-1289" <.. "CNG-557" : Relates
"CNG-1047" <.. "CNG-68" : Dependent
"CNG-1047" <.. "CNG-1207" : Feature
"CNG-1286" <.. "CNG-1254" : Dependent
"CNG-1044" <.. "CNG-557" : Dependent
"CNG-1045" <.. "CNG-68" : Dependent
"CNG-1045" <.. "CNG-1207" : Feature
"CNG-1174" <.. "CNG-765" : Relates
"CNG-1174" <.. "CNG-804" : Relates
"CNG-1175" <.. "CNG-733" : Relates
"CNG-1293" <.. "CNG-1233" : Dependent
"CNG-1172" <.. "CNG-765" : Relates
"CNG-1172" <.. "CNG-804" : Relates
"CNG-1294" <.. "CNG-1205" : Dependent
"CNG-391" <.. "CNG-393" : Dependent
"CNG-391" <.. "CNG-1203" : Feature
"CNG-1291" <.. "CNG-1233" : Dependent
"CNG-394" <.. "CNG-395" : Cloners
"CNG-394" <.. "CNG-73" : Dependent
"CNG-394" <.. "CNG-687" : Relates
"CNG-1292" <.. "CNG-1233" : Dependent
"CNG-1050" <.. "CNG-68" : Dependent
"CNG-1050" <.. "CNG-1207" : Feature
"CNG-393" <.. "CNG-655" : Relates
"CNG-1290" <.. "CNG-1233" : Dependent
"CNG-395" <.. "CNG-73" : Relates
"CNG-387" <.. "CNG-67" : Dependent
"CNG-387" <.. "CNG-684" : Feature
"CNG-388" <.. "CNG-67" : Dependent
"CNG-388" <.. "CNG-809" : Feature
"CNG-388" <.. "CNG-1173" : Feature
"CNG-388" <.. "CNG-686" : Relates
"CNG-1179" <.. "CNG-733" : Relates
"CNG-269" <.. "CNG-415" : Approval
"CNG-269" <.. "CNG-596" : Dependent
"CNG-269" <.. "CNG-393" : Dependent
"CNG-269" <.. "CNG-684" : Feature
"CNG-269" <.. "CNG-1203" : Feature
"CNG-269" <.. "CNG-685" : Relates
"CNG-1141" <.. "CNG-1039" : Relates
"CNG-1142" <.. "CNG-1039" : Relates
"CNG-1260" <.. "CNG-1254" : Dependent
"CNG-1140" <.. "CNG-1039" : Relates
"CNG-1268" <.. "CNG-1237" : Dependent
"CNG-356" <.. "CNG-73" : Relates
"CNG-356" <.. "CNG-726" : Relates
"CNG-1266" <.. "CNG-1253" : Dependent
"CNG-1267" <.. "CNG-1253" : Dependent
"CNG-1264" <.. "CNG-1254" : Dependent
"CNG-1265" <.. "CNG-1253" : Dependent
"CNG-1153" <.. "CNG-1151" : Polaris issue link
"CNG-1153" <.. "CNG-685" : Relates
"CNG-1271" <.. "CNG-1205" : Dependent
"CNG-491" <.. "CNG-73" : Relates
"CNG-491" <.. "CNG-723" : Relates
"CNG-1272" <.. "CNG-1205" : Dependent
"CNG-1151" <.. "CNG-1205" : Blocks
"CNG-1151" <.. "CNG-1030" : Relates
"CNG-1030" <.. "CNG-1123" : Dependent
"CNG-485" <.. "CNG-67" : Dependent
"CNG-485" <.. "CNG-69" : Relates
"CNG-485" <.. "CNG-686" : Relates
"CNG-1279" <.. "CNG-733" : Relates
"CNG-367" <.. "CNG-684" : Approval
"CNG-366" <.. "CNG-984" : Relates
"CNG-1277" <.. "CNG-557" : Dependent
"CNG-1156" <.. "CNG-733" : Relates
"CNG-369" <.. "CNG-79" : Dependent
"CNG-369" <.. "CNG-81" : Dependent
"CNG-1278" <.. "CNG-557" : Dependent
"CNG-1155" <.. "CNG-1163" : Dependent
"CNG-1155" <.. "CNG-1198" : Dependent
"CNG-1155" <.. "CNG-1233" : Dependent
"CNG-1155" <.. "CNG-1234" : Dependent
"CNG-1361" <.. "CNG-590" : Relates
"CNG-1362" <.. "CNG-590" : Dependent
"CNG-90" <.. "CNG-69" : Relates
"CNG-93" <.. "CNG-68" : Approval
"CNG-93" <.. "CNG-1207" : Feature
"CNG-1369" <.. "CNG-590" : Dependent
"CNG-1007" <.. "CNG-383" : Relates
"CNG-1007" <.. "CNG-395" : Relates
"CNG-1007" <.. "CNG-394" : Relates
"CNG-1367" <.. "CNG-589" : Dependent
"CNG-1246" <.. "CNG-1237" : Dependent
"CNG-1368" <.. "CNG-590" : Dependent
"CNG-1244" <.. "CNG-1237" : Dependent
"CNG-1123" <.. "CNG-557" : Dependent
"CNG-1366" <.. "CNG-589" : Dependent
"CNG-1001" <.. "CNG-865" : Dependent
"CNG-1001" <.. "CNG-961" : Dependent
"CNG-1372" <.. "CNG-589" : Dependent
"CNG-1251" <.. "CNG-1303" : Dependent
"CNG-1252" <.. "CNG-1274" : Cloners
"CNG-1010" <.. "CNG-984" : Relates
"CNG-1370" <.. "CNG-590" : Dependent
"CNG-1371" <.. "CNG-590" : Dependent
"CNG-1250" <.. "CNG-1237" : Dependent
"CNG-1017" <.. "CNG-388" : Dependent
"CNG-1017" <.. "CNG-700" : Relates
"CNG-1139" <.. "CNG-1039" : Relates
"CNG-1378" <.. "CNG-591" : Relates
"CNG-1015" <.. "CNG-814" : Relates
"CNG-1376" <.. "CNG-1173" : Dependent
"CNG-1013" <.. "CNG-558" : Relates
"CNG-1377" <.. "CNG-1173" : Dependent
"CNG-1256" <.. "CNG-1254" : Dependent
"CNG-1374" <.. "CNG-589" : Dependent
"CNG-1253" <.. "CNG-733" : Dependent
"CNG-1011" <.. "CNG-984" : Relates
"CNG-1254" <.. "CNG-1253" : Dependent
"CNG-1254" <.. "CNG-1271" : Dependent
"CNG-1012" <.. "CNG-558" : Relates
"CNG-70" <.. "CNG-1080" : Dependent
"CNG-70" <.. "CNG-1082" : Dependent
"CNG-70" <.. "CNG-1083" : Dependent
"CNG-70" <.. "CNG-1084" : Dependent
"CNG-70" <.. "CNG-1085" : Dependent
"CNG-70" <.. "CNG-696" : Feature
"CNG-70" <.. "CNG-684" : Relates
"CNG-70" <.. "CNG-629" : Relates
"CNG-70" <.. "CNG-1191" : Relates
"CNG-71" <.. "CNG-672" : Dependent
"CNG-71" <.. "CNG-67" : Dependent
"CNG-71" <.. "CNG-647" : Enable
"CNG-71" <.. "CNG-1173" : Feature
"CNG-71" <.. "CNG-684" : Relates
"CNG-72" <.. "CNG-70" : Relates
"CNG-73" <.. "CNG-50" : Dependent
"CNG-73" <.. "CNG-30" : Dependent
"CNG-73" <.. "CNG-28" : Dependent
"CNG-73" <.. "CNG-37" : Dependent
"CNG-73" <.. "CNG-724" : Feature
"CNG-74" <.. "CNG-684" : Relates
"CNG-75" <.. "CNG-1173" : Feature
"CNG-77" <.. "CNG-741" : Feature
"CNG-78" <.. "CNG-79" : Dependent
"CNG-78" <.. "CNG-81" : Dependent
"CNG-78" <.. "CNG-393" : Dependent
"CNG-78" <.. "CNG-1203" : Feature
"CNG-1107" <.. "CNG-556" : Dependent
"CNG-398" <.. "CNG-689" : Relates
"CNG-1224" <.. "CNG-1155" : Dependent
"CNG-1224" <.. "CNG-1290" : Dependent
"CNG-1222" <.. "CNG-873" : Relates
"CNG-1223" <.. "CNG-73" : Defect
"CNG-1223" <.. "CNG-1203" : Feature
"CNG-1223" <.. "CNG-999" : Relates
"CNG-293" <.. "CNG-679" : Relates
"CNG-293" <.. "CNG-1005" : Relates
"CNG-294" <.. "CNG-679" : Relates
"CNG-82" <.. "CNG-393" : Dependent
"CNG-82" <.. "CNG-1203" : Feature
"CNG-84" <.. "CNG-393" : Dependent
"CNG-84" <.. "CNG-1203" : Feature
"CNG-84" <.. "CNG-592" : Relates
"CNG-87" <.. "CNG-391" : Cloners
"CNG-87" <.. "CNG-393" : Dependent
"CNG-87" <.. "CNG-1203" : Feature
"CNG-1237" <.. "CNG-733" : Dependent
"CNG-1235" <.. "CNG-388" : Relates
"CNG-1235" <.. "CNG-32" : Relates
"CNG-1235" <.. "CNG-46" : Relates
"CNG-1235" <.. "CNG-69" : Relates
"CNG-1235" <.. "CNG-387" : Relates
"CNG-1235" <.. "CNG-873" : Relates
"CNG-1235" <.. "CNG-1185" : Relates
"CNG-1236" <.. "CNG-733" : Relates
"CNG-1233" <.. "CNG-733" : Dependent
"CNG-1234" <.. "CNG-1233" : Dependent
"CNG-1231" <.. "CNG-1290" : Dependent


@enduml
