@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Wed Apr 17 17:35:20 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 2
(To Do) : 8
(Under Investigation) : 1
(In Progress) : 10
(Rejected) : 1
(Raised) : 5
(Design Review) : 4
----
Jira Ticket Types
----
(Task) : 12
(Bug) : 7
(Sub-task) : 6
(Story) : 5
(New Feature) : 1
end legend


' Tickets =======
class "CNG-1340" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-79" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : QA
  Type : Story
}

class "CNG-1325" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-255" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : QA
  Type : Task
}

class "CNG-1369" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1348" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Rejected
  Type : Bug
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-655" << (N,lightgreen) >> {
  Status : To Do
  Type : New Feature
}

class "CNG-1387" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1366" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1386" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Under Investigation
  Type : Bug
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1394" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1252" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1274" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1392" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1370" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Task
}

class "CNG-1371" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-391" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Design Review
  Type : Story
}

class "CNG-592" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-84" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-87" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1359" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Progress
  Type : Task
}

class "CNG-1277" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1398" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1278" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}



' Links =======
"CNG-255" <.. "CNG-684" : Feature
"CNG-255" <.. "CNG-1359" : Relates
"CNG-393" <.. "CNG-655" : Relates
"CNG-1386" <.. "CNG-873" : Relates
"CNG-1277" <.. "CNG-557" : Dependent
"CNG-1278" <.. "CNG-557" : Dependent
"CNG-1369" <.. "CNG-590" : Dependent
"CNG-1366" <.. "CNG-589" : Dependent
"CNG-1252" <.. "CNG-1274" : Cloners
"CNG-1370" <.. "CNG-590" : Dependent
"CNG-1371" <.. "CNG-590" : Dependent
"CNG-84" <.. "CNG-393" : Dependent
"CNG-84" <.. "CNG-1203" : Feature
"CNG-84" <.. "CNG-592" : Relates
"CNG-87" <.. "CNG-391" : Cloners
"CNG-87" <.. "CNG-393" : Dependent
"CNG-87" <.. "CNG-1203" : Feature


@enduml
