@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:28:09 CEST 2024

title Jira Tickets for Person Narayana Golla
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
(In Progress) : 4
(Work Complete) : 1
----
Jira Ticket Types
----
(Task) : 3
(Bug) : 1
(Sub-task) : 1
(New Feature) : 1
end legend


' Tickets =======
class "CNG-1372" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-1283" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-1390" << (N,lightgreen) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : New Feature
}

class "CNG-1248" << (B,red) >> {
  Assigned to : Narayana Golla
  Status : Work Complete
  Type : Bug
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : Done
  Type : Task
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}



' Links =======
"CNG-1283" <.. "CNG-1205" : End To Start
"CNG-1248" <.. "CNG-1205" : Relates
"CNG-1372" <.. "CNG-589" : Dependent


@enduml
