@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 19 14:50:29 CEST 2024

title Jira Tickets for Status IN UAT
hide empty members

legend
Jira Ticket Status
----
(IN UAT) : 7
(To Do) : 3
(Done) : 1
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 1
(Bug) : 7
(Sub-task) : 4
end legend


' Tickets =======
class "CNG-559" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-606" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-904" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-494" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-521" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-599" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-536" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-646" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-777" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}



' Links =======
"CNG-536" <.. "CNG-684" : Relates
"CNG-536" <.. "CNG-777" : Relates
"CNG-521" <.. "CNG-687" : Relates
"CNG-646" <.. "CNG-687" : Relates
"CNG-606" <.. "CNG-599" : Dependent
"CNG-606" <.. "CNG-687" : Relates
"CNG-904" <.. "CNG-557" : Dependent
"CNG-904" <.. "CNG-559" : Dependent


@enduml
