@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:59 CEST 2024

title Jira Tickets for Person Sankaranarayanan Kopparasukavi
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
(In Work) : 3
----
Jira Ticket Types
----
(Task) : 1
(Bug) : 3
end legend


' Tickets =======
class "CNG-1347" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Summary : CNG-SOLR API-System Test - Getting Success Response for Solr requests when sensitive fields[fareClass related] are passed in query
  Status : In Work
  Type : Bug
}

class "CNG-822" << (T,lightblue) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Summary : SOLR API Javabin Response Format - Build
  Status : Done
  Type : Task
}

class "CNG-1397" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Summary : CNG - SOLR API - System Test - MIN,MAX issues for different handlers and propositions.
  Status : In Work
  Type : Bug
}

class "CNG-1342" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Summary : CNG - SOLR API - System Test - Missing fields in FH and HO Propositions
  Status : In Work
  Type : Bug
}



' Links =======


@enduml
