@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:28:09 CEST 2024

title Jira Tickets for Status In Progress
hide empty members

legend
Jira Ticket Status
----
(In Review (migrated)) : 1
(IN UAT) : 1
(To Do) : 31
(Done) : 42
(Dev Review) : 1
(In Progress) : 106
(Raised) : 4
(Design Review) : 2
----
Jira Ticket Types
----
(Risks) : 2
(Task) : 127
(Improvement) : 2
(Issue) : 1
(Work Request) : 2
(Bug) : 5
(Sub-task) : 47
(Story) : 1
(New Feature) : 1
end legend


' Tickets =======
class "CNG-1042" << (S,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1163" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1285" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1040" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-1283" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-1281" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1329" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1328" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : In Progress
  Type : Sub-task
}

class "CNG-818" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-651" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1204" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Done
  Type : Task
}

class "CNG-893" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-892" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : Done
  Type : Task
}

class "CNG-1326" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-774" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-773" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-894" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-776" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1288" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1200" << (T,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : Done
  Type : Task
}

class "CNG-1201" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-1044" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-1295" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-1054" << (S,lightblue) >> {
  Assigned to : Abdillahi Mirie
  Status : In Progress
  Type : Sub-task
}

class "CNG-1175" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1052" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-1173" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1290" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-824" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-428" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Story
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-1219" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Done
  Type : Task
}

class "CNG-662" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1216" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-785" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1299" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-666" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1330" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1176" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-668" << (S,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : In Progress
  Type : Sub-task
}

class "CNG-1210" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-1331" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-667" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1260" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1305" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-596" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-1304" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1301" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-993" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Risks
}

class "CNG-630" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-1300" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-1025" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-874" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Progress
  Type : Task
}

class "CNG-1146" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-599" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Done
  Type : Task
}

class "CNG-1385" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-635" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1023" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Task
}

class "CNG-1031" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Progress
  Type : Sub-task
}

class "CNG-1273" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Design Review
  Type : Task
}

class "CNG-1274" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1271" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1272" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1030" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1390" << (N,lightgreen) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : New Feature
}

class "CNG-494" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-926" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-807" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : In Progress
  Type : Task
}

class "CNG-1039" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-760" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1315" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1038" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1159" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-765" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : In Progress
  Type : Sub-task
}

class "CNG-1035" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-1398" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-525" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-1154" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1275" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1033" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-767" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-645" << (T,lightblue) >> {
  Assigned to : Jayanth Vignesh
  Status : In Progress
  Type : Task
}

class "CNG-1155" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1240" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-1361" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1241" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-1360" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-581" << (S,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : Done
  Type : Sub-task
}

class "CNG-1408" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-619" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : Done
  Type : Task
}

class "CNG-1008" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1006" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1369" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1007" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1004" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : In Progress
  Type : Risks
}

class "CNG-697" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-696" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-732" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-699" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-852" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Raised
  Type : Bug
}

class "CNG-1366" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1363" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-975" << (T,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Task
}

class "CNG-1372" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-1131" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-1252" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1094" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Task
}

class "CNG-908" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-901" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-746" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-903" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-506" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-902" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1019" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1139" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : In Progress
  Type : Task
}

class "CNG-1015" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-1379" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-740" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1137" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-985" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-622" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Task
}

class "CNG-1410" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-588" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1256" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1253" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1254" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-1064" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : In Progress
  Type : Improvement
}

class "CNG-1185" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1186" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1184" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1060" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1181" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : Done
  Type : Task
}

class "CNG-680" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1061" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Improvement
}

class "CNG-681" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : In Progress
  Type : Sub-task
}

class "CNG-1180" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-834" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-716" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-717" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Sub-task
}

class "CNG-959" << (T,lightblue) >> {
  Status : Done
  Type : Task
}

class "CNG-1107" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Design Review
  Type : Task
}

class "CNG-1229" << (I,orange) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Issue
}

class "CNG-1227" << (S,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Done
  Type : Sub-task
}

class "CNG-795" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1225" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-1068" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-710" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-556" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Dev Review
  Type : Sub-task
}

class "CNG-555" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1069" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-558" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-833" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-679" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1067" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1075" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1196" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1230" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1197" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : Done
  Type : Task
}

class "CNG-1195" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1071" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1072" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-1190" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1070" << (T,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : Done
  Type : Task
}

class "CNG-725" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-724" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-603" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : Done
  Type : Task
}

class "CNG-727" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1237" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-562" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Done
  Type : Task
}

class "CNG-1359" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Progress
  Type : Task
}

class "CNG-961" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-1235" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1236" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-688" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1233" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1234" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1231" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1198" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}



' Links =======
"CNG-773" <.. "CNG-717" : Dependent
"CNG-773" <.. "CNG-716" : Dependent
"CNG-1201" <.. "CNG-733" : Approval
"CNG-533" <.. "CNG-732" : Dependent
"CNG-533" <.. "CNG-688" : Relates
"CNG-785" <.. "CNG-814" : Dependent
"CNG-760" <.. "CNG-1008" : Dependent
"CNG-589" <.. "CNG-1363" : Relates
"CNG-795" <.. "CNG-892" : Relates
"CNG-557" <.. "CNG-558" : Dependent
"CNG-733" <.. "CNG-1360" : Automates
"CNG-733" <.. "CNG-1385" : Automates
"CNG-733" <.. "CNG-1410" : Automates
"CNG-733" <.. "CNG-776" : Relates
"CNG-733" <.. "CNG-1060" : Relates
"CNG-733" <.. "CNG-1154" : Relates
"CNG-733" <.. "CNG-651" : Relates
"CNG-733" <.. "CNG-506" : Relates
"CNG-733" <.. "CNG-1281" : Relates
"CNG-733" <.. "CNG-1299" : Relates
"CNG-733" <.. "CNG-1300" : Relates
"CNG-733" <.. "CNG-1301" : Relates
"CNG-733" <.. "CNG-1330" : Relates
"CNG-733" <.. "CNG-1331" : Relates
"CNG-733" <.. "CNG-1329" : Relates
"CNG-725" <.. "CNG-727" : Dependent
"CNG-724" <.. "CNG-993" : Automates
"CNG-727" <.. "CNG-760" : Dependent
"CNG-961" <.. "CNG-1060" : Approval
"CNG-1075" <.. "CNG-733" : Relates
"CNG-1285" <.. "CNG-1290" : Dependent
"CNG-1283" <.. "CNG-1205" : End To Start
"CNG-1288" <.. "CNG-733" : Dependent
"CNG-1044" <.. "CNG-557" : Dependent
"CNG-1260" <.. "CNG-1254" : Dependent
"CNG-1023" <.. "CNG-1131" : Approval
"CNG-1023" <.. "CNG-1094" : Relates
"CNG-1272" <.. "CNG-1205" : Dependent
"CNG-1252" <.. "CNG-1274" : Cloners
"CNG-1015" <.. "CNG-814" : Relates
"CNG-1256" <.. "CNG-1254" : Dependent
"CNG-1253" <.. "CNG-733" : Dependent
"CNG-1254" <.. "CNG-1253" : Dependent
"CNG-1254" <.. "CNG-1271" : Dependent
"CNG-1230" <.. "CNG-1204" : Dependent
"CNG-1237" <.. "CNG-733" : Dependent
"CNG-1235" <.. "CNG-873" : Relates
"CNG-1235" <.. "CNG-1185" : Relates
"CNG-1236" <.. "CNG-733" : Relates
"CNG-1236" <.. "CNG-1181" : Relates
"CNG-1236" <.. "CNG-1176" : Relates
"CNG-1236" <.. "CNG-833" : Relates
"CNG-1236" <.. "CNG-699" : Relates
"CNG-1236" <.. "CNG-985" : Relates
"CNG-1236" <.. "CNG-774" : Relates
"CNG-1236" <.. "CNG-894" : Relates
"CNG-1236" <.. "CNG-903" : Relates
"CNG-1236" <.. "CNG-635" : Relates
"CNG-1236" <.. "CNG-901" : Relates
"CNG-1236" <.. "CNG-1006" : Relates
"CNG-1236" <.. "CNG-1072" : Relates
"CNG-1236" <.. "CNG-1071" : Relates
"CNG-1236" <.. "CNG-1070" : Relates
"CNG-1236" <.. "CNG-1069" : Relates
"CNG-1236" <.. "CNG-1068" : Relates
"CNG-1236" <.. "CNG-1067" : Relates
"CNG-1236" <.. "CNG-767" : Relates
"CNG-1236" <.. "CNG-1061" : Relates
"CNG-1236" <.. "CNG-1200" : Relates
"CNG-1236" <.. "CNG-1227" : Relates
"CNG-1236" <.. "CNG-1219" : Relates
"CNG-1236" <.. "CNG-562" : Relates
"CNG-1233" <.. "CNG-733" : Dependent
"CNG-1231" <.. "CNG-1290" : Dependent
"CNG-667" <.. "CNG-1007" : Relates
"CNG-873" <.. "CNG-1107" : Relates
"CNG-873" <.. "CNG-1204" : Relates
"CNG-873" <.. "CNG-961" : Relates
"CNG-873" <.. "CNG-710" : Relates
"CNG-873" <.. "CNG-1230" : Relates
"CNG-873" <.. "CNG-557" : Relates
"CNG-873" <.. "CNG-1273" : Relates
"CNG-873" <.. "CNG-1274" : Relates
"CNG-873" <.. "CNG-1275" : Relates
"CNG-873" <.. "CNG-1305" : Relates
"CNG-873" <.. "CNG-1315" : Relates
"CNG-873" <.. "CNG-1229" : Relates
"CNG-873" <.. "CNG-1379" : Relates
"CNG-874" <.. "CNG-926" : Dependent
"CNG-645" <.. "CNG-818" : Dependent
"CNG-696" <.. "CNG-697" : Relates
"CNG-696" <.. "CNG-630" : Relates
"CNG-696" <.. "CNG-740" : Relates
"CNG-680" <.. "CNG-1197" : Relates
"CNG-681" <.. "CNG-494" : Relates
"CNG-679" <.. "CNG-893" : Relates
"CNG-679" <.. "CNG-852" : Relates
"CNG-679" <.. "CNG-834" : Relates
"CNG-679" <.. "CNG-1190" : Relates
"CNG-679" <.. "CNG-1035" : Relates
"CNG-679" <.. "CNG-1326" : Relates
"CNG-824" <.. "CNG-558" : Dependent
"CNG-807" <.. "CNG-558" : Dependent
"CNG-908" <.. "CNG-902" : Dependent
"CNG-908" <.. "CNG-556" : Dependent
"CNG-908" <.. "CNG-428" : Relates
"CNG-908" <.. "CNG-785" : Relates
"CNG-1186" <.. "CNG-1173" : Dependent
"CNG-1184" <.. "CNG-1290" : Dependent
"CNG-1180" <.. "CNG-1290" : Dependent
"CNG-1196" <.. "CNG-733" : Approval
"CNG-1195" <.. "CNG-733" : Approval
"CNG-1198" <.. "CNG-733" : Approval
"CNG-1175" <.. "CNG-733" : Relates
"CNG-1151" <.. "CNG-1205" : Blocks
"CNG-1151" <.. "CNG-1227" : Blocks
"CNG-1151" <.. "CNG-1030" : Relates
"CNG-1159" <.. "CNG-630" : Relates
"CNG-1155" <.. "CNG-1163" : Dependent
"CNG-1155" <.. "CNG-1198" : Dependent
"CNG-1155" <.. "CNG-1233" : Dependent
"CNG-1155" <.. "CNG-1234" : Dependent
"CNG-1361" <.. "CNG-590" : Relates
"CNG-1361" <.. "CNG-1019" : Relates
"CNG-1361" <.. "CNG-959" : Relates
"CNG-1361" <.. "CNG-622" : Relates
"CNG-1361" <.. "CNG-619" : Relates
"CNG-1361" <.. "CNG-603" : Relates
"CNG-1361" <.. "CNG-581" : Relates
"CNG-1361" <.. "CNG-599" : Relates
"CNG-1369" <.. "CNG-590" : Dependent
"CNG-1366" <.. "CNG-589" : Dependent
"CNG-1372" <.. "CNG-589" : Dependent
"CNG-1139" <.. "CNG-1039" : Relates


@enduml
