@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 15:11:08 CEST 2024

title Jira Tickets for Person Deepak Ingwale
hide empty members

legend
Jira Ticket Status
----
(In Review (migrated)) : 1
(Done) : 11
(To Do) : 9
(Under Investigation) : 1
(In Progress) : 10
(Rejected) : 1
(Raised) : 8
(Design Review) : 1
----
Jira Ticket Types
----
(Task) : 25
(Bug) : 10
(Sub-task) : 6
(Story) : 1
end legend


' Tickets =======
class "CNG-1384" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1340" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1282" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-815" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1325" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1369" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1348" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Rejected
  Type : Bug
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1387" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1123" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1366" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1221" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1386" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Under Investigation
  Type : Bug
}

class "CNG-1152" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1296" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1252" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1274" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1392" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1150" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1370" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Task
}

class "CNG-1030" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1371" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-923" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-924" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-707" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Story
}

class "CNG-927" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-928" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1413" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1237" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1414" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1411" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1412" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1277" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1398" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1410" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1278" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1276" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}

class "CNG-1232" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Done
  Type : Task
}



' Links =======
"CNG-707" <.. "CNG-1203" : Feature
"CNG-923" <.. "CNG-557" : Dependent
"CNG-923" <.. "CNG-924" : Dependent
"CNG-927" <.. "CNG-928" : Dependent
"CNG-1282" <.. "CNG-557" : Dependent
"CNG-1296" <.. "CNG-1237" : Dependent
"CNG-1296" <.. "CNG-557" : Dependent
"CNG-1277" <.. "CNG-557" : Dependent
"CNG-1278" <.. "CNG-557" : Dependent
"CNG-1276" <.. "CNG-557" : Dependent
"CNG-1252" <.. "CNG-1274" : Cloners
"CNG-1221" <.. "CNG-815" : Dependent
"CNG-1221" <.. "CNG-873" : Relates
"CNG-1232" <.. "CNG-1237" : Dependent
"CNG-1386" <.. "CNG-873" : Relates
"CNG-1152" <.. "CNG-557" : Dependent
"CNG-1152" <.. "CNG-1030" : Relates
"CNG-1150" <.. "CNG-557" : Dependent
"CNG-1150" <.. "CNG-1030" : Relates
"CNG-1369" <.. "CNG-590" : Dependent
"CNG-1123" <.. "CNG-557" : Dependent
"CNG-1366" <.. "CNG-589" : Dependent
"CNG-1370" <.. "CNG-590" : Dependent
"CNG-1371" <.. "CNG-590" : Dependent


@enduml
