@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 10:28:35 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 12
(Done) : 1
(Dev Review) : 1
(Build) : 1
(In Progress) : 5
(Raised) : 1
----
Jira Ticket Types
----
(Task) : 12
(Bug) : 1
(Sub-task) : 7
(Story) : 1
end legend


' Tickets =======
class "CNG-592" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-493" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Done
  Type : Task
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-594" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-593" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-736" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-539" << (B,red) >> {
  Assigned to : Anand Dixit
  Status : Raised
  Type : Bug
}

class "CNG-709" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-596" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-531" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-564" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-732" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-688" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-644" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Build
  Type : Sub-task
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-401" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-525" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-734" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-624" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-723" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}



' Links =======
"CNG-533" <.. "CNG-732" : Dependent
"CNG-533" <.. "CNG-688" : Relates
"CNG-644" <.. "CNG-393" : Dependent
"CNG-624" <.. "CNG-531" : Dependent
"CNG-604" <.. "CNG-723" : Relates


@enduml
