@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 11:01:10 CEST 2024

title Jira Tickets for Person Sushant Khandelwal
hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(To Do) : 11
(Dev Review) : 3
(In Work) : 1
(UAT) : 4
(In Progress) : 12
(Design Review) : 2
----
Jira Ticket Types
----
(Risks) : 1
(Task) : 15
(Bug) : 1
(Sub-task) : 8
(Story) : 9
end legend


' Tickets =======
class "CNG-1084" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1085" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-383" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-1082" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1083" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1080" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-70" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-50" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-73" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Story
}

class "CNG-30" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-37" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-696" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1044" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-395" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-1191" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-82" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-724" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-67" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-629" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Task
}

class "CNG-28" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1336" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-661" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Sub-task
}

class "CNG-543" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-620" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Task
}

class "CNG-1015" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-544" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-984" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1011" << (R,red) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Risks
}



' Links =======
"CNG-629" <.. "CNG-67" : Dependent
"CNG-629" <.. "CNG-395" : Relates
"CNG-620" <.. "CNG-604" : Dependent
"CNG-50" <.. "CNG-383" : Relates
"CNG-50" <.. "CNG-629" : Relates
"CNG-50" <.. "CNG-395" : Relates
"CNG-1044" <.. "CNG-557" : Dependent
"CNG-1015" <.. "CNG-814" : Relates
"CNG-1011" <.. "CNG-984" : Relates
"CNG-70" <.. "CNG-1080" : Dependent
"CNG-70" <.. "CNG-1082" : Dependent
"CNG-70" <.. "CNG-1083" : Dependent
"CNG-70" <.. "CNG-1084" : Dependent
"CNG-70" <.. "CNG-1085" : Dependent
"CNG-70" <.. "CNG-696" : Feature
"CNG-70" <.. "CNG-629" : Relates
"CNG-70" <.. "CNG-1191" : Relates
"CNG-73" <.. "CNG-50" : Dependent
"CNG-73" <.. "CNG-30" : Dependent
"CNG-73" <.. "CNG-28" : Dependent
"CNG-73" <.. "CNG-37" : Dependent
"CNG-73" <.. "CNG-724" : Feature
"CNG-82" <.. "CNG-393" : Dependent
"CNG-82" <.. "CNG-1203" : Feature


@enduml
