@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 13:08:16 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(To Do) : 6
(Dev Review) : 5
(In Work) : 2
(Build) : 1
(In Progress) : 4
----
Jira Ticket Types
----
(Task) : 2
(Bug) : 2
(Sub-task) : 8
(Story) : 7
end legend


' Tickets =======
class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-81" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Story
}

class "CNG-559" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-79" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Build
  Type : Story
}

class "CNG-376" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-596" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1358" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-377" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Story
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-1357" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-369" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-874" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Progress
  Type : Task
}

class "CNG-269" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-415" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-558" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}



' Links =======
"CNG-874" <.. "CNG-79" : Dependent
"CNG-874" <.. "CNG-81" : Dependent
"CNG-874" <.. "CNG-79" : Dependent
"CNG-874" <.. "CNG-81" : Dependent
"CNG-874" <.. "CNG-79" : Dependent
"CNG-874" <.. "CNG-81" : Dependent
"CNG-376" <.. "CNG-79" : Dependent
"CNG-376" <.. "CNG-81" : Dependent
"CNG-376" <.. "CNG-559" : Relates
"CNG-376" <.. "CNG-79" : Dependent
"CNG-376" <.. "CNG-81" : Dependent
"CNG-376" <.. "CNG-377" : Relates
"CNG-376" <.. "CNG-79" : Dependent
"CNG-376" <.. "CNG-81" : Dependent
"CNG-376" <.. "CNG-377" : Relates
"CNG-269" <.. "CNG-415" : Approval
"CNG-269" <.. "CNG-596" : Dependent
"CNG-269" <.. "CNG-393" : Dependent
"CNG-269" <.. "CNG-558" : Relates
"CNG-269" <.. "CNG-687" : Relates
"CNG-269" <.. "CNG-686" : Relates
"CNG-269" <.. "CNG-415" : Approval
"CNG-269" <.. "CNG-596" : Dependent
"CNG-269" <.. "CNG-393" : Dependent
"CNG-269" <.. "CNG-684" : Feature
"CNG-269" <.. "CNG-1203" : Feature
"CNG-269" <.. "CNG-685" : Relates
"CNG-269" <.. "CNG-415" : Approval
"CNG-269" <.. "CNG-596" : Dependent
"CNG-269" <.. "CNG-393" : Dependent
"CNG-269" <.. "CNG-684" : Feature
"CNG-269" <.. "CNG-1203" : Feature
"CNG-269" <.. "CNG-685" : Relates
"CNG-369" <.. "CNG-79" : Dependent
"CNG-369" <.. "CNG-81" : Dependent
"CNG-369" <.. "CNG-559" : Relates
"CNG-369" <.. "CNG-79" : Dependent
"CNG-369" <.. "CNG-81" : Dependent
"CNG-369" <.. "CNG-79" : Dependent
"CNG-369" <.. "CNG-81" : Dependent


@enduml
