@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 14:59:12 CEST 2024

title Jira Tickets for Link Type Automates
hide empty members

legend
Jira Ticket Status
----
(To Do) : 4
(In Progress) : 4
----
Jira Ticket Types
----
(Risks) : 2
(Task) : 5
(Sub-task) : 1
end legend


' Tickets =======
class "CNG-988" << (R,red) >> {
  Status : To Do
  Type : Risks
}

class "CNG-724" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1360" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-993" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Risks
}

class "CNG-1410" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-984" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1385" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}



' Links =======
"CNG-733" <.. "CNG-1360" : Automates
"CNG-733" <.. "CNG-1385" : Automates
"CNG-733" <.. "CNG-1410" : Automates
"CNG-984" <.. "CNG-988" : Automates
"CNG-724" <.. "CNG-993" : Automates


@enduml
