@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:59 CEST 2024

title Jira Tickets for Person Sivagami S
hide empty members

legend
Jira Ticket Status
----
(Done) : 4
(To Do) : 2
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 5
(Sub-task) : 2
end legend


' Tickets =======
class "CNG-1294" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Summary : Create Cross Account Ingestion Pipeline Roles for Stack04 and OpenSearch
  Status : Done
  Type : Task
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Summary : POC for Open Search Ingestion pipeline
  Status : Done
  Type : Task
}

class "CNG-1227" << (S,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Summary : CNG - Burst (CAPTWO), Batch (CAPTWO) - Services - Establish connectivity between AWS CAPTWO stack04 to OpenSearch.
  Status : Done
  Type : Sub-task
}

class "CNG-1202" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Summary : Test the connectivity for OS endpoint from stack04
  Status : To Do
  Type : Task
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Summary : Burst & Batch Controller Build
  Status : To Do
  Type : Sub-task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Summary : AWS Infrastructure
  Status : In Progress
  Type : Task
}

class "CNG-1188" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Summary : Create Ingestion pipeline in ECP account
  Status : Done
  Type : Task
}



' Links =======
"CNG-1205" <.. "CNG-1227" : Enable
"CNG-1205" <.. "CNG-685" : Relates
"CNG-1202" <.. "CNG-733" : Approval
"CNG-1202" <.. "CNG-1188" : Dependent
"CNG-1294" <.. "CNG-1205" : Dependent


@enduml
