@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 3
(To Do) : 5
(In Work) : 1
(Build) : 1
(Under Investigation) : 1
(In Progress) : 6
(In System Test) : 1
----
Jira Ticket Types
----
(Task) : 7
(Bug) : 3
(Sub-task) : 6
(Story) : 2
end legend


' Tickets =======
class "CNG-1052" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-394" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-671" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-395" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-670" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-90" << (S,lightgreen) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Story
}

class "CNG-725" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-826" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Task
}

class "CNG-2" << (S,lightgreen) >> {
  Assigned to : Merin Joseph
  Status : Build
  Type : Story
}

class "CNG-1379" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-366" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : In Work
  Type : Bug
}

class "CNG-773" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-663" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Task
}

class "CNG-1137" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-1225" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-1344" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Under Investigation
  Type : Bug
}

class "CNG-654" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : In System Test
  Type : Bug
}



' Links =======


@enduml
