@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(In Review (migrated)) : 3
(To Do) : 57
(Dev Review) : 1
(In Work) : 1
(UAT) : 1
(In Progress) : 12
(On Hold / Monitoring) : 1
----
Jira Ticket Types
----
(Risks) : 4
(Task) : 46
(Issue) : 1
(Work Request) : 1
(Bug) : 2
(Sub-task) : 20
(Story) : 3
end legend


' Tickets =======
class "CNG-1163" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-385" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1081" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-615" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-55" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-614" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-616" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1329" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1208" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-739" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-697" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-653" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-696" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1003" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-415" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1010" << (I,orange) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Issue
}

class "CNG-1293" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1291" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1292" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-591" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1290" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-626" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1017" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-741" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-664" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : QA
  Type : Sub-task
}

class "CNG-300" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-740" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-666" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-588" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-700" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-986" << (W,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Work Request
}

class "CNG-1186" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1182" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-440" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-74" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-518" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : UAT
  Type : Task
}

class "CNG-716" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1309" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-718" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1308" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-717" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-917" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-719" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-871" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1029" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-672" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-994" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-795" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1024" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-996" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-556" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Dev Review
  Type : Sub-task
}

class "CNG-710" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-995" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-997" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1032" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1230" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1190" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-571" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1191" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-85" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-768" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-647" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-407" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : On Hold / Monitoring
  Type : Bug
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-760" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-367" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : In Work
  Type : Bug
}

class "CNG-762" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1310" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1233" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-721" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-720" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-722" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}



' Links =======


@enduml
