@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 11:01:10 CEST 2024

title Jira Tickets for Person BharathKum Sarangarajan
hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(In Review (migrated)) : 1
(To Do) : 16
(Dev Review) : 1
(In Progress) : 13
(Design Review) : 1
----
Jira Ticket Types
----
(Task) : 24
(Sub-task) : 6
(Story) : 3
end legend


' Tickets =======
class "CNG-1285" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-73" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Story
}

class "CNG-999" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1268" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-333" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-556" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Dev Review
  Type : Sub-task
}

class "CNG-1223" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-1264" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1271" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1272" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1030" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1290" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-908" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-68" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-902" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1318" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1237" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1315" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-785" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1059" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1299" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1057" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Sub-task
}

class "CNG-1135" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1132" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1231" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1199" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1254" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-1133" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}



' Links =======
"CNG-785" <.. "CNG-814" : Dependent
"CNG-1318" <.. "CNG-684" : Relates
"CNG-333" <.. "CNG-68" : Dependent
"CNG-908" <.. "CNG-902" : Dependent
"CNG-908" <.. "CNG-556" : Dependent
"CNG-908" <.. "CNG-785" : Relates
"CNG-1199" <.. "CNG-733" : Approval
"CNG-1285" <.. "CNG-1290" : Dependent
"CNG-1268" <.. "CNG-1237" : Dependent
"CNG-1264" <.. "CNG-1254" : Dependent
"CNG-1151" <.. "CNG-1030" : Relates
"CNG-1223" <.. "CNG-73" : Defect
"CNG-1223" <.. "CNG-1203" : Feature
"CNG-1223" <.. "CNG-999" : Relates
"CNG-1231" <.. "CNG-1290" : Dependent


@enduml
