@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 22 10:33:04 CEST 2024

title Jira Tickets for Status Resolved
hide empty members

legend
Jira Ticket Status
----
(Resolved) : 1
----
Jira Ticket Types
----
(Risk) : 1
end legend


' Tickets =======
class "CNG-545" << (X,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Resolved
  Type : Risk
}



' Links =======


@enduml
