@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 22 10:33:04 CEST 2024

title Jira Tickets for Status Design Review
hide empty members

legend
Jira Ticket Status
----
(To Do) : 1
(Done) : 1
(Dev Review) : 2
(Withdrawn) : 1
(In Progress) : 1
(Resolved (Closed)) : 1
(Design Review) : 6
----
Jira Ticket Types
----
(Task) : 6
(Bug) : 1
(Sub-task) : 5
(Impediment (Issue)) : 1
end legend


' Tickets =======
class "CNG-1273" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Design Review
  Type : Task
}

class "CNG-1370" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Task
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-977" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Design Review
  Type : Sub-task
}

class "CNG-537" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : Withdrawn
  Type : Bug
}

class "CNG-1107" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Design Review
  Type : Task
}

class "CNG-1028" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : Done
  Type : Sub-task
}

class "CNG-1216" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-620" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Task
}

class "CNG-1005" << (T,lightblue) >> {
  Assigned to : Poornima Sajeendran
  Status : Design Review
  Type : Task
}

class "CNG-556" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Dev Review
  Type : Sub-task
}

class "CNG-657" << (I,orange) >> {
  Assigned to : Shafiqul Islam
  Status : Resolved (Closed)
  Type : Impediment (Issue)
}



' Links =======
"CNG-977" <.. "CNG-1216" : Cloners
"CNG-620" <.. "CNG-657" : Blocks
"CNG-620" <.. "CNG-537" : Blocks
"CNG-620" <.. "CNG-604" : Dependent
"CNG-1370" <.. "CNG-590" : Dependent
"CNG-1107" <.. "CNG-556" : Dependent
"CNG-1107" <.. "CNG-1028" : Relates


@enduml
