@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 15:33:04 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 3
(Denied) : 1
(In Progress) : 1
(Accepted) : 1
----
Jira Ticket Types
----
(Risks) : 2
(Task) : 2
(Project Request Package) : 2
end legend


' Tickets =======
class "CNG-1008" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-299" << (T,lightblue) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Task
}

class "CNG-895" << (P,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Accepted
  Type : Project Request Package
}

class "CNG-1004" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : In Progress
  Type : Risks
}

class "CNG-993" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Risks
}

class "CNG-897" << (P,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Denied
  Type : Project Request Package
}



' Links =======
"CNG-993" <.. "CNG-1008" : Relates


@enduml
