@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 15:18:49 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 7
(In Progress) : 2
----
Jira Ticket Types
----
(Task) : 4
(Sub-task) : 5
end legend


' Tickets =======
class "CNG-714" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-713" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-715" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-651" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-795" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-712" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-711" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-964" << (T,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Task
}



' Links =======
"CNG-711" <.. "CNG-873" : Relates
"CNG-711" <.. "CNG-873" : Relates
"CNG-711" <.. "CNG-651" : Relates
"CNG-711" <.. "CNG-651" : Relates
"CNG-964" <.. "CNG-795" : Relates
"CNG-964" <.. "CNG-795" : Relates


@enduml
