@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 14:59:13 CEST 2024

title Jira Tickets for Person Rosy Mary
hide empty members

legend
Jira Ticket Status
----
(Done) : 2
----
Jira Ticket Types
----
(Task) : 1
(Sub-task) : 1
end legend


' Tickets =======
class "CNG-971" << (T,lightblue) >> {
  Assigned to : Rosy Mary
  Status : Done
  Type : Task
}

class "CNG-976" << (S,lightblue) >> {
  Assigned to : Rosy Mary
  Status : Done
  Type : Sub-task
}



' Links =======


@enduml
