@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:58 CEST 2024

title Jira Tickets for Person Saranya Subramani
hide empty members

legend
Jira Ticket Status
----
(Work Complete) : 1
----
Jira Ticket Types
----
(Bug) : 1
end legend


' Tickets =======
class "CNG-1338" << (B,red) >> {
  Assigned to : Saranya Subramani
  Summary : CNG-SOLR API-System test - Solr API retrieving documents for BA Airline brand and paxmix other than 2A in Solr response
  Status : Work Complete
  Type : Bug
}



' Links =======


@enduml
