@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 19 14:50:29 CEST 2024

title Jira Tickets for Person Swagath Ganta
hide empty members

legend
Jira Ticket Status
----
(Done) : 2
(To Do) : 3
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 2
(Sub-task) : 4
end legend


' Tickets =======
class "CNG-1228" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : Done
  Type : Sub-task
}

class "CNG-1328" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : In Progress
  Type : Sub-task
}

class "CNG-1226" << (T,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Task
}

class "CNG-1312" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Sub-task
}

class "CNG-1313" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Sub-task
}

class "CNG-1200" << (T,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : Done
  Type : Task
}



' Links =======


@enduml
