@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:28:09 CEST 2024

title Jira Tickets for Person Sankaranarayanan Kopparasukavi
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
(In Work) : 3
----
Jira Ticket Types
----
(Task) : 1
(Bug) : 3
end legend


' Tickets =======
class "CNG-1347" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-822" << (T,lightblue) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : Done
  Type : Task
}

class "CNG-1397" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-1342" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}



' Links =======


@enduml
