@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 17:00:09 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(To Do) : 18
(In Work) : 1
(Dev Review) : 1
(Build) : 1
(UAT) : 1
(In Progress) : 7
(In System Test) : 1
----
Jira Ticket Types
----
(Task) : 17
(Bug) : 2
(Sub-task) : 3
(Story) : 9
end legend


' Tickets =======
class "CNG-1060" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-93" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-74" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-615" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-917" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-871" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1202" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : To Do
  Type : Task
}

class "CNG-1201" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1022" << (T,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Task
}

class "CNG-415" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-810" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1196" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1195" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-82" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-85" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-626" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-647" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-68" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-69" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-2" << (S,lightgreen) >> {
  Assigned to : Merin Joseph
  Status : Build
  Type : Story
}

class "CNG-48" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Story
}

class "CNG-609" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-961" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-367" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : In Work
  Type : Bug
}

class "CNG-346" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-269" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-624" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-1198" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1199" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}



' Links =======
"CNG-1202" <.. "CNG-733" : Approval
"CNG-1201" <.. "CNG-733" : Approval
"CNG-2" <.. "CNG-609" : Approval
"CNG-346" <.. "CNG-69" : Approval
"CNG-810" <.. "CNG-1022" : Approval
"CNG-626" <.. "CNG-85" : Approval
"CNG-626" <.. "CNG-74" : Approval
"CNG-626" <.. "CNG-48" : Approval
"CNG-626" <.. "CNG-82" : Approval
"CNG-626" <.. "CNG-615" : Approval
"CNG-626" <.. "CNG-624" : Approval
"CNG-626" <.. "CNG-647" : Approval
"CNG-626" <.. "CNG-871" : Approval
"CNG-626" <.. "CNG-917" : Approval
"CNG-961" <.. "CNG-1060" : Approval
"CNG-1196" <.. "CNG-733" : Approval
"CNG-1195" <.. "CNG-733" : Approval
"CNG-1198" <.. "CNG-733" : Approval
"CNG-1199" <.. "CNG-733" : Approval
"CNG-269" <.. "CNG-415" : Approval
"CNG-367" <.. "CNG-684" : Approval
"CNG-93" <.. "CNG-68" : Approval


@enduml
