@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(In Work) : 3
----
Jira Ticket Types
----
(Bug) : 3
end legend


' Tickets =======
class "CNG-1347" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-1342" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-1375" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}



' Links =======


@enduml
