@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 13:01:55 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(To Do) : 1
(UAT) : 1
(In Progress) : 3
----
Jira Ticket Types
----
(Task) : 4
(Sub-task) : 1
(Story) : 1
end legend


' Tickets =======
class "CNG-1153" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1305" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-51" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}



' Links =======
"CNG-873" <.. "CNG-1305" : Polaris issue link
"CNG-687" <.. "CNG-51" : Polaris issue link
"CNG-1153" <.. "CNG-1151" : Polaris issue link
"CNG-1153" <.. "CNG-1151" : Polaris issue link


@enduml
