@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 19 14:50:29 CEST 2024

title Jira Tickets for Status QA
hide empty members

legend
Jira Ticket Status
----
(QA) : 11
(Done) : 2
(In Progress) : 3
----
Jira Ticket Types
----
(Task) : 9
(Sub-task) : 7
end legend


' Tickets =======
class "CNG-1153" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1193" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Task
}

class "CNG-999" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-729" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-1319" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-609" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-1138" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-782" << (T,lightblue) >> {
  Status : QA
  Type : Task
}

class "CNG-760" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-664" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : QA
  Type : Sub-task
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-665" << (S,lightblue) >> {
  Status : Done
  Type : Sub-task
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-610" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-689" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}



' Links =======
"CNG-729" <.. "CNG-760" : Dependent
"CNG-686" <.. "CNG-665" : Relates
"CNG-686" <.. "CNG-1193" : Relates
"CNG-686" <.. "CNG-999" : Relates
"CNG-689" <.. "CNG-533" : Dependent
"CNG-610" <.. "CNG-686" : Relates
"CNG-609" <.. "CNG-686" : Relates
"CNG-1153" <.. "CNG-1151" : Jira Product Discovery issue link
"CNG-1153" <.. "CNG-686" : Relates


@enduml
