@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 2
(To Do) : 1
(Dev Review) : 1
(Build) : 1
(In Progress) : 4
(In System Test) : 3
----
Jira Ticket Types
----
(Task) : 5
(Work Request) : 2
(Bug) : 3
(Sub-task) : 2
end legend


' Tickets =======
class "CNG-1295" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-1153" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1142" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : To Do
  Type : Task
}

class "CNG-916" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-1319" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1039" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1038" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1013" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-1134" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : Build
  Type : Task
}

class "CNG-1058" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : Dev Review
  Type : Task
}

class "CNG-1146" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-1012" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}



' Links =======


@enduml
