@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 1
(Dev Review) : 2
(Design Review) : 1
----
Jira Ticket Types
----
(Task) : 1
(Sub-task) : 1
(Story) : 2
end legend


' Tickets =======
class "CNG-339" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Task
}

class "CNG-726" << (S,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : To Do
  Type : Sub-task
}

class "CNG-391" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Design Review
  Type : Story
}

class "CNG-377" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Story
}



' Links =======


@enduml
