@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:59 CEST 2024

title Jira Tickets for Person Dale Tubb
hide empty members

legend
Jira Ticket Status
----
(Rejected) : 1
----
Jira Ticket Types
----
(Bug) : 1
end legend


' Tickets =======
class "CNG-516" << (B,red) >> {
  Assigned to : Dale Tubb
  Summary : Incorrect data in flight matrix fields (e.g. aircraft_2_O, aircraft_2_I etc.) for FC ABCBA to Paris
  Status : Rejected
  Type : Bug
}



' Links =======


@enduml
