@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 8
(Under Investigation) : 1
(In Progress) : 1
(On Hold / Monitoring) : 1
(Design Review) : 1
----
Jira Ticket Types
----
(Task) : 7
(Bug) : 2
(Sub-task) : 1
(Story) : 2
end legend


' Tickets =======
class "CNG-48" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Story
}

class "CNG-294" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-352" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : On Hold / Monitoring
  Type : Bug
}

class "CNG-1218" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-364" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : Under Investigation
  Type : Bug
}

class "CNG-1359" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1222" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1234" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-668" << (S,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : In Progress
  Type : Sub-task
}

class "CNG-75" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : Design Review
  Type : Story
}

class "CNG-865" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-953" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}



' Links =======


@enduml
