@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(Dev Review) : 3
(In Work) : 2
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 1
(Bug) : 2
(Story) : 3
end legend


' Tickets =======
class "CNG-376" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-1358" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-1357" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-369" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-874" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Progress
  Type : Task
}

class "CNG-269" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}



' Links =======


@enduml
