@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:46:43 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 2
(To Do) : 21
(Dev Review) : 4
(In Work) : 2
(UAT) : 6
(In Progress) : 16
(Design Review) : 2
----
Jira Ticket Types
----
(Risks) : 1
(Task) : 18
(Bug) : 2
(Sub-task) : 17
(Story) : 15
end legend


' Tickets =======
class "CNG-1084" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1085" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-383" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-1082" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1083" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1080" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-50" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-696" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1044" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-1173" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-395" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-626" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-67" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-69" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-629" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Task
}

class "CNG-28" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1336" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-661" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Sub-task
}

class "CNG-543" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-620" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Task
}

class "CNG-1015" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-388" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-544" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-984" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1011" << (R,red) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Risks
}

class "CNG-70" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-72" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-73" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Story
}

class "CNG-30" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-559" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-37" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-356" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-1223" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-491" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : To Do
  Type : Task
}

class "CNG-1191" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-809" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-81" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Story
}

class "CNG-82" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-724" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-46" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-726" << (S,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : To Do
  Type : Sub-task
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-1235" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-800" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}



' Links =======
"CNG-548" <.. "CNG-800" : Relates
"CNG-629" <.. "CNG-67" : Dependent
"CNG-629" <.. "CNG-46" : Relates
"CNG-629" <.. "CNG-50" : Relates
"CNG-629" <.. "CNG-70" : Relates
"CNG-629" <.. "CNG-67" : Dependent
"CNG-629" <.. "CNG-395" : Relates
"CNG-629" <.. "CNG-67" : Dependent
"CNG-629" <.. "CNG-395" : Relates
"CNG-620" <.. "CNG-604" : Dependent
"CNG-620" <.. "CNG-604" : Dependent
"CNG-620" <.. "CNG-604" : Dependent
"CNG-50" <.. "CNG-687" : Relates
"CNG-50" <.. "CNG-686" : Relates
"CNG-50" <.. "CNG-685" : Relates
"CNG-50" <.. "CNG-383" : Relates
"CNG-50" <.. "CNG-629" : Relates
"CNG-50" <.. "CNG-395" : Relates
"CNG-50" <.. "CNG-383" : Relates
"CNG-50" <.. "CNG-629" : Relates
"CNG-50" <.. "CNG-395" : Relates
"CNG-1044" <.. "CNG-557" : Dependent
"CNG-1044" <.. "CNG-557" : Dependent
"CNG-1044" <.. "CNG-557" : Dependent
"CNG-388" <.. "CNG-69" : Defect
"CNG-388" <.. "CNG-67" : Dependent
"CNG-388" <.. "CNG-1235" : Relates
"CNG-388" <.. "CNG-67" : Dependent
"CNG-388" <.. "CNG-809" : Feature
"CNG-388" <.. "CNG-1173" : Feature
"CNG-388" <.. "CNG-686" : Relates
"CNG-388" <.. "CNG-67" : Dependent
"CNG-388" <.. "CNG-809" : Feature
"CNG-388" <.. "CNG-1173" : Feature
"CNG-388" <.. "CNG-686" : Relates
"CNG-356" <.. "CNG-73" : Relates
"CNG-356" <.. "CNG-726" : Relates
"CNG-356" <.. "CNG-73" : Relates
"CNG-356" <.. "CNG-726" : Relates
"CNG-1015" <.. "CNG-814" : Relates
"CNG-1015" <.. "CNG-814" : Relates
"CNG-1011" <.. "CNG-984" : Relates
"CNG-1011" <.. "CNG-984" : Relates
"CNG-70" <.. "CNG-1080" : Dependent
"CNG-70" <.. "CNG-1082" : Dependent
"CNG-70" <.. "CNG-1083" : Dependent
"CNG-70" <.. "CNG-72" : Relates
"CNG-70" <.. "CNG-687" : Relates
"CNG-70" <.. "CNG-685" : Relates
"CNG-70" <.. "CNG-686" : Relates
"CNG-70" <.. "CNG-1080" : Dependent
"CNG-70" <.. "CNG-1082" : Dependent
"CNG-70" <.. "CNG-1083" : Dependent
"CNG-70" <.. "CNG-1084" : Dependent
"CNG-70" <.. "CNG-1085" : Dependent
"CNG-70" <.. "CNG-696" : Feature
"CNG-70" <.. "CNG-684" : Relates
"CNG-70" <.. "CNG-629" : Relates
"CNG-70" <.. "CNG-1191" : Relates
"CNG-70" <.. "CNG-1080" : Dependent
"CNG-70" <.. "CNG-1082" : Dependent
"CNG-70" <.. "CNG-1083" : Dependent
"CNG-70" <.. "CNG-1084" : Dependent
"CNG-70" <.. "CNG-1085" : Dependent
"CNG-70" <.. "CNG-696" : Feature
"CNG-70" <.. "CNG-684" : Relates
"CNG-70" <.. "CNG-629" : Relates
"CNG-70" <.. "CNG-1191" : Relates
"CNG-73" <.. "CNG-1223" : Dependent
"CNG-73" <.. "CNG-50" : Dependent
"CNG-73" <.. "CNG-30" : Dependent
"CNG-73" <.. "CNG-28" : Dependent
"CNG-73" <.. "CNG-356" : Relates
"CNG-73" <.. "CNG-395" : Relates
"CNG-73" <.. "CNG-491" : Relates
"CNG-73" <.. "CNG-50" : Dependent
"CNG-73" <.. "CNG-30" : Dependent
"CNG-73" <.. "CNG-28" : Dependent
"CNG-73" <.. "CNG-37" : Dependent
"CNG-73" <.. "CNG-724" : Feature
"CNG-73" <.. "CNG-50" : Dependent
"CNG-73" <.. "CNG-30" : Dependent
"CNG-73" <.. "CNG-28" : Dependent
"CNG-73" <.. "CNG-37" : Dependent
"CNG-73" <.. "CNG-724" : Feature
"CNG-81" <.. "CNG-559" : Relates
"CNG-82" <.. "CNG-626" : Automates
"CNG-82" <.. "CNG-393" : Dependent
"CNG-82" <.. "CNG-393" : Dependent
"CNG-82" <.. "CNG-1203" : Feature
"CNG-82" <.. "CNG-393" : Dependent
"CNG-82" <.. "CNG-1203" : Feature


@enduml
