@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:46:43 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(IN UAT) : 2
(To Do) : 17
(Under Investigation) : 1
(UAT) : 1
(In Progress) : 3
----
Jira Ticket Types
----
(Task) : 3
(Bug) : 3
(Sub-task) : 10
(Story) : 9
end legend


' Tickets =======
class "CNG-560" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-681" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : In Progress
  Type : Sub-task
}

class "CNG-70" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-93" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-72" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-77" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-1207" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1048" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-336" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-1174" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1172" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1173" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1192" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-41" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-845" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-804" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Sub-task
}

class "CNG-67" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-46" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-68" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-521" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-741" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-765" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : In Progress
  Type : Sub-task
}

class "CNG-688" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-500" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Under Investigation
  Type : Bug
}



' Links =======
"CNG-521" <.. "CNG-46" : Relates
"CNG-521" <.. "CNG-686" : Relates
"CNG-521" <.. "CNG-686" : Relates
"CNG-765" <.. "CNG-1172" : Relates
"CNG-765" <.. "CNG-1174" : Relates
"CNG-804" <.. "CNG-67" : Dependent
"CNG-804" <.. "CNG-1172" : Relates
"CNG-804" <.. "CNG-1174" : Relates
"CNG-804" <.. "CNG-67" : Dependent
"CNG-804" <.. "CNG-67" : Dependent
"CNG-67" <.. "CNG-1173" : Feature
"CNG-67" <.. "CNG-1173" : Feature
"CNG-41" <.. "CNG-560" : Relates
"CNG-41" <.. "CNG-681" : Relates
"CNG-41" <.. "CNG-741" : Feature
"CNG-41" <.. "CNG-741" : Feature
"CNG-1192" <.. "CNG-70" : Issue split
"CNG-1192" <.. "CNG-70" : Issue split
"CNG-1048" <.. "CNG-68" : Dependent
"CNG-1048" <.. "CNG-68" : Dependent
"CNG-1048" <.. "CNG-1207" : Feature
"CNG-1048" <.. "CNG-68" : Dependent
"CNG-1048" <.. "CNG-1207" : Feature
"CNG-93" <.. "CNG-68" : Approval
"CNG-93" <.. "CNG-68" : Approval
"CNG-93" <.. "CNG-1207" : Feature
"CNG-93" <.. "CNG-68" : Approval
"CNG-93" <.. "CNG-1207" : Feature
"CNG-72" <.. "CNG-70" : Relates
"CNG-72" <.. "CNG-70" : Relates
"CNG-77" <.. "CNG-688" : Relates
"CNG-77" <.. "CNG-741" : Feature
"CNG-77" <.. "CNG-741" : Feature


@enduml
