@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 12 19:54:48 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 11
(Under Investigation) : 1
(In Progress) : 8
(Raised) : 1
(Design Review) : 1
----
Jira Ticket Types
----
(Task) : 12
(Bug) : 2
(Sub-task) : 4
(Story) : 4
end legend


' Tickets =======
class "CNG-1173" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-294" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-70" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-75" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : Design Review
  Type : Story
}

class "CNG-626" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-966" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : Raised
  Type : Bug
}

class "CNG-68" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-48" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Story
}

class "CNG-1218" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-364" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : Under Investigation
  Type : Bug
}

class "CNG-1359" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-961" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-795" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1233" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1222" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1234" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-668" << (S,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : In Progress
  Type : Sub-task
}

class "CNG-679" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-865" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-953" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}



' Links =======
"CNG-1234" <.. "CNG-1233" : Dependent
"CNG-1222" <.. "CNG-873" : Relates
"CNG-48" <.. "CNG-626" : Relates
"CNG-75" <.. "CNG-1173" : Feature
"CNG-865" <.. "CNG-961" : Dependent
"CNG-865" <.. "CNG-68" : Relates
"CNG-953" <.. "CNG-795" : Relates
"CNG-1218" <.. "CNG-733" : Dependent
"CNG-966" <.. "CNG-70" : Dependent
"CNG-294" <.. "CNG-679" : Relates


@enduml
