@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 1
(In Progress) : 2
----
Jira Ticket Types
----
(Task) : 2
(Story) : 1
end legend


' Tickets =======
class "CNG-1372" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : To Do
  Type : Task
}

class "CNG-1283" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-214" << (S,lightgreen) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Story
}



' Links =======


@enduml
