@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 13
(In Progress) : 9
----
Jira Ticket Types
----
(Task) : 18
(Sub-task) : 1
(Story) : 3
end legend


' Tickets =======
class "CNG-1285" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1271" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1272" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-908" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-71" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-78" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Story
}

class "CNG-1318" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1306" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1315" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1268" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-785" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1059" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-333" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1057" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Sub-task
}

class "CNG-1135" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1223" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-1132" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1231" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1264" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1133" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1199" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}



' Links =======


@enduml
