@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 11:50:48 CEST 2024

title Jira Tickets for Link Type End To Start
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 2
end legend


' Tickets =======
class "CNG-1283" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : Done
  Type : Task
}



' Links =======
"CNG-1283" <.. "CNG-1205" : End To Start


@enduml
