@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(IN UAT) : 7
(To Do) : 4
(UAT) : 18
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 2
(Bug) : 7
(Sub-task) : 6
(Story) : 15
end legend


' Tickets =======
class "CNG-383" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-681" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : In Progress
  Type : Sub-task
}

class "CNG-51" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-30" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-857" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-32" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-559" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-858" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-57" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-37" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-210" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-312" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-730" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-536" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-217" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-777" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-494" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-42" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-65" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-66" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-606" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-46" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-69" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-904" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-28" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-387" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-485" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-646" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-623" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Sub-task
}



' Links =======


@enduml
