@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(IN UAT) : 2
(To Do) : 9
(Under Investigation) : 1
(In Progress) : 1
----
Jira Ticket Types
----
(Task) : 2
(Bug) : 3
(Sub-task) : 2
(Story) : 6
end legend


' Tickets =======
class "CNG-1192" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-93" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-72" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-41" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-77" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-845" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-67" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-804" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Sub-task
}

class "CNG-1048" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-521" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-765" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : In Progress
  Type : Sub-task
}

class "CNG-336" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-500" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Under Investigation
  Type : Bug
}



' Links =======


@enduml
