@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:59 CEST 2024

title Jira Tickets for Status Resolved
hide empty members

legend
Jira Ticket Status
----
(Resolved) : 1
----
Jira Ticket Types
----
(Risk) : 1
end legend


' Tickets =======
class "CNG-545" << (X,lightblue) >> {
  Assigned to : Anand Dixit
  Summary : Need SIP responses from SIP team to work on Response json to XML 
  Status : Resolved
  Type : Risk
}



' Links =======


@enduml
