@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 12
(Dev Review) : 1
(Build) : 1
(In Progress) : 6
----
Jira Ticket Types
----
(Task) : 11
(Sub-task) : 8
(Story) : 1
end legend


' Tickets =======
class "CNG-592" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-594" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-593" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-736" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-738" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-707" << (S,lightgreen) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Story
}

class "CNG-709" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-596" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-564" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-531" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-644" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Build
  Type : Sub-task
}

class "CNG-798" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-732" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-401" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-624" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-800" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-734" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-525" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}



' Links =======


@enduml
