@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:59 CEST 2024

title Jira Tickets for Status In System Test
hide empty members

legend
Jira Ticket Status
----
(IN UAT) : 1
(To Do) : 1
(In System Test) : 6
(In Progress) : 1
----
Jira Ticket Types
----
(Bug) : 7
(Sub-task) : 2
end legend


' Tickets =======
class "CNG-916" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Summary : SOLr b/w - differences in default response type for some handlers between live and dev
  Status : In System Test
  Type : Bug
}

class "CNG-708" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : CNG - SOLR API - NOT(!) Logic
  Status : In System Test
  Type : Bug
}

class "CNG-1357" << (B,red) >> {
  Assigned to : Rajeswari Vijayal Neelakantan
  Summary : CNG - SOLR API - System Test -Facet not returned when group.main is true
  Status : In System Test
  Type : Bug
}

class "CNG-1013" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Summary : CNG - SOLR API- Lambda - ST- group.query is  not returning results for below queries
  Status : In System Test
  Type : Bug
}

class "CNG-654" << (B,red) >> {
  Assigned to : Merin Joseph
  Summary : CNG is issuing availability requests for travel dates in the past
  Status : In System Test
  Type : Bug
}

class "CNG-558" << (S,lightblue) >> {
  Summary : Solr API - SIT
  Status : To Do
  Type : Sub-task
}

class "CNG-536" << (B,red) >> {
  Assigned to : Sulafa Malik
  Summary : Deeplink url parameters look to be incorrect
  Status : IN UAT
  Type : Bug
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Summary : Solr API - Build
  Status : In Progress
  Type : Sub-task
}

class "CNG-1012" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Summary : CNG - SOLR API- Lambda - ST- group.query is not returning results 
  Status : In System Test
  Type : Bug
}



' Links =======
"CNG-916" <.. "CNG-557" : Dependent
"CNG-1013" <.. "CNG-558" : Relates
"CNG-1012" <.. "CNG-558" : Relates
"CNG-654" <.. "CNG-536" : Relates


@enduml
