@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 14:59:13 CEST 2024

title Jira Tickets for Status Raised
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
(In System Test) : 1
(Raised) : 23
----
Jira Ticket Types
----
(Task) : 1
(Bug) : 24
end legend


' Tickets =======
class "CNG-1340" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-834" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-539" << (B,red) >> {
  Assigned to : Anand Dixit
  Status : Raised
  Type : Bug
}

class "CNG-937" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Raised
  Type : Bug
}

class "CNG-1325" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1326" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-851" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Raised
  Type : Bug
}

class "CNG-1346" << (B,red) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Raised
  Type : Bug
}

class "CNG-699" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Done
  Type : Task
}

class "CNG-1387" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-852" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Raised
  Type : Bug
}

class "CNG-854" << (B,red) >> {
  Assigned to : Pooja Ravi
  Status : Raised
  Type : Bug
}

class "CNG-1394" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : Raised
  Type : Bug
}

class "CNG-1392" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-905" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-708" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-1413" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1414" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-881" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-1411" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1412" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Raised
  Type : Bug
}

class "CNG-1035" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-1036" << (B,red) >> {
  Status : Raised
  Type : Bug
}

class "CNG-1396" << (B,red) >> {
  Assigned to : Philip Adams
  Status : Raised
  Type : Bug
}

class "CNG-502" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Raised
  Type : Bug
}



' Links =======
"CNG-881" <.. "CNG-708" : Relates
"CNG-905" <.. "CNG-699" : Blocks


@enduml
