@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Thu Apr 18 11:01:10 CEST 2024

title Jira Tickets for Person Abinaya Arumugasamy
hide empty members

legend
Jira Ticket Status
----
(To Do) : 2
(Dev Review) : 2
(In Progress) : 2
(Design Review) : 1
----
Jira Ticket Types
----
(Task) : 1
(Sub-task) : 3
(Story) : 3
end legend


' Tickets =======
class "CNG-339" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Task
}

class "CNG-726" << (S,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : To Do
  Type : Sub-task
}

class "CNG-391" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Design Review
  Type : Story
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-728" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-377" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Story
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}



' Links =======
"CNG-339" <.. "CNG-393" : Dependent
"CNG-726" <.. "CNG-728" : Dependent
"CNG-377" <.. "CNG-393" : Dependent
"CNG-377" <.. "CNG-1203" : Feature
"CNG-391" <.. "CNG-393" : Dependent
"CNG-391" <.. "CNG-1203" : Feature


@enduml
