@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
----
Jira Ticket Types
----
end legend


' Jira Tickets =======
class "CNG-906" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1360" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-616" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-491" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : To Do
  Type : Task
}

class "CNG-1123" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-746" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1379" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-644" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Build
  Type : Sub-task
}

class "CNG-742" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-949" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1353" << (B,red) >> {
  Assigned to : Anand Jajoo
  Status : In Work
  Type : Bug
}

class "CNG-991" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1022" << (T,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Task
}

class "CNG-661" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Sub-task
}

class "CNG-1155" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-536" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-1203" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1154" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-765" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : In Progress
  Type : Sub-task
}

class "CNG-1304" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1306" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1366" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-356" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-300" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-377" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Story
}

class "CNG-1160" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1157" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1331" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-741" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1159" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1158" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1136" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1017" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-944" << (W,lightblue) >> {
  Assigned to : Scott Nimmo
  Status : To Do
  Type : Work Request
}

class "CNG-398" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-79" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Build
  Type : Story
}

class "CNG-1087" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-257" << (S,lightgreen) >> {
  Assigned to : Tony Cassidy
  Status : UAT
  Type : Story
}

class "CNG-210" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1361" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-893" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-675" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-90" << (S,lightgreen) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Story
}

class "CNG-1162" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1161" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1330" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1164" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1329" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1163" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-626" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-740" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-388" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-82" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-71" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-655" << (N,lightgreen) >> {
  Status : To Do
  Type : New Feature
}

class "CNG-214" << (S,lightgreen) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Story
}

class "CNG-72" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-385" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1179" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1141" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-1234" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-516" << (B,red) >> {
  Assigned to : Dale Tubb
  Status : Rejected
  Type : Bug
}

class "CNG-1242" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : To Do
  Type : Sub-task
}

class "CNG-715" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-1023" << (T,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Task
}

class "CNG-714" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-1241" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-760" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1001" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1057" << (S,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Sub-task
}

class "CNG-544" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-1388" << (T,lightblue) >> {
  Assigned to : Surya Prakash Bhallamudi
  Status : To Do
  Type : Task
}

class "CNG-543" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Sub-task
}

class "CNG-1294" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : In Progress
  Type : Task
}

class "CNG-548" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-679" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-620" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Task
}

class "CNG-682" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-681" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : In Progress
  Type : Sub-task
}

class "CNG-680" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1030" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1029" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1032" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-908" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-621" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1031" << (S,lightblue) >> {
  Assigned to : Pratik Desai
  Status : In Progress
  Type : Sub-task
}

class "CNG-768" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1192" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-1076" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1025" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-1024" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1026" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1040" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-1039" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1027" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-1038" << (S,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1098" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1156" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-625" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-624" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-1077" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1013" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-518" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : UAT
  Type : Task
}

class "CNG-1286" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-367" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : In Work
  Type : Bug
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-346" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-1174" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-988" << (R,red) >> {
  Status : To Do
  Type : Risks
}

class "CNG-1078" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1033" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-1079" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1222" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1173" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-366" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : In Work
  Type : Bug
}

class "CNG-964" << (T,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Task
}

class "CNG-1230" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1333" << (B,red) >> {
  Assigned to : Anand Jajoo
  Status : In System Test
  Type : Bug
}

class "CNG-352" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : On Hold / Monitoring
  Type : Bug
}

class "CNG-508" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-773" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-51" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1328" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : In Progress
  Type : Sub-task
}

class "CNG-387" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-999" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-314" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-70" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-776" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-55" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-1214" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-1133" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1170" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-762" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-614" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-874" << (T,lightblue) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Progress
  Type : Task
}

class "CNG-1216" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-857" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-1215" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-1107" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1092" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1086" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-395" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-1189" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1062" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : To Do
  Type : Improvement
}

class "CNG-1093" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-646" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-1311" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-858" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-312" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-1300" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-364" << (B,red) >> {
  Assigned to : Nigel Hassett
  Status : Under Investigation
  Type : Bug
}

class "CNG-1084" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1134" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : Build
  Type : Task
}

class "CNG-1318" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-564" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-563" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-1378" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1186" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-217" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1244" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-997" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-685" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-77" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-684" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-662" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-615" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1139" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : In Progress
  Type : Task
}

class "CNG-946" << (N,lightgreen) >> {
  Status : To Do
  Type : New Feature
}

class "CNG-688" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-686" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-902" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-994" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-995" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-1246" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1007" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-996" << (R,red) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Risks
}

class "CNG-1315" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-716" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-68" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-1088" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-67" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-383" << (T,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Task
}

class "CNG-299" << (T,lightblue) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Task
}

class "CNG-30" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1190" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-376" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-993" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : To Do
  Type : Risks
}

class "CNG-49" << (S,lightgreen) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Story
}

class "CNG-984" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1183" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-269" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-73" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Design Review
  Type : Story
}

class "CNG-87" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-1310" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1065" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : To Do
  Type : Improvement
}

class "CNG-1012" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-651" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-846" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-848" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-847" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-849" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1066" << (T,lightblue) >> {
  Assigned to : Sam Miles
  Status : To Do
  Type : Task
}

class "CNG-485" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1089" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-415" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-46" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1363" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1005" << (T,lightblue) >> {
  Assigned to : Poornima Sajeendran
  Status : Design Review
  Type : Task
}

class "CNG-1004" << (R,red) >> {
  Assigned to : Sana Fathima
  Status : In Progress
  Type : Risks
}

class "CNG-28" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1090" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1085" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-41" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-1184" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1075" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-293" << (T,lightblue) >> {
  Assigned to : Poornima Sajeendran
  Status : In Progress
  Type : Task
}

class "CNG-401" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-65" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-557" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-556" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : Dev Review
  Type : Sub-task
}

class "CNG-1290" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-555" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1344" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : Under Investigation
  Type : Bug
}

class "CNG-1291" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-560" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-798" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-559" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-1292" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-558" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1308" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1293" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1199" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-940" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-941" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-942" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-932" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1309" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1091" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-93" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-48" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Story
}

class "CNG-339" << (T,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Dev Review
  Type : Task
}

class "CNG-69" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-904" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-85" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-1303" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1285" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-255" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Dev Review
  Type : Task
}

class "CNG-1240" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-1238" << (S,lightblue) >> {
  Assigned to : Jayanth Vignesh
  Status : Dev Review
  Type : Sub-task
}

class "CNG-75" << (S,lightgreen) >> {
  Assigned to : Nigel Hassett
  Status : Design Review
  Type : Story
}

class "CNG-897" << (P,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Denied
  Type : Project Request Package
}

class "CNG-1384" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-32" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-807" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : In Progress
  Type : Task
}

class "CNG-500" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Under Investigation
  Type : Bug
}

class "CNG-981" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-2" << (S,lightgreen) >> {
  Assigned to : Merin Joseph
  Status : Build
  Type : Story
}

class "CNG-689" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-1187" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-850" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1063" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : To Do
  Type : Improvement
}

class "CNG-733" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1274" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1252" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-845" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-826" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Task
}

class "CNG-529" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1301" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1385" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : To Do
  Type : Task
}

class "CNG-1279" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1049" << (S,lightgreen) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Story
}

class "CNG-1277" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1278" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1047" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-1362" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1048" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-589" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-1275" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1185" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-825" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-795" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1034" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : In Review (migrated)
  Type : Sub-task
}

class "CNG-591" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-592" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-531" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-593" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-1195" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-824" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1224" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1196" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-590" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-394" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : QA
  Type : Task
}

class "CNG-1044" << (S,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Sub-task
}

class "CNG-917" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1280" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1288" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-700" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1254" << (T,lightblue) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Task
}

class "CNG-800" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-1054" << (S,lightblue) >> {
  Assigned to : Abdillahi Mirie
  Status : In Progress
  Type : Sub-task
}

class "CNG-1253" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-777" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-530" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1055" << (S,lightblue) >> {
  Assigned to : Abdillahi Mirie
  Status : To Do
  Type : Sub-task
}

class "CNG-1043" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1316" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-974" << (T,lightblue) >> {
  Assigned to : Pragya Singhal
  Status : To Do
  Type : Task
}

class "CNG-887" << (B,red) >> {
  Assigned to : Riti Agarwal
  Status : Under Investigation
  Type : Bug
}

class "CNG-1171" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-712" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-711" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-732" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-713" << (S,lightblue) >> {
  Assigned to : Iswarya Gunasegaran
  Status : To Do
  Type : Sub-task
}

class "CNG-1207" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-316" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-707" << (S,lightgreen) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Story
}

class "CNG-1260" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1250" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1251" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-623" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Sub-task
}

class "CNG-805" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1256" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1342" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-804" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Sub-task
}

class "CNG-865" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1101" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-81" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Story
}

class "CNG-709" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-708" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-710" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1383" << (T,lightblue) >> {
  Assigned to : Philip Adams
  Status : To Do
  Type : Task
}

class "CNG-74" << (S,lightgreen) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Story
}

class "CNG-1382" << (T,lightblue) >> {
  Assigned to : Philip Adams
  Status : To Do
  Type : Task
}

class "CNG-1080" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-928" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1081" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-310" << (P,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : Denied
  Type : Project Request Package
}

class "CNG-84" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-1172" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1140" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Task
}

class "CNG-815" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-606" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-407" << (B,red) >> {
  Assigned to : Shafiqul Islam
  Status : On Hold / Monitoring
  Type : Bug
}

class "CNG-952" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-594" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-596" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Sub-task
}

class "CNG-871" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-570" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1208" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1202" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : To Do
  Type : Task
}

class "CNG-1082" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1135" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1268" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1153" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-1008" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-571" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1305" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1347" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-870" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-835" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1211" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-629" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : Dev Review
  Type : Task
}

class "CNG-1209" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-1271" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1272" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1191" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1083" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1011" << (R,red) >> {
  Assigned to : Sushant Khandelwal
  Status : To Do
  Type : Risks
}

class "CNG-1367" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1322" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-895" << (P,lightblue) >> {
  Assigned to : Sana Fathima
  Status : Accepted
  Type : Project Request Package
}

class "CNG-814" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1375" << (B,red) >> {
  Assigned to : Sankaranarayanan Kopparasukavi
  Status : In Work
  Type : Bug
}

class "CNG-785" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1299" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-654" << (B,red) >> {
  Assigned to : Merin Joseph
  Status : In System Test
  Type : Bug
}

class "CNG-611" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : To Do
  Type : Sub-task
}

class "CNG-786" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1336" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Status : In Work
  Type : Bug
}

class "CNG-782" << (T,lightblue) >> {
  Status : QA
  Type : Task
}

class "CNG-953" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-734" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-1210" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Sub-task
}

class "CNG-610" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-1351" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1020" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-696" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1212" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-697" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1010" << (I,orange) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Issue
}

class "CNG-609" << (T,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Task
}

class "CNG-1327" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Dev Review
  Type : Task
}

class "CNG-1320" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-738" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Task
}

class "CNG-1273" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : Design Review
  Type : Task
}

class "CNG-1138" << (S,lightblue) >> {
  Assigned to : Amreen Fathima
  Status : QA
  Type : Sub-task
}

class "CNG-1132" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-961" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Sub-task
}

class "CNG-1376" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1313" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Sub-task
}

class "CNG-737" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-42" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1321" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1177" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1237" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1235" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-1281" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-935" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-1377" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1233" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-1175" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-916" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Status : In System Test
  Type : Bug
}

class "CNG-440" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-37" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1151" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-50" << (S,lightgreen) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Story
}

class "CNG-721" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-720" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1312" << (S,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Sub-task
}

class "CNG-1348" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Rejected
  Type : Bug
}

class "CNG-722" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1295" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-717" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-719" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-718" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1381" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1142" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : To Do
  Type : Task
}

class "CNG-1050" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-809" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1229" << (I,orange) >> {
  Assigned to : Dileep
  Status : In Progress
  Type : Issue
}

class "CNG-1287" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1283" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : In Progress
  Type : Task
}

class "CNG-1223" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Story
}

class "CNG-533" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-1182" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-810" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-811" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1380" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-812" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-736" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Status : To Do
  Type : Sub-task
}

class "CNG-506" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Status : In Progress
  Type : Task
}

class "CNG-987" << (R,red) >> {
  Status : To Do
  Type : Risks
}

class "CNG-986" << (W,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Work Request
}

class "CNG-1206" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-604" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : Dev Review
  Type : Task
}

class "CNG-1226" << (T,lightblue) >> {
  Assigned to : Swagath Ganta
  Status : To Do
  Type : Task
}

class "CNG-1369" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1368" << (T,lightblue) >> {
  Assigned to : Surya Prakash Bhallamudi
  Status : To Do
  Type : Task
}

class "CNG-369" << (S,lightgreen) >> {
  Assigned to : Abdul Kader Nabil
  Status : Dev Review
  Type : Story
}

class "CNG-57" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1289" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-525" << (T,lightblue) >> {
  Assigned to : Anand Dixit
  Status : In Progress
  Type : Task
}

class "CNG-1371" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1231" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-1370" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1058" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : Dev Review
  Type : Task
}

class "CNG-588" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Task
}

class "CNG-494" << (B,red) >> {
  Assigned to : Sulafa Malik
  Status : IN UAT
  Type : Bug
}

class "CNG-975" << (T,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : In Progress
  Type : Task
}

class "CNG-1314" << (S,lightblue) >> {
  Assigned to : Riti Agarwal
  Status : To Do
  Type : Sub-task
}

class "CNG-977" << (S,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : Design Review
  Type : Sub-task
}

class "CNG-1217" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-1003" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1052" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-666" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : In Progress
  Type : Sub-task
}

class "CNG-663" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Task
}

class "CNG-670" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-667" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-668" << (S,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : In Progress
  Type : Sub-task
}

class "CNG-1374" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-671" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : To Do
  Type : Sub-task
}

class "CNG-1372" << (T,lightblue) >> {
  Assigned to : Narayana Golla
  Status : To Do
  Type : Task
}

class "CNG-1015" << (T,lightblue) >> {
  Assigned to : Sushant Khandelwal
  Status : In Progress
  Type : Task
}

class "CNG-78" << (S,lightgreen) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Story
}

class "CNG-729" << (S,lightblue) >> {
  Status : QA
  Type : Sub-task
}

class "CNG-739" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-731" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-730" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-66" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-1356" << (B,red) >> {
  Assigned to : Anand Jajoo
  Status : In Work
  Type : Bug
}

class "CNG-990" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}

class "CNG-924" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-333" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : In Progress
  Type : Task
}

class "CNG-672" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Sub-task
}

class "CNG-1178" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1319" << (T,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : QA
  Type : Task
}

class "CNG-653" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-1059" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1267" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1266" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1265" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1264" << (T,lightblue) >> {
  Assigned to : BharathKum Sarangarajan
  Status : To Do
  Type : Task
}

class "CNG-1053" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-724" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1359" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1213" << (S,lightblue) >> {
  Assigned to : Anand Jajoo
  Status : To Do
  Type : Sub-task
}

class "CNG-989" << (T,lightblue) >> {
  Assigned to : Dheeraj Kumar
  Status : To Do
  Type : Task
}

class "CNG-336" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-1357" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-723" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-521" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-1218" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-726" << (S,lightblue) >> {
  Assigned to : Abinaya Arumugasamy
  Status : To Do
  Type : Sub-task
}

class "CNG-1198" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1060" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : To Do
  Type : Task
}

class "CNG-725" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-664" << (S,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : QA
  Type : Sub-task
}

class "CNG-728" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-727" << (S,lightblue) >> {
  Status : In Progress
  Type : Sub-task
}

class "CNG-1137" << (T,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Task
}

class "CNG-1046" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-1225" << (S,lightblue) >> {
  Assigned to : Merin Joseph
  Status : In Progress
  Type : Sub-task
}

class "CNG-888" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-1056" << (S,lightblue) >> {
  Assigned to : Abdillahi Mirie
  Status : To Do
  Type : Sub-task
}

class "CNG-873" << (T,lightblue) >> {
  Assigned to : Paolo Brunasti
  Status : In Progress
  Type : Task
}

class "CNG-317" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-1042" << (S,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : In Progress
  Type : Sub-task
}

class "CNG-1064" << (I,lightblue) >> {
  Assigned to : Liam Rae-McLauchlan
  Status : In Progress
  Type : Improvement
}

class "CNG-645" << (T,lightblue) >> {
  Assigned to : Jayanth Vignesh
  Status : In Progress
  Type : Task
}

class "CNG-1201" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1180" << (T,lightblue) >> {
  Assigned to : Rukaya Ogazi-Khan
  Status : In Progress
  Type : Task
}

class "CNG-1236" << (T,lightblue) >> {
  Status : In Progress
  Type : Task
}

class "CNG-1045" << (S,lightgreen) >> {
  Status : To Do
  Type : Story
}

class "CNG-647" << (T,lightblue) >> {
  Assigned to : Shafiqul Islam
  Status : To Do
  Type : Task
}

class "CNG-391" << (S,lightgreen) >> {
  Assigned to : Abinaya Arumugasamy
  Status : Design Review
  Type : Story
}

class "CNG-1146" << (W,lightblue) >> {
  Assigned to : Stephy Aniyan
  Status : In Progress
  Type : Work Request
}

class "CNG-294" << (T,lightblue) >> {
  Assigned to : Nigel Hassett
  Status : To Do
  Type : Task
}

class "CNG-1324" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}

class "CNG-1358" << (B,red) >> {
  Assigned to : Abdul Kader Nabil
  Status : In Work
  Type : Bug
}

class "CNG-357" << (B,red) >> {
  Assigned to : Amreen Fathima
  Status : In System Test
  Type : Bug
}

class "CNG-1323" << (T,lightblue) >> {
  Status : To Do
  Type : Task
}



' Parents =======
"CNG-604" <|-- "CNG-746"
"CNG-50" <|-- "CNG-661"
"CNG-588" <|-- "CNG-1203"
"CNG-739" <|-- "CNG-765"
"CNG-555" <|-- "CNG-1160"
"CNG-555" <|-- "CNG-1157"
"CNG-555" <|-- "CNG-1159"
"CNG-555" <|-- "CNG-1158"
"CNG-1058" <|-- "CNG-1136"
"CNG-1080" <|-- "CNG-1087"
"CNG-533" <|-- "CNG-675"
"CNG-555" <|-- "CNG-1162"
"CNG-555" <|-- "CNG-1161"
"CNG-555" <|-- "CNG-1164"
"CNG-1235" <|-- "CNG-1242"
"CNG-709" <|-- "CNG-715"
"CNG-709" <|-- "CNG-714"
"CNG-1235" <|-- "CNG-1241"
"CNG-904" <|-- "CNG-1057"
"CNG-508" <|-- "CNG-544"
"CNG-508" <|-- "CNG-543"
"CNG-662" <|-- "CNG-679"
"CNG-662" <|-- "CNG-682"
"CNG-662" <|-- "CNG-681"
"CNG-662" <|-- "CNG-680"
"CNG-1023" <|-- "CNG-1030"
"CNG-1023" <|-- "CNG-1029"
"CNG-1023" <|-- "CNG-1032"
"CNG-1023" <|-- "CNG-1031"
"CNG-1023" <|-- "CNG-1025"
"CNG-1023" <|-- "CNG-1024"
"CNG-1023" <|-- "CNG-1026"
"CNG-1023" <|-- "CNG-1040"
"CNG-1023" <|-- "CNG-1039"
"CNG-1023" <|-- "CNG-1027"
"CNG-1023" <|-- "CNG-1038"
"CNG-629" <|-- "CNG-1098"
"CNG-624" <|-- "CNG-625"
"CNG-1076" <|-- "CNG-1077"
"CNG-662" <|-- "CNG-1174"
"CNG-1076" <|-- "CNG-1078"
"CNG-1023" <|-- "CNG-1033"
"CNG-1076" <|-- "CNG-1079"
"CNG-555" <|-- "CNG-1173"
"CNG-1226" <|-- "CNG-1328"
"CNG-975" <|-- "CNG-1214"
"CNG-662" <|-- "CNG-1170"
"CNG-975" <|-- "CNG-1216"
"CNG-708" <|-- "CNG-857"
"CNG-975" <|-- "CNG-1215"
"CNG-1085" <|-- "CNG-1092"
"CNG-1080" <|-- "CNG-1086"
"CNG-1085" <|-- "CNG-1093"
"CNG-663" <|-- "CNG-685"
"CNG-663" <|-- "CNG-684"
"CNG-663" <|-- "CNG-688"
"CNG-663" <|-- "CNG-687"
"CNG-663" <|-- "CNG-686"
"CNG-1080" <|-- "CNG-1088"
"CNG-826" <|-- "CNG-846"
"CNG-826" <|-- "CNG-848"
"CNG-826" <|-- "CNG-847"
"CNG-826" <|-- "CNG-849"
"CNG-1082" <|-- "CNG-1089"
"CNG-1082" <|-- "CNG-1090"
"CNG-555" <|-- "CNG-557"
"CNG-555" <|-- "CNG-556"
"CNG-555" <|-- "CNG-560"
"CNG-795" <|-- "CNG-798"
"CNG-555" <|-- "CNG-559"
"CNG-555" <|-- "CNG-558"
"CNG-588" <|-- "CNG-940"
"CNG-738" <|-- "CNG-941"
"CNG-723" <|-- "CNG-942"
"CNG-1082" <|-- "CNG-1091"
"CNG-1235" <|-- "CNG-1240"
"CNG-84" <|-- "CNG-1238"
"CNG-663" <|-- "CNG-689"
"CNG-588" <|-- "CNG-589"
"CNG-1023" <|-- "CNG-1034"
"CNG-588" <|-- "CNG-591"
"CNG-588" <|-- "CNG-592"
"CNG-588" <|-- "CNG-593"
"CNG-588" <|-- "CNG-590"
"CNG-1023" <|-- "CNG-1044"
"CNG-795" <|-- "CNG-800"
"CNG-904" <|-- "CNG-1054"
"CNG-904" <|-- "CNG-1055"
"CNG-662" <|-- "CNG-1171"
"CNG-709" <|-- "CNG-712"
"CNG-709" <|-- "CNG-711"
"CNG-663" <|-- "CNG-732"
"CNG-709" <|-- "CNG-713"
"CNG-709" <|-- "CNG-1207"
"CNG-606" <|-- "CNG-623"
"CNG-739" <|-- "CNG-804"
"CNG-50" <|-- "CNG-1101"
"CNG-709" <|-- "CNG-710"
"CNG-662" <|-- "CNG-1172"
"CNG-555" <|-- "CNG-815"
"CNG-594" <|-- "CNG-596"
"CNG-739" <|-- "CNG-835"
"CNG-1208" <|-- "CNG-1211"
"CNG-1208" <|-- "CNG-1209"
"CNG-555" <|-- "CNG-814"
"CNG-609" <|-- "CNG-611"
"CNG-1208" <|-- "CNG-1210"
"CNG-609" <|-- "CNG-610"
"CNG-1208" <|-- "CNG-1212"
"CNG-1137" <|-- "CNG-1138"
"CNG-709" <|-- "CNG-961"
"CNG-1226" <|-- "CNG-1313"
"CNG-1151" <|-- "CNG-1177"
"CNG-716" <|-- "CNG-721"
"CNG-716" <|-- "CNG-720"
"CNG-1226" <|-- "CNG-1312"
"CNG-716" <|-- "CNG-722"
"CNG-716" <|-- "CNG-717"
"CNG-716" <|-- "CNG-719"
"CNG-716" <|-- "CNG-718"
"CNG-738" <|-- "CNG-809"
"CNG-738" <|-- "CNG-810"
"CNG-738" <|-- "CNG-811"
"CNG-738" <|-- "CNG-812"
"CNG-588" <|-- "CNG-736"
"CNG-1151" <|-- "CNG-1206"
"CNG-1226" <|-- "CNG-1314"
"CNG-975" <|-- "CNG-977"
"CNG-999" <|-- "CNG-1052"
"CNG-533" <|-- "CNG-666"
"CNG-533" <|-- "CNG-670"
"CNG-533" <|-- "CNG-667"
"CNG-533" <|-- "CNG-668"
"CNG-533" <|-- "CNG-671"
"CNG-723" <|-- "CNG-729"
"CNG-723" <|-- "CNG-731"
"CNG-723" <|-- "CNG-730"
"CNG-533" <|-- "CNG-672"
"CNG-1151" <|-- "CNG-1178"
"CNG-999" <|-- "CNG-1053"
"CNG-723" <|-- "CNG-724"
"CNG-975" <|-- "CNG-1213"
"CNG-723" <|-- "CNG-726"
"CNG-723" <|-- "CNG-725"
"CNG-533" <|-- "CNG-664"
"CNG-723" <|-- "CNG-728"
"CNG-723" <|-- "CNG-727"
"CNG-1023" <|-- "CNG-1225"
"CNG-723" <|-- "CNG-888"
"CNG-904" <|-- "CNG-1056"
"CNG-1023" <|-- "CNG-1042"


' Links =======


@enduml
