@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(To Do) : 6
(Dev Review) : 1
(Build) : 1
(In Progress) : 3
(Rejected) : 1
(Design Review) : 2
----
Jira Ticket Types
----
(Task) : 9
(Bug) : 1
(Story) : 4
end legend


' Tickets =======
class "CNG-1384" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1370" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1371" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-393" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Story
}

class "CNG-84" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-87" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Design Review
  Type : Story
}

class "CNG-79" << (S,lightgreen) >> {
  Assigned to : Deepak Ingwale
  Status : Build
  Type : Story
}

class "CNG-255" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : Dev Review
  Type : Task
}

class "CNG-1369" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1348" << (B,red) >> {
  Assigned to : Deepak Ingwale
  Status : Rejected
  Type : Bug
}

class "CNG-1123" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1277" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}

class "CNG-1366" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : In Progress
  Type : Task
}

class "CNG-1278" << (T,lightblue) >> {
  Assigned to : Deepak Ingwale
  Status : To Do
  Type : Task
}



' Links =======


@enduml
