@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue Apr 23 13:28:09 CEST 2024

title Jira Tickets for Person Jon Funnell
hide empty members

legend
Jira Ticket Status
----
(IN UAT) : 1
(Done) : 7
(To Do) : 6
(Under Investigation) : 1
(UAT) : 1
(Withdrawn) : 3
(In Progress) : 1
(Work Complete) : 11
(Raised) : 1
----
Jira Ticket Types
----
(Task) : 8
(Bug) : 17
(Sub-task) : 4
(Story) : 3
end legend


' Tickets =======
class "CNG-480" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Withdrawn
  Type : Bug
}

class "CNG-482" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Withdrawn
  Type : Bug
}

class "CNG-460" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-416" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Task
}

class "CNG-836" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Task
}

class "CNG-1207" << (S,lightblue) >> {
  Status : To Do
  Type : Sub-task
}

class "CNG-474" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-1048" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Story
}

class "CNG-477" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-971" << (T,lightblue) >> {
  Assigned to : Rosy Mary
  Status : Done
  Type : Task
}

class "CNG-479" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-973" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Task
}

class "CNG-478" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-458" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-490" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Task
}

class "CNG-1192" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-470" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-1193" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Task
}

class "CNG-845" << (T,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Task
}

class "CNG-804" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : To Do
  Type : Sub-task
}

class "CNG-486" << (B,red) >> {
  Assigned to : Tony Cassidy
  Status : Work Complete
  Type : Bug
}

class "CNG-485" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Status : UAT
  Type : Story
}

class "CNG-521" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : IN UAT
  Type : Bug
}

class "CNG-488" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Withdrawn
  Type : Bug
}

class "CNG-765" << (S,lightblue) >> {
  Assigned to : Jon Funnell
  Status : In Progress
  Type : Sub-task
}

class "CNG-468" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-687" << (S,lightblue) >> {
  Assigned to : Sulafa Malik
  Status : To Do
  Type : Sub-task
}

class "CNG-500" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Under Investigation
  Type : Bug
}

class "CNG-423" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-489" << (S,lightgreen) >> {
  Assigned to : Jon Funnell
  Status : Done
  Type : Story
}

class "CNG-503" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Work Complete
  Type : Bug
}

class "CNG-502" << (B,red) >> {
  Assigned to : Jon Funnell
  Status : Raised
  Type : Bug
}



' Links =======
"CNG-521" <.. "CNG-687" : Relates
"CNG-973" <.. "CNG-971" : Dependent
"CNG-1048" <.. "CNG-1207" : Feature
"CNG-458" <.. "CNG-485" : Relates
"CNG-470" <.. "CNG-486" : Approval
"CNG-479" <.. "CNG-460" : Relates


@enduml
