@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri Apr 12 19:54:48 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(Raised) : 1
----
Jira Ticket Types
----
(Bug) : 1
end legend


' Tickets =======
class "CNG-854" << (B,red) >> {
  Assigned to : Pooja Ravi
  Status : Raised
  Type : Bug
}



' Links =======


@enduml
