@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Fri May 03 10:09:59 CEST 2024

title Jira Tickets for Status Work Complete
hide empty members

legend
Jira Ticket Status
----
(QA) : 1
(Done) : 2
(To Do) : 1
(UAT) : 1
(In System Test) : 1
(Work Complete) : 131
(Raised) : 1
----
Jira Ticket Types
----
(Task) : 1
(Bug) : 133
(Sub-task) : 3
(Story) : 1
end legend


' Tickets =======
class "CNG-538" << (B,red) >> {
  Assigned to : Anand Dixit
  Summary : ELK is not supporting HTTPS as keys - Issue with Version 1
  Status : Work Complete
  Type : Bug
}

class "CNG-936" << (B,red) >> {
  Assigned to : Abinaya Arumugasamy
  Summary : SIT SIP-  Special Characters are not being shown properly
  Status : Work Complete
  Type : Bug
}

class "CNG-419" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : Burst count is not calculated correctly if we give First and last travel date/lead time from and to
  Status : Work Complete
  Type : Bug
}

class "CNG-418" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Summary : Unable to see the BATCH COMPLETED records in Kibana
  Status : Work Complete
  Type : Bug
}

class "CNG-938" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Summary : SIT: Unable to see records in the Kibana
  Status : Work Complete
  Type : Bug
}

class "CNG-772" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Summary : SIT-Unable to see the Batch Completed record in Kibana
  Status : Work Complete
  Type : Bug
}

class "CNG-497" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-CostAfterTax is not showing the correct value after decimal in Kibana for the Room Rate Tag
  Status : Work Complete
  Type : Bug
}

class "CNG-1205" << (T,lightblue) >> {
  Assigned to : Sivagami S
  Summary : POC for Open Search Ingestion pipeline
  Status : Done
  Type : Task
}

class "CNG-496" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Child Age is coming in Bracket[] for HO Proposition
  Status : Work Complete
  Type : Bug
}

class "CNG-499" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Few fields are still shown in Kibana for FC and CO Proposition.
  Status : Work Complete
  Type : Bug
}

class "CNG-498" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Few fields are still shown in Kibana for FH and HO Proposition.
  Status : Work Complete
  Type : Bug
}

class "CNG-896" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : Unexpected b/w SOLr response behaviours in SIT
  Status : Work Complete
  Type : Bug
}

class "CNG-945" << (B,red) >> {
  Assigned to : Rajeswari Vijayal Neelakantan
  Summary : SIT SIP- Datatype differ in CNG SIP API for AveragePricePerPerson
  Status : Work Complete
  Type : Bug
}

class "CNG-427" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : Eligible records are not picked by burst
  Status : Work Complete
  Type : Bug
}

class "CNG-706" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT- Record Status is not being updated properly
  Status : Work Complete
  Type : Bug
}

class "CNG-1338" << (B,red) >> {
  Assigned to : Saranya Subramani
  Summary : CNG-SOLR API-System test - Solr API retrieving documents for BA Airline brand and paxmix other than 2A in Solr response
  Status : Work Complete
  Type : Bug
}

class "CNG-1339" << (B,red) >> {
  Assigned to : Rajalakshmi Ramachandran
  Summary : CNG - SOLR API - System Test - Mismatch in QTime,group,facet positions between live and CNG
  Status : Work Complete
  Type : Bug
}

class "CNG-708" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : CNG - SOLR API - NOT(!) Logic
  Status : In System Test
  Type : Bug
}

class "CNG-420" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : CMA- displayPricePerPersonPerNight is not calculated correctly for HO
  Status : Work Complete
  Type : Bug
}

class "CNG-1337" << (B,red) >> {
  Assigned to : Aswathi Ullattil
  Summary : CNG-SOLR API-System Test- Default sorting and row counts not working for safe handler in FH,FC,HO propositions and FH/hfHandler
  Status : Work Complete
  Type : Bug
}

class "CNG-1334" << (B,red) >> {
  Assigned to : Rajalakshmi Ramachandran
  Summary : CNG - SOLR API - System Test - Getting error for non sensitive fields in FH and HO propositions for all handlers
  Status : Work Complete
  Type : Bug
}

class "CNG-1335" << (B,red) >> {
  Assigned to : Naveen Kumar S
  Summary : CNG-SOLR API-System test - Invariant related issues in bahpricefeed handler for FC,HO and CO propositions
  Status : Work Complete
  Type : Bug
}

class "CNG-421" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : CNG - Batch (CAPTWO) - Impacted Component - Service - Few accommodation is missing in kibana for FH
  Status : Work Complete
  Type : Bug
}

class "CNG-1332" << (B,red) >> {
  Assigned to : Aswathi Ullattil
  Summary : CNG - SOLR API - Sanity Test - Missing field names in SOLR response for FC Proposition
  Status : Work Complete
  Type : Bug
}

class "CNG-424" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : The cached child ages in Kibana has square brackets for FC
  Status : Work Complete
  Type : Bug
}

class "CNG-1333" << (B,red) >> {
  Assigned to : Anand Jajoo
  Summary : CNG - SOLR API - System Test - Geodist() requests failing with error as all shards failed
  Status : Work Complete
  Type : Bug
}

class "CNG-423" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : Batch retry for few routes
  Status : Work Complete
  Type : Bug
}

class "CNG-426" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : Loyatly points are not cached correctly for FC proposition
  Status : Work Complete
  Type : Bug
}

class "CNG-481" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : HO - destinationCountryName actually contains destination country code
  Status : Work Complete
  Type : Bug
}

class "CNG-880" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Summary : SIT SOLR  NOT(!) -Getting null response when we add NOT(!) to flightDuration_1_O
  Status : Work Complete
  Type : Bug
}

class "CNG-484" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : FH - hotelRatePlanCode not populating (HO is ok)
  Status : Work Complete
  Type : Bug
}

class "CNG-483" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CO, FC - not all availability responses messages being cached for a CMT ref id
  Status : Work Complete
  Type : Bug
}

class "CNG-879" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLR  NOT(!) -Getting null response when we add NOT(!) to HotelID
  Status : Work Complete
  Type : Bug
}

class "CNG-878" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Summary : SIT SOLR  NOT(!) - When a market is specified with not(!) we are able to see the same value in the response
  Status : Work Complete
  Type : Bug
}

class "CNG-517" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : flightReference field is not present in Kibana for FH
  Status : Work Complete
  Type : Bug
}

class "CNG-519" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : SIT- When a huge records are pushed for Batch retry at the 3rd Cycle the records are being struck at BATCH_STARTED
  Status : Work Complete
  Type : Bug
}

class "CNG-915" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SIP- Different Timezone is shown in existing SIP API and New SIP API
  Status : Work Complete
  Type : Bug
}

class "CNG-992" << (B,red) >> {
  Assigned to : Sushant Khandelwal
  Summary : Wrong endpoint captured in SIP URL
  Status : Work Complete
  Type : Bug
}

class "CNG-475" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : FH hotelPromotionCode not being populated
  Status : Work Complete
  Type : Bug
}

class "CNG-474" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : FH flight cost not being populated (FC looks ok)
  Status : Work Complete
  Type : Bug
}

class "CNG-510" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Propositions (e.g. FH-10151 & CO-10081) - not all AncillaryIDs are being Batched
  Status : Work Complete
  Type : Bug
}

class "CNG-477" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : FC Combine And Save not being populated
  Status : Work Complete
  Type : Bug
}

class "CNG-872" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-GroupOperation is not returning the proper results for XML
  Status : Work Complete
  Type : Bug
}

class "CNG-476" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : FC numberOfStop not populated
  Status : Work Complete
  Type : Bug
}

class "CNG-512" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Unexpected field, 'event.original', present in Kibana for all propositions
  Status : Work Complete
  Type : Bug
}

class "CNG-479" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : Format of cngKey data for FC doesn't looks correct
  Status : Work Complete
  Type : Bug
}

class "CNG-511" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Inconsistent mapping of 'airlineMetal' field between FH & FC
  Status : Work Complete
  Type : Bug
}

class "CNG-478" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : FC depAirportCityName not populated - is it required?
  Status : Work Complete
  Type : Bug
}

class "CNG-514" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : HO - Caching incorrect roomTypeCode and roomType
  Status : Work Complete
  Type : Bug
}

class "CNG-876" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLR  NOT(!) - Getting default Null response for a ! query though values are present in the Cache for FC Proposition
  Status : Work Complete
  Type : Bug
}

class "CNG-1393" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Summary : CNG - SOLR API - System Test -  Json format is getting displayed in response instead of Xml format even when specified in query 
  Status : Work Complete
  Type : Bug
}

class "CNG-891" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLR-Facet with fq operation has different behaviour in New and Old solr
  Status : Work Complete
  Type : Bug
}

class "CNG-495" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Image URL is not being mapped from Content Code14
  Status : Work Complete
  Type : Bug
}

class "CNG-890" << (B,red) >> {
  Assigned to : Merin Joseph
  Summary : SIT SOLR- Unable to get the response for HO Proposition
  Status : Work Complete
  Type : Bug
}

class "CNG-889" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLR: Getting null response for carRentalPlan
  Status : Work Complete
  Type : Bug
}

class "CNG-882" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLr-Other values returned apart from fq value
  Status : Work Complete
  Type : Bug
}

class "CNG-486" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : FC - departureAirport and departureTime fields not populated as expected in Kibana
  Status : Work Complete
  Type : Bug
}

class "CNG-881" << (B,red) >> {
  Summary : SOLR B/W Compatible API SIT  for NOT(!) handling 
  Status : Raised
  Type : Bug
}

class "CNG-485" << (S,lightgreen) >> {
  Assigned to : Sulafa Malik
  Summary : (3844) - Informational Logging - Batch Controller (CAPTWO)
  Status : UAT
  Type : Story
}

class "CNG-886" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLR  NOT(!) -Filter Query with Range condition not working correctly with NOT operation
  Status : Work Complete
  Type : Bug
}

class "CNG-764" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG Application Check for APC Production Issue – FC NYC-LON Searches not producing prices in the APC 
  Status : Work Complete
  Type : Bug
}

class "CNG-885" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLR  NOT(!) - When a boardBasis is specified with! we are still able to see it in response
  Status : Work Complete
  Type : Bug
}

class "CNG-460" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : F+C not storing results for upgraded cabins as expected
  Status : Work Complete
  Type : Bug
}

class "CNG-461" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - Price difference for Car Only US Market
  Status : Work Complete
  Type : Bug
}

class "CNG-978" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : Midnight refresh and Housekeeping Job is not being Scheduled
  Status : Work Complete
  Type : Bug
}

class "CNG-856" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Query is giving response when no handler is specified in request url
  Status : Work Complete
  Type : Bug
}

class "CNG-979" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : Records are not being updated with proper Status
  Status : Work Complete
  Type : Bug
}

class "CNG-970" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Summary : SIT SIP- Inbound date is not being consider when a SIP response is created.
  Status : Work Complete
  Type : Bug
}

class "CNG-1248" << (B,red) >> {
  Assigned to : Narayana Golla
  Summary : Ingestion Pipeline host is not reachable from CAP2 and OnPrem
  Status : Work Complete
  Type : Bug
}

class "CNG-453" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : FH - We are caching BA.com holiday finder urls for IB brand
  Status : Work Complete
  Type : Bug
}

class "CNG-694" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLr-browse handler is not giving response.
  Status : Work Complete
  Type : Bug
}

class "CNG-452" << (B,red) >> {
  Assigned to : Merin Joseph
  Summary : CNG UAT - Unable to process Search requests - not being BURST
  Status : Work Complete
  Type : Bug
}

class "CNG-455" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - Unable to manually Burst content. 
  Status : Work Complete
  Type : Bug
}

class "CNG-454" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - LAST_FAILED_DATE column is not getting populated when Batches fail or retry
  Status : Work Complete
  Type : Bug
}

class "CNG-1365" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Summary : CNG - SOLR API - System Test - Referer value is not getting passed in the DeepLink
  Status : Work Complete
  Type : Bug
}

class "CNG-456" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - Child Age not being added to Deeplink url
  Status : Work Complete
  Type : Bug
}

class "CNG-459" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Current retry logic results in failed searches being re-issued many times
  Status : Work Complete
  Type : Bug
}

class "CNG-855" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT- Specified Rows are not being shown properly
  Status : Work Complete
  Type : Bug
}

class "CNG-458" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : CNG - Batch (CAPTWO) - Impacted Component - Service - Review and update CO rules for excluding results from the Cache
  Status : Work Complete
  Type : Bug
}

class "CNG-1364" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Summary : CNG - SOLR API - System Test - Response Documents are not retrieved for HO proposition for general query
  Status : Work Complete
  Type : Bug
}

class "CNG-471" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - Missing Data field (RetCabinCode) for F+C AncillaryIDs in the Cache
  Status : Work Complete
  Type : Bug
}

class "CNG-470" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : FH - departureAirport and departureTime  fields not populated in Kibana
  Status : Work Complete
  Type : Bug
}

class "CNG-473" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : FH & FC - fareclass not being stored in ELS
  Status : Work Complete
  Type : Bug
}

class "CNG-472" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : FH & FC Direct flights not being populated
  Status : Work Complete
  Type : Bug
}

class "CNG-504" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : packageDuration not being populated correctly in FC proposition
  Status : Work Complete
  Type : Bug
}

class "CNG-867" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT- Hotel Stars is returning Null response
  Status : Work Complete
  Type : Bug
}

class "CNG-509" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : 'flightCarrier_3_O' and 'terminal_3_O' field missing in Kibana for FH
  Status : Work Complete
  Type : Bug
}

class "CNG-585" << (S,lightblue) >> {
  Assigned to : Anand Dixit
  Summary : SIP B/W Compatible API SIT
  Status : Done
  Type : Sub-task
}

class "CNG-860" << (B,red) >> {
  Assigned to : Dhanish Kumar
  Summary : SIT-Getting Internal server error  for cabinupgrade & query handlers for wt=xml
  Status : Work Complete
  Type : Bug
}

class "CNG-463" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - CMT on bhdev56 is down
  Status : Work Complete
  Type : Bug
}

class "CNG-466" << (B,red) >> {
  Assigned to : Merin Joseph
  Summary : CNG UAT - Burst and Batch process has stopped working
  Status : Work Complete
  Type : Bug
}

class "CNG-862" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Extra delimiter(,) within fl results error in old solr, While result returned in New solr.
  Status : Work Complete
  Type : Bug
}

class "CNG-465" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - Child ages appearing after being removed from Search Requests
  Status : Work Complete
  Type : Bug
}

class "CNG-861" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Summary : SIT-bahpricefeed and query default wt is json for old while xml for new
  Status : Work Complete
  Type : Bug
}

class "CNG-468" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : Incorrect whitespace in market column of ancillary tables
  Status : Work Complete
  Type : Bug
}

class "CNG-864" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-sfield an pt is giving null response
  Status : Work Complete
  Type : Bug
}

class "CNG-467" << (B,red) >> {
  Assigned to : Merin Joseph
  Summary : CNG UAT - Amended Search Requests not Bursting at all
  Status : Work Complete
  Type : Bug
}

class "CNG-863" << (B,red) >> {
  Assigned to : Stephy Aniyan
  Summary : SIT-Group Operation
  Status : Work Complete
  Type : Bug
}

class "CNG-503" << (B,red) >> {
  Assigned to : Jon Funnell
  Summary : CMT - Unable to set 'First Travel Date' & 'Last Travel Date' to the same date
  Status : Work Complete
  Type : Bug
}

class "CNG-469" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Additional Whitespace being sent in availability request CountryOfResidence field
  Status : Work Complete
  Type : Bug
}

class "CNG-1375" << (B,red) >> {
  Assigned to : Rajeswari Vijayal Neelakantan
  Summary : CNG - SOLR API - System Test - totalPrice is displayed twice in SOLR response when fl=* and wt=json
  Status : Work Complete
  Type : Bug
}

class "CNG-439" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Some HO and CO availability request parameters as not as per live
  Status : Work Complete
  Type : Bug
}

class "CNG-438" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : HO index - roomTypeCode is actually storing room name
  Status : Work Complete
  Type : Bug
}

class "CNG-839" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : Hotel checkInDate and checkOutDate is not correct for HO Proposition inSOLR response
  Status : Work Complete
  Type : Bug
}

class "CNG-838" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Ancillary id is not string in the JSON response
  Status : Work Complete
  Type : Bug
}

class "CNG-1349" << (B,red) >> {
  Assigned to : Rajalakshmi Ramachandran
  Summary : CNG - SOLR API - System Test - Date format issue in groupvalue for given date related fields
  Status : Work Complete
  Type : Bug
}

class "CNG-431" << (B,red) >> {
  Summary : Some FH Package Search parameters are not as per live 
  Status : Work Complete
  Type : Bug
}

class "CNG-430" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : Back-off period is not calculated properly for HO and CO propositions
  Status : Work Complete
  Type : Bug
}

class "CNG-796" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Different Data types Observed in SIT KIBANA and e2e Data Mapping
  Status : Work Complete
  Type : Bug
}

class "CNG-433" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : Brand and chain code are not cached in Kibana
  Status : Work Complete
  Type : Bug
}

class "CNG-1345" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Summary : CNG - SOLR API - System Test - Protocol and Context path is missing in DeepLink
  Status : Work Complete
  Type : Bug
}

class "CNG-432" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Some FC Package Search parameters are not as per live
  Status : Work Complete
  Type : Bug
}

class "CNG-435" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CO index -  carBrandIdentifier is storing full car supplier name and not supplier code
  Status : Work Complete
  Type : Bug
}

class "CNG-1343" << (B,red) >> {
  Assigned to : Rajeswari Vijayal Neelakantan
  Summary : CNG - SOLR API - System Test -  maxScore not present in response for requests with score
  Status : Work Complete
  Type : Bug
}

class "CNG-797" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT: Unable to get the SOLR Response for Total Price field
  Status : Work Complete
  Type : Bug
}

class "CNG-434" << (B,red) >> {
  Assigned to : Baranipriya Ramanathan
  Summary : Burst stopped running automatically
  Status : Work Complete
  Type : Bug
}

class "CNG-558" << (S,lightblue) >> {
  Summary : Solr API - SIT
  Status : To Do
  Type : Sub-task
}

class "CNG-437" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Inappropriate Data Types used for fields across the different indexes
  Status : Work Complete
  Type : Bug
}

class "CNG-1341" << (B,red) >> {
  Assigned to : Rajeswari Vijayal Neelakantan
  Summary : CNG - SOLR API - System Test - Date format issue with milli seconds
  Status : Work Complete
  Type : Bug
}

class "CNG-436" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Inconsistent Paxmix field types and names across different indexes
  Status : Work Complete
  Type : Bug
}

class "CNG-1350" << (B,red) >> {
  Assigned to : Naveen Kumar S
  Summary : CNG-SOLR API-System test -overallCabin: 'M' only is not returned by default in solr response,when overallCabin is not specified in solr request.
  Status : Work Complete
  Type : Bug
}

class "CNG-691" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLr-Safe handler is not giving response.
  Status : Work Complete
  Type : Bug
}

class "CNG-693" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLr-query handler is not giving response.
  Status : Work Complete
  Type : Bug
}

class "CNG-451" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - Incorrect loyalty points showing in cache for Club Bookings
  Status : Work Complete
  Type : Bug
}

class "CNG-692" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SOLr-bahpricefeed handler is not giving response.
  Status : Work Complete
  Type : Bug
}

class "CNG-966" << (B,red) >> {
  Assigned to : Nigel Hassett
  Summary : CNG - Batch - Xdistributor- ST - inconsistent sessionid formats from captwov2 stack 4 batch controller
  Status : Work Complete
  Type : Bug
}

class "CNG-449" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : Display of datetime fields in Kibana is not as per the availability response
  Status : Work Complete
  Type : Bug
}

class "CNG-969" << (B,red) >> {
  Assigned to : Jayanth Vignesh
  Summary : SIT SIP- Checkout dates  not populated correctly in SIP Response
  Status : Work Complete
  Type : Bug
}

class "CNG-1358" << (B,red) >> {
  Assigned to : Dilip Kandamuthu
  Summary : CNG - SOLR API - System Test - Facet.field is not working properly for fields having data type as Float, Date and Boolean
  Status : Work Complete
  Type : Bug
}

class "CNG-686" << (S,lightblue) >> {
  Summary : CNG - Burst & Batch Controller - SIT
  Status : QA
  Type : Sub-task
}

class "CNG-444" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG - Batch (CAPTWO) - Impacted Component - Service - CNG UAT - F+C Packages - Not all being cached when compared against front end
  Status : Work Complete
  Type : Bug
}

class "CNG-840" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-depDate is not shown properly for FC Proposition in SOLR response
  Status : Work Complete
  Type : Bug
}

class "CNG-443" << (B,red) >> {
  Assigned to : Tony Cassidy
  Summary : CNG UAT - Price difference due to overnight flight as part of FH Package
  Status : Work Complete
  Type : Bug
}

class "CNG-963" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT SIP- Text format is not proper
  Status : Work Complete
  Type : Bug
}

class "CNG-446" << (B,red) >> {
  Assigned to : Merin Joseph
  Summary : CNG UAT - Burst and/or Batch process is down since 15:40
  Status : Work Complete
  Type : Bug
}

class "CNG-841" << (B,red) >> {
  Assigned to : Amreen Fathima
  Summary : SIT-Total price value is not Integer in the SOLR response
  Status : Work Complete
  Type : Bug
}

class "CNG-1355" << (B,red) >> {
  Assigned to : Naveen Kumar S
  Summary : CNG - SOLR API - System Test - Date/YEAR is not working for all propositions
  Status : Work Complete
  Type : Bug
}

class "CNG-1352" << (B,red) >> {
  Assigned to : Rajeswari Vijayal Neelakantan
  Summary : CNG - SOLR API - System Test - Facet issues with limit and mincount
  Status : Work Complete
  Type : Bug
}



' Links =======
"CNG-772" <.. "CNG-686" : Relates
"CNG-992" <.. "CNG-585" : Relates
"CNG-512" <.. "CNG-686" : Relates
"CNG-796" <.. "CNG-558" : Approval
"CNG-936" <.. "CNG-585" : Relates
"CNG-938" <.. "CNG-585" : Relates
"CNG-938" <.. "CNG-558" : Relates
"CNG-945" <.. "CNG-585" : Relates
"CNG-915" <.. "CNG-585" : Relates
"CNG-970" <.. "CNG-585" : Relates
"CNG-969" <.. "CNG-585" : Relates
"CNG-963" <.. "CNG-585" : Relates
"CNG-1248" <.. "CNG-1205" : Relates
"CNG-896" <.. "CNG-879" : Relates
"CNG-879" <.. "CNG-708" : Approval
"CNG-878" <.. "CNG-708" : Relates
"CNG-876" <.. "CNG-708" : Approval
"CNG-891" <.. "CNG-881" : Relates
"CNG-891" <.. "CNG-558" : Relates
"CNG-890" <.. "CNG-881" : Relates
"CNG-890" <.. "CNG-558" : Relates
"CNG-882" <.. "CNG-879" : Relates
"CNG-882" <.. "CNG-876" : Relates
"CNG-694" <.. "CNG-558" : Relates
"CNG-459" <.. "CNG-483" : Relates
"CNG-458" <.. "CNG-485" : Relates
"CNG-470" <.. "CNG-486" : Approval
"CNG-467" <.. "CNG-483" : Relates
"CNG-431" <.. "CNG-432" : Approval
"CNG-437" <.. "CNG-436" : Relates
"CNG-691" <.. "CNG-558" : Relates
"CNG-693" <.. "CNG-558" : Relates
"CNG-692" <.. "CNG-558" : Relates
"CNG-855" <.. "CNG-558" : Relates
"CNG-855" <.. "CNG-860" : Relates
"CNG-867" <.. "CNG-558" : Approval
"CNG-862" <.. "CNG-558" : Relates
"CNG-861" <.. "CNG-558" : Relates
"CNG-863" <.. "CNG-558" : Relates
"CNG-838" <.. "CNG-558" : Relates
"CNG-499" <.. "CNG-498" : Bundles
"CNG-479" <.. "CNG-460" : Relates


@enduml
