@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Mon Apr 15 12:32:40 CEST 2024

hide empty members

legend
Jira Ticket Status
----
(UAT) : 1
----
Jira Ticket Types
----
(Story) : 1
end legend


' Tickets =======
class "CNG-257" << (S,lightgreen) >> {
  Assigned to : Tony Cassidy
  Status : UAT
  Type : Story
}



' Links =======


@enduml
