@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue May 14 12:13:26 CEST 2024

title Jira Tickets for Epic Product footer
hide empty members

legend
Jira Ticket Status
----
(Done) : 1
----
Jira Ticket Types
----
(Epic) : 1
end legend


' Tickets =======
class "ENKPS-41" << (E,green) >> {
  Summary : Product footer
  Status : Done
  Type : Epic
}



' Links =======

' Parents =======



@enduml
