@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generated at    : Tue May 14 10:46:39 CEST 2024

title Jira Tickets for Status In Review
hide empty members

legend
Jira Ticket Status
----
(In Review) : 1
----
Jira Ticket Types
----
(Task) : 1
end legend


' Tickets =======
class "ENKPS-46" << (T,lightblue) >> {
  Summary : Build icon functionality component
  Assigned to : Oliver Oenang
  Status : In Review
  Type : Task
  Points : 2.0
}



' Links =======


@enduml
